/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/hotels": {
    /** Retrieve list of property information for all properties actively mapped to a single channel code.  <p><strong>OperationId:</strong>getPropertiesSummary</p> */
    get: operations["getPropertiesSummary"];
  };
  "/hotels/{hotelCode}": {
    /** Retrieve property information for a single property. <p><strong>OperationId:</strong>getPropertyInfo</p> */
    get: operations["getPropertyInfo"];
  };
  "/hotels/{hotelCode}/roomTypes": {
    /** Retrieve room types information for a single property. <p><strong>OperationId:</strong>getRoomTypesInfo</p> */
    get: operations["getRoomTypesInfo"];
  };
  "/hotels/{hotelCode}/ratePlans": {
    /** Retrieve rate plans information for a single property. <p><strong>OperationId:</strong>getRatePlans</p> */
    get: operations["getRatePlansInfo"];
  };
  "/hotels/{hotelCode}/rateRooms": {
    /** Retrieve rate plan and room type mapping information for a single property. <p><strong>OperationId:</strong>getRateRooms</p> */
    get: operations["getRateRooms"];
  };
}

export interface definitions {
  /** @description Rate Rooms Response */
  RateRoomsResponse: {
    /** @description Collection of the returned RateRooms for given channel */
    rateRooms?: definitions["ContentRateRoom"][];
    /** @example 50 */
    count?: number;
    /** @example true */
    hasMore?: boolean;
    /** @example 100 */
    limit?: number;
    /** @example 25 */
    offset?: number;
    /** @example 500 */
    totalResults?: number;
  };
  ContentRateRoom: {
    /**
     * @description A code for a rate plan for a requested channel.
     * @example XDAILY
     */
    ratePlanCode?: string;
    /**
     * @description A rate plan code for a hotel.
     * @example DAILY
     */
    hotelRatePlanCode?: string;
    /**
     * @description A code for a room type for a requested channel.
     * @example XA1K
     */
    roomType?: string;
    /**
     * @description A room type code for a hotel.
     * @example A1K
     */
    hotelRoomType?: string;
    /**
     * @description It represent if the rate room is active or inactive. Default value is true.
     * @example true
     */
    active?: boolean;
    /** @description It holds list of elements that defines room type occupancy information. */
    occupancy?: definitions["Occupancy"];
  };
  Occupancy: {
    /**
     * Format: int32
     * @description Assigned Type: ota2-0500:NonNegativeInteger
     * @example 2
     */
    minOccupancy?: number;
    /**
     * Format: int32
     * @description Assigned Type: ota2-0500:NonNegativeInteger
     * @example 8
     */
    maxOccupancy?: number;
    /**
     * Format: int32
     * @description Assigned Type: ota2-0500:NonNegativeInteger
     * @example 4
     */
    maxAdultOccupancy?: number;
    /**
     * Format: int32
     * @description Assigned Type: ota2-0500:NonNegativeInteger
     * @example 3
     */
    maxChildOccupancy?: number;
  };
  /** @description Rate Plans Response */
  RatePlansResponse: {
    /** @description Collection of the returned Rate Plans for a given channel */
    ratePlans?: definitions["ContentRatePlan"][];
    /** @example 50 */
    count?: number;
    /** @example true */
    hasMore?: boolean;
    /** @example 100 */
    limit?: number;
    /** @example 25 */
    offset?: number;
    /** @example 500 */
    totalResults?: number;
  };
  ContentRatePlan: {
    /**
     * @description A rate plan code for a hotel.
     * @example DAILY
     */
    hotelRatePlanCode?: string;
    /**
     * @description A code for a rate plan for a requested channel.
     * @example XDAILY
     */
    ratePlanCode?: string;
    /**
     * @description It represent if the rate is active or inactive.
     * @example true
     */
    active?: boolean;
    /**
     * @description It represents whether rate is tax Inclusive or not.
     * @example true
     */
    taxInclusive?: boolean;
    /**
     * @description currency code
     * @example USD
     */
    currencyCode?: string;
    /** @description if the rate plan is negotiated or not */
    negotiated?: boolean;
    /**
     * @description Code of the Channel Rate Plan Type
     * @example 10
     */
    ratePlanType?: string;
    /** @description Rate Plan Name */
    ratePlanName?: string;
    /** @description Indicates if an ID is required during the Check-In for this rate booking */
    identificationRequired?: boolean;
    /** @description The rate level associated with the rate code */
    ratePlanLevel?: string;
    /** @description The rate category associated with the rate plan code */
    ratePlanCategory?: string;
    gdsDescription?: definitions["Description"];
    /** @description Type of meal plan the rate plan includes */
    mealPlan?: definitions["OfferMealPlan"];
    /** @description Cancellation policy schedule(s) and detail(s) */
    cancellationPolicies?: definitions["CancellationPolicies"];
  };
  Description: {
    line1?: string;
    line2?: string;
    line3?: string;
    detailedDescription?: string;
  };
  /** @description The list of cancellation policies attached to a rate plan */
  CancellationPolicies: definitions["CancellationPoliciesItem"][];
  /** @description The cancellation policy containing its schedules and policy details */
  CancellationPoliciesItem: {
    policy?: definitions["CancellationPolicy"];
    scheduleDetail?: definitions["CancellationPolicyScheduleDetail"];
  };
  /** @description The cancellation policy schedule detail */
  CancellationPolicyScheduleDetail: {
    /**
     * Format: date
     * @description The start date the cancellation policy schedule is effective
     * @example 2025-11-01
     */
    start?: string;
    /**
     * Format: date
     * @description The end date the cancellation policy is no longer effective
     * @example 2025-11-07
     */
    end?: string;
  };
  /** @description The cancellation policy details */
  CancellationPolicy: {
    /**
     * @description The cancellation policy code
     * @example 1 DAY
     */
    policyCode?: string;
    /**
     * @description The cancellation policy description
     * @example 1 Day prior to arrival, forfeit 1 night
     */
    description?: string;
    /**
     * @description Cancellation policy deadline
     * @example {
     *   "offsetFromArrival": 5,
     *   "offsetDropTime": "2000-01-01T22:00:00.000Z",
     *   "offsetFromBookingDate": 3
     * }
     */
    deadline?: definitions["CancellationPolicyDeadline"];
    /**
     * @description Cancellation fee expressed as a fixed amount, or percentage of/or room nights.
     * @example {
     *   "basisType": "FlatAmount",
     *   "amount": 100
     * }
     */
    amountPercent?: definitions["CancellationPolicyAmountPercentType"];
    /**
     * @description Does this cancellation policy override another cancellation policy
     * @example true
     */
    override?: boolean;
  };
  /** @description The cancellation policy deadline */
  CancellationPolicyDeadline: {
    /**
     * @description The number of days before arrival that allows cancellation without penalties.
     * @example 5
     */
    offsetFromArrival?: number;
    /**
     * @description Time on offset day the cancellation penalties applies. 24-hour format, hh:mm
     * @example 22:00
     */
    offsetDropTime?: string;
  };
  CancellationPolicyAmountPercentType: definitions["CancellationPolicyBasicAmountPercentType"] & {
    /**
     * @description Cancellation policy basis type
     * @example NightPercentage
     */
    basisType?: definitions["CancellationPolicyBasisType"];
  };
  CancellationPolicyBasicAmountPercentType: {
    /**
     * @description Number of nights of the hotel stay used to calculate the fee amount when basisType=Nights.
     * @example 2
     */
    nights?: number;
    /**
     * Format: double
     * @description Percentage used to calculate the amount when basisType=Percentage
     * @example 50
     */
    percent?: number;
    /**
     * Format: double
     * @description Percentage used to calculate the amount when basisType=NightPercentage.
     * @example 66.6
     */
    nightPercent?: number;
    /**
     * Format: double
     * @description Monetary amount when basisType=FlatAmount.
     * @example 540
     */
    amount?: number;
  };
  /**
   * @description The method to be used to compute the penalty. Nights - The penalty amount is determined by the guest's room rate plus any packages, and generates associated with the rate for this number of nights. For example, assume the guest is planning to stay 3 nights. If the Penalty Amount is 1, and the nightly room rate is $150, the cancellation charge would be $150 ($150 x 1 nights). Percentage - The penalty amount is the percentage of the entire stay's room rate, plus any packages and generates associated with the rate, that will be taken for a cancellation charge. For example, if the Penalty Amount is 50, the guest will pay a charge of 50% of the total stay room rate. If the room rate is $300 a night for 3 nights, the guest pays$450 (0.50 x $900). NightPercentage - The penalty amount is based on the percentage of the first night's room rate. Schedule the time period when this rule is effective. FlatAmount - The penalty amount is the exact amount of the cancellation charge in the property currency. NonCancelable - The reservation can't be canceled. It will be resulted in penalty of the total cost of stay.
   * @enum {string}
   */
  CancellationPolicyBasisType:
    | "Nights"
    | "Percentage"
    | "NightPercentage"
    | "FlatAmount"
    | "NonCancelable";
  OfferMealPlan: {
    /**
     * @description The meal plan code
     * @example 1
     */
    mealPlanCode?: string;
    /**
     * @description The meal plan description
     * @example All inclusive meal plan
     */
    mealPlanDescription?: string;
    /** @description Type of meal plan */
    mealsIncluded?: definitions["OfferRatePlanMealType"][];
  };
  /**
   * @description Type of meal the rate plan includes
   * @enum {string}
   */
  OfferRatePlanMealType: "Breakfast" | "Lunch" | "Dinner";
  /** @description Room Types Response */
  RoomTypesResponse: {
    /** @description Collection of the returned Room Types for given channel */
    roomTypes?: definitions["ContentRoomType"][];
    /** @example 50 */
    count?: number;
    /** @example true */
    hasMore?: boolean;
    /** @example 100 */
    limit?: number;
    /** @example 25 */
    offset?: number;
    /** @example 500 */
    totalResults?: number;
  };
  /** @description Room Type information */
  ContentRoomType: {
    /**
     * @description A room type code for a hotel.
     * @example A1K
     */
    hotelRoomType?: string;
    /**
     * @description A code for a room type for a requested channel.
     * @example XA1K
     */
    roomType?: string;
    description?: string[];
    /** @example 102 */
    roomName?: string;
    /** @example SUITE */
    roomCategory?: string;
    roomAmenities?: definitions["ContentRoomAmenity"][];
    roomViewType?: string;
    roomPrimaryBedType?: string;
    /** @example true */
    nonSmokingInd?: boolean;
    occupancy?: definitions["Occupancy"];
    /**
     * @description number of rooms requested
     * @example 1
     */
    numberOfUnits?: number;
  };
  ContentRoomAmenity: {
    roomAmenity?: string;
    description?: string;
    quantity?: number;
    includeInRate?: boolean;
    confirmable?: boolean;
  };
  PropertyInfoResponse: {
    propertyInfo?: definitions["ContentPropertyInfo"];
  };
  /** @description Property information */
  ContentPropertyInfo: {
    /**
     * @description Unique ID that identifies a single hotel property
     * @example Hotel1
     */
    hotelId?: string;
    /**
     * @description The Enterprise ID of the property it belongs to
     * @example Hotel1
     */
    enterpriseId?: string;
    /**
     * @description A channel hotel code
     * @example XUSXXYY99
     */
    hotelCode?: string;
    /**
     * @description A full name of a hotel
     * @example Resort1
     */
    hotelName?: string;
    /** @description Description of a hotel */
    hotelDescription?: string;
    /**
     * @description Channel chain code for a property
     * @example CHAIN1
     */
    chainCode?: string;
    /**
     * @description Code of the cluster
     * @example CLU123
     */
    clusterCode?: string;
    address?: definitions["Address"];
    /**
     * Format: double
     * @description Latitude of a hotel
     * @example 15
     */
    latitude?: number;
    /**
     * Format: double
     * @description Longitude of a hotel
     * @example 40
     */
    longitude?: number;
    propertyAmenities?: definitions["PropertyOffersHotelAmenity"][];
    pointOfInterest?: definitions["OfferPointOfInterest"][];
    /**
     * @description Property level marketing message.
     * @example Thank you for choosing our property.
     */
    marketingMessage?: string;
    /**
     * @description currency code
     * @example USD
     */
    currencyCode?: string;
    /**
     * @description Primary Language spoken at the property
     * @example en-us
     */
    primaryLanguage?: string;
    /**
     * @description The total number of guest rooms for the property
     * @example 5
     */
    totalNumberOfRooms?: number;
    /**
     * @description Hotel pet policy.
     * @enum {string}
     */
    petPolicy?:
      | "Pets allowed"
      | "Pets not allowed"
      | "Assistive animals only"
      | "Pets by arrangement"
      | "Other_";
    hotelChildPolicy?: definitions["HotelChildPolicy"];
    timeZone?: definitions["TimeZone"];
    generalInformation?: definitions["GeneralInformation"];
    communications?: definitions["Communications"];
    transportations?: definitions["Transportation"][];
    direction?: definitions["Direction"];
    location?: definitions["Location"];
  };
  GeneralInformation: {
    /** @example 04:30 */
    checkInTime?: string;
    /** @example 14:30 */
    checkOutTime?: string;
  };
  HotelChildPolicy: {
    kidsStayFreeInd?: boolean;
    /** @example 5 */
    usualStayFreeCutoffAge?: number;
    /** @example 18 */
    maxChildAge?: number;
  };
  TimeZone: {
    /**
     * @description Zone Name of the region
     * @example Asia/Calcutta
     */
    timeZoneName?: string;
    /**
     * @description Provides the current offset from UTC for the specified time zone, considering DST
     * @example UTC+05:30
     */
    offset?: string;
  };
  Direction: {
    /** @example SE ABC hills */
    propertyDirection?: string;
  };
  Transportation: {
    /**
     * @description Transportation type ex: Bus, Taxi. Enum values from globalCodes TRP - Transportation Code
     * @example Metro
     */
    transportationCode?: string;
    /** @example Description for a Transportation */
    description?: string;
    /**
     * @description Indicates whether charge rate is included or excluded
     * @example false
     */
    includeInRate?: boolean;
    /**
     * @description Indicates whether reservation is required for this Transportation
     * @example true
     */
    reservationRequired?: boolean;
  };
  /** @description The contact information for the property */
  Communications: {
    /** @description List of phone numbers for the property */
    phones?: definitions["Phone"][];
    /** @description List of emails addresses for the property */
    emails?: definitions["Email"][];
    /** @description List of urls for the property */
    urls?: definitions["Url"][];
  };
  Email: {
    /** @description The email type */
    emailType?: string;
    /** @description The email address for the specific emailType */
    email?: string;
  };
  Url: {
    /** @description The url or internet web address */
    url?: string;
  };
  Phone: {
    /** @description The type of technology associated with the telephone number */
    phoneTechType?: string;
    /** @description Describes the location of the phone */
    phoneLocationType?: string;
    /** @description The phone number assigned to a specific location */
    phoneNumber?: string;
  };
  Location: {
    /** @example ABC hills */
    propertyLocation?: string;
  };
  /** @description The point of interest for guests to get to the hotel. */
  OfferPointOfInterest: {
    /**
     * @description The name of the point of interest.
     * @example Dallas airport, Park
     */
    name?: string;
    /**
     * @description The point of interest type available to choose.
     * @example AIRPORT
     * @enum {string}
     */
    pointOfInterestType?: "AIRPORT" | "ATTRACTIONS";
    /** @description The description of the point of interest. */
    description?: string;
    /**
     * @description The unique 3 letter IATA code to identify the airport.
     * @example DAL
     */
    airportCode?: string;
    /**
     * Format: double
     * @description The distance from the point of interest to the hotel
     * @example 6
     */
    distance?: number;
    /**
     * @description Unit of measurement for the distance
     * @example Kilometers
     */
    distanceUnit?: string;
    /**
     * @description The attraction direction from point of interest to the hotel.
     * @example N
     * @enum {string}
     */
    attractionDirection?: "N" | "W" | "S" | "E" | "NW" | "NE" | "SW" | "SE";
    /**
     * @description The transportation type for the chosen point of interest.
     * @example [
     *   "objId"
     * ]
     */
    transportation?: string[];
    /**
     * @description The description for how to get from point of interest to the hotel.
     * @example Free text to describe route from property to attraction
     */
    directionDescription?: string;
    /**
     * Format: double
     * @description The driving time it will take to get from point of interest to the hotel.
     * @example 3.5
     */
    drivingTime?: number;
  };
  PropertyOffersHotelAmenity: {
    /**
     * @description Feature available at a hotel
     * @example 12
     */
    hotelAmenity?: string;
    /**
     * @description Description of a hotel amenity
     * @example Swimming Pool
     */
    description?: string;
    /**
     * @description Quantity of a hotel amenity
     * @example 1
     */
    quantity?: number;
    /**
     * @description Indicates if an amenity is included in a room rate
     * @example true
     */
    includeInRate?: boolean;
    /**
     * @description If a hotel amenity is confirmed to be available
     * @example false
     */
    confirmable?: boolean;
  };
  Address: {
    /**
     * @description The property's street address
     * @example [
     *   "Street 123",
     *   "Box 1"
     * ]
     */
    addressLine?: string[];
    /**
     * @description The property's two letter ISO country code
     * @example US
     */
    countryCode?: string;
    /**
     * @description The city where the property is located
     * @example Miami
     */
    cityName?: string;
    /**
     * @description The state where the property is located
     * @example Florida
     */
    stateProv?: string;
    /**
     * @description The property's postal (ZIP) code
     * @example 90210
     */
    postalCode?: string;
  };
  /** @description Common Error Response format */
  ExceptionDetail: {
    /**
     * @description Short, human-readable summary of the problem.  The summary SHOULD NOT change for subsequent occurrences of the problem, except for purposes of localization.
     * @example Error in Application
     */
    title?: string;
    /**
     * @description HTTP status code for this occurrence of the problem, set by the origin server.
     * @example 400
     */
    status?: number;
    /**
     * @description Business specific Error code, which is different from HTTP error code.
     * @example RSV-34534534
     */
    "o:errorCode"?: string;
    /**
     * @description Absolute URI [RFC3986] that identifies the problem type. When dereferenced, it SHOULD provide a human-readable summary of the problem.
     * @example http://www.w3.org/Protocols/rfc2616/rfc2616-sec10.html#sec10.4
     */
    type?: string;
    /**
     * Format: date-time
     * @description The UTC Date and Time of the Error happened.
     * @example 2022-01-02T11:30:22.234Z
     */
    timestamp?: string;
    /** @description Details of the error message, consisting of a hierarchical tree structure */
    "o:errorDetails"?: definitions["ExceptionDetail"][];
    /**
     * @description An ID for support reasons to be able identify errors better.
     * @example 334543532224
     */
    logId?: number;
  };
  PropertyInfoSummaryResponse: {
    /**
     * @description Boolean value that is set to true if more resources are available on the server than the subset returned in current page.
     * @example true
     */
    hasMore?: boolean;
    /**
     * @description Total count of the resource instances, including both the instances in the current range and the instances on the server that satisfy the request.
     * @example 100
     */
    totalResults?: number;
    /**
     * @description Actual paging size used by the server.
     * @example 100
     */
    limit?: number;
    /**
     * @description Number of resource instances returned in the current range.
     * @example 100
     */
    count?: number;
    /**
     * @description Offset value used in the current page.
     * @example 1
     */
    offset?: number;
    hotels?: definitions["OfferDetailsPropertyInfoSummary"][];
  };
  /** @description Property information */
  OfferDetailsPropertyInfoSummary: {
    /**
     * @description Unique ID that identifies a single hotel property
     * @example Hotel1
     */
    hotelId?: string;
    /**
     * @description The external Hotel/property Id for a channel
     * @example XUSXXYY99
     */
    hotelCode?: string;
    /**
     * @description The descriptive name of a property
     * @example The Palmyra Resort
     */
    hotelName?: string;
    /**
     * @description Channel chain code for a property
     * @example CHAIN1
     */
    chainCode?: string;
    /**
     * @description Channel's hotel/property brand code
     * @example BRAND1
     */
    brandCode?: string;
    /**
     * Format: date
     * @description The date this property will be active for the channel
     * @example 2023-08-03
     */
    startDate?: string;
    /**
     * Format: date
     * @description The date this property will be deactivate for the channel
     * @example 2024-09-04
     */
    endDate?: string;
    /** @description Address Details such as city, state, country, postal code etc for a hotel property */
    address?: definitions["Address"];
    /** @description The contact information for the property */
    communications?: definitions["Communications"];
    /** @description The connection information for the channel */
    connectionInformation?: definitions["ConnectionInformation"];
  };
  /** @description Channel Connection Information for the hotel property */
  ConnectionInformation: {
    /**
     * @description Channel connection status
     * @enum {string}
     */
    connectionStatus?: "TEST" | "ACTIVE" | "MAINTENANCE";
    /**
     * Format: date-time
     * @description Channel connection status last changed on this date time
     * @example 2022-01-02T11:30:22.234Z
     */
    connectionStatusLastChangedOn?: string;
    /**
     * @description ARI message format
     * @example Oracle_v1
     * @enum {string}
     */
    defaultARIMessageFormat?: "Oracle_v1" | "AdsRateUpdate" | "AdsRateAmount";
    /** @description The web service location (URL) of the distribution partners where Oracle Hospitality Distribution ARI service will post messages such as the property inventory, restrictions/availability, rate schedules updates, etc. */
    channelRoutes?: definitions["ChannelRouteType"][];
  };
  ChannelRouteType: definitions["ModifiableChannelRouteType"] & {
    messageType?: definitions["MessageType"];
  };
  /**
   * @description Message type that is enabled. <p>AvailNotif -  Indicates enable for hotel restrictions update </p> <p>RatePlanNotif - Indicates enable for hotel rate and room pricing update </p> <p>InvCountNotif - Indicates enable for hotel inventory counts update </p> <p>GetRooms - Indicates enable to fetch rooms from the distribution partner system </p> <p>GetRatePlans - Indicates enable to fetch rates from the distribution partner system </p>
   * @example AvailNotif
   * @enum {string}
   */
  MessageType:
    | "AvailNotif"
    | "RatePlanNotif"
    | "InvCountNotif"
    | "GetRooms"
    | "GetRatePlans";
  ModifiableChannelRouteType: {
    url?: definitions["MessageUrl"];
  };
  /**
   * @description Message URL
   * @example https://pms-certification.profit.net/opera-cloud
   */
  MessageUrl: string;
}

export interface parameters {
  /** @description Channel code */
  "x-channelCode": string;
  /**
   * @description The optional additional information to be included in the response
   * @enum {string}
   */
  fetchInstructionsRatePlans: "Policy";
  /** @description Unique tracing key e.g. 4664ab3423434a45 */
  "x-request-id": string;
  /** @description Room Type */
  roomType: string;
  /** @description Rate Plan code */
  ratePlanCode: string;
  /**
   * @description If true include inactive rateRooms. Default is False
   * @default false
   */
  includeInactive: boolean;
  /**
   * @description Channel connection status
   * @enum {string}
   */
  connectionStatus: "TEST" | "ACTIVE" | "MAINTENANCE";
  /** @description Client or Partner's Application Key */
  "x-app-key": string;
  /**
   * Format: date-time
   * @description Channel connection status last changed before this time
   */
  connectionStatusLastChangedTo: string;
  /** @description Hotel Code */
  HotelCode: string;
  /**
   * @description Set this true to include Negotiated rate plans along with public rate plans. Default is False
   * @default false
   */
  includeNegotiatedRates: boolean;
  /**
   * @description The optional summary sections to be included in the response
   * @enum {string}
   */
  fetchInstructions: "ConnectionInformation";
  /**
   * @description If true include room amenities along with each room type. Default is False
   * @default false
   */
  includeRoomAmenities: boolean;
  /**
   * @description Non-negative integer values that specifies the index of the first item to be returned. The offset index begins at 0. By default, the offset is 0, which returns all items starting from the first item in the collection
   * @default 0
   */
  offset: number;
  /**
   * @description Integer, the maximal number of item entities to be returned
   * @default 20
   */
  limit: number;
  /**
   * Format: date-time
   * @description Channel connection status last changed after this time
   */
  connectionStatusLastChangedFrom: string;
  /**
   * @description Bearer token that needs to be passed which is generated post user
   *   authentication
   */
  authorization: string;
  /** @description Customer's Integration Application Id */
  "x-originating-application": string;
}

export interface operations {
  /** Retrieve list of property information for all properties actively mapped to a single channel code.  <p><strong>OperationId:</strong>getPropertiesSummary</p> */
  getPropertiesSummary: {
    parameters: {
      header: {
        /**
         * Bearer token that needs to be passed which is generated post user
         *   authentication
         */
        authorization: parameters["authorization"];
        /** Channel code */
        "x-channelCode": parameters["x-channelCode"];
        /** Client or Partner's Application Key */
        "x-app-key"?: parameters["x-app-key"];
        /** Unique tracing key e.g. 4664ab3423434a45 */
        "x-request-id"?: parameters["x-request-id"];
        /** Customer's Integration Application Id */
        "x-originating-application"?: parameters["x-originating-application"];
      };
      query: {
        /** Channel connection status last changed after this time */
        connectionStatusLastChangedFrom?: parameters["connectionStatusLastChangedFrom"];
        /** Channel connection status last changed before this time */
        connectionStatusLastChangedTo?: parameters["connectionStatusLastChangedTo"];
        /** Channel connection status */
        connectionStatus?: parameters["connectionStatus"];
        /** The optional summary sections to be included in the response */
        fetchInstructions?: parameters["fetchInstructions"];
        /** Integer, the maximal number of item entities to be returned */
        limit?: parameters["limit"];
        /** Non-negative integer values that specifies the index of the first item to be returned. The offset index begins at 0. By default, the offset is 0, which returns all items starting from the first item in the collection */
        offset?: parameters["offset"];
      };
    };
    responses: {
      /** Response object for property info */
      200: {
        headers: {};
        schema: definitions["PropertyInfoSummaryResponse"];
      };
      /** Request data provided is invalid */
      400: {
        schema: definitions["ExceptionDetail"];
      };
      /** Unauthorized */
      401: {
        schema: definitions["ExceptionDetail"];
      };
      /** Forbidden */
      403: {
        schema: definitions["ExceptionDetail"];
      };
      /** Not Found */
      404: {
        schema: definitions["ExceptionDetail"];
      };
      /** Not Allowed */
      405: {
        schema: definitions["ExceptionDetail"];
      };
      /** Not Acceptable */
      406: {
        schema: definitions["ExceptionDetail"];
      };
      /** Payload Too Large */
      413: {
        schema: definitions["ExceptionDetail"];
      };
      /** URI Too Long */
      414: {
        schema: definitions["ExceptionDetail"];
      };
      /** Unsupported Media Type */
      415: {
        schema: definitions["ExceptionDetail"];
      };
      /** Internal Server Error */
      500: {
        schema: definitions["ExceptionDetail"];
      };
      /** Bad Gateway */
      502: {
        schema: definitions["ExceptionDetail"];
      };
      /** Service Unavailable */
      503: {
        schema: definitions["ExceptionDetail"];
      };
    };
  };
  /** Retrieve property information for a single property. <p><strong>OperationId:</strong>getPropertyInfo</p> */
  getPropertyInfo: {
    parameters: {
      header: {
        /**
         * Bearer token that needs to be passed which is generated post user
         *   authentication
         */
        authorization: parameters["authorization"];
        /** Channel code */
        "x-channelCode": parameters["x-channelCode"];
        /** Client or Partner's Application Key */
        "x-app-key"?: parameters["x-app-key"];
        /** Unique tracing key e.g. 4664ab3423434a45 */
        "x-request-id"?: parameters["x-request-id"];
        /** Customer's Integration Application Id */
        "x-originating-application"?: parameters["x-originating-application"];
      };
      path: {
        /** Hotel Code */
        hotelCode: parameters["HotelCode"];
      };
    };
    responses: {
      /** Response object for property info */
      200: {
        headers: {};
        schema: definitions["PropertyInfoResponse"];
      };
      /** Request data provided is invalid */
      400: {
        schema: definitions["ExceptionDetail"];
      };
      /** Unauthorized */
      401: {
        schema: definitions["ExceptionDetail"];
      };
      /** Forbidden */
      403: {
        schema: definitions["ExceptionDetail"];
      };
      /** Not Found */
      404: {
        schema: definitions["ExceptionDetail"];
      };
      /** Not Allowed */
      405: {
        schema: definitions["ExceptionDetail"];
      };
      /** Not Acceptable */
      406: {
        schema: definitions["ExceptionDetail"];
      };
      /** Payload Too Large */
      413: {
        schema: definitions["ExceptionDetail"];
      };
      /** URI Too Long */
      414: {
        schema: definitions["ExceptionDetail"];
      };
      /** Unsupported Media Type */
      415: {
        schema: definitions["ExceptionDetail"];
      };
      /** Internal Server Error */
      500: {
        schema: definitions["ExceptionDetail"];
      };
      /** Bad Gateway */
      502: {
        schema: definitions["ExceptionDetail"];
      };
      /** Service Unavailable */
      503: {
        schema: definitions["ExceptionDetail"];
      };
    };
  };
  /** Retrieve room types information for a single property. <p><strong>OperationId:</strong>getRoomTypesInfo</p> */
  getRoomTypesInfo: {
    parameters: {
      header: {
        /**
         * Bearer token that needs to be passed which is generated post user
         *   authentication
         */
        authorization: parameters["authorization"];
        /** Channel code */
        "x-channelCode": parameters["x-channelCode"];
        /** Client or Partner's Application Key */
        "x-app-key"?: parameters["x-app-key"];
        /** Unique tracing key e.g. 4664ab3423434a45 */
        "x-request-id"?: parameters["x-request-id"];
        /** Customer's Integration Application Id */
        "x-originating-application"?: parameters["x-originating-application"];
      };
      path: {
        /** Hotel Code */
        hotelCode: parameters["HotelCode"];
      };
      query: {
        /** If true include room amenities along with each room type. Default is False */
        includeRoomAmenities?: parameters["includeRoomAmenities"];
        /** Room Type */
        roomType?: parameters["roomType"];
        /** Integer, the maximal number of item entities to be returned */
        limit?: parameters["limit"];
        /** Non-negative integer values that specifies the index of the first item to be returned. The offset index begins at 0. By default, the offset is 0, which returns all items starting from the first item in the collection */
        offset?: parameters["offset"];
      };
    };
    responses: {
      /** Response object for roomTypes info */
      200: {
        headers: {};
        schema: definitions["RoomTypesResponse"];
      };
      /** Request data provided is invalid */
      400: {
        schema: definitions["ExceptionDetail"];
      };
      /** Unauthorized */
      401: {
        schema: definitions["ExceptionDetail"];
      };
      /** Forbidden */
      403: {
        schema: definitions["ExceptionDetail"];
      };
      /** Not Found */
      404: {
        schema: definitions["ExceptionDetail"];
      };
      /** Not Allowed */
      405: {
        schema: definitions["ExceptionDetail"];
      };
      /** Not Acceptable */
      406: {
        schema: definitions["ExceptionDetail"];
      };
      /** Payload Too Large */
      413: {
        schema: definitions["ExceptionDetail"];
      };
      /** URI Too Long */
      414: {
        schema: definitions["ExceptionDetail"];
      };
      /** Unsupported Media Type */
      415: {
        schema: definitions["ExceptionDetail"];
      };
      /** Internal Server Error */
      500: {
        schema: definitions["ExceptionDetail"];
      };
      /** Bad Gateway */
      502: {
        schema: definitions["ExceptionDetail"];
      };
      /** Service Unavailable */
      503: {
        schema: definitions["ExceptionDetail"];
      };
    };
  };
  /** Retrieve rate plans information for a single property. <p><strong>OperationId:</strong>getRatePlans</p> */
  getRatePlansInfo: {
    parameters: {
      header: {
        /**
         * Bearer token that needs to be passed which is generated post user
         *   authentication
         */
        authorization: parameters["authorization"];
        /** Channel code */
        "x-channelCode": parameters["x-channelCode"];
        /** Client or Partner's Application Key */
        "x-app-key"?: parameters["x-app-key"];
        /** Unique tracing key e.g. 4664ab3423434a45 */
        "x-request-id"?: parameters["x-request-id"];
        /** Customer's Integration Application Id */
        "x-originating-application"?: parameters["x-originating-application"];
      };
      path: {
        /** Hotel Code */
        hotelCode: parameters["HotelCode"];
      };
      query: {
        /** Set this true to include Negotiated rate plans along with public rate plans. Default is False */
        includeNegotiatedRates?: parameters["includeNegotiatedRates"];
        /** Rate Plan code */
        ratePlanCode?: parameters["ratePlanCode"];
        /** The optional additional information to be included in the response */
        fetchInstructions?: parameters["fetchInstructionsRatePlans"];
        /** Integer, the maximal number of item entities to be returned */
        limit?: parameters["limit"];
        /** Non-negative integer values that specifies the index of the first item to be returned. The offset index begins at 0. By default, the offset is 0, which returns all items starting from the first item in the collection */
        offset?: parameters["offset"];
      };
    };
    responses: {
      /** Response object for property info */
      200: {
        headers: {};
        schema: definitions["RatePlansResponse"];
      };
      /** Request data provided is invalid */
      400: {
        schema: definitions["ExceptionDetail"];
      };
      /** Unauthorized */
      401: {
        schema: definitions["ExceptionDetail"];
      };
      /** Forbidden */
      403: {
        schema: definitions["ExceptionDetail"];
      };
      /** Not Found */
      404: {
        schema: definitions["ExceptionDetail"];
      };
      /** Not Allowed */
      405: {
        schema: definitions["ExceptionDetail"];
      };
      /** Not Acceptable */
      406: {
        schema: definitions["ExceptionDetail"];
      };
      /** Payload Too Large */
      413: {
        schema: definitions["ExceptionDetail"];
      };
      /** URI Too Long */
      414: {
        schema: definitions["ExceptionDetail"];
      };
      /** Unsupported Media Type */
      415: {
        schema: definitions["ExceptionDetail"];
      };
      /** Internal Server Error */
      500: {
        schema: definitions["ExceptionDetail"];
      };
      /** Bad Gateway */
      502: {
        schema: definitions["ExceptionDetail"];
      };
      /** Service Unavailable */
      503: {
        schema: definitions["ExceptionDetail"];
      };
    };
  };
  /** Retrieve rate plan and room type mapping information for a single property. <p><strong>OperationId:</strong>getRateRooms</p> */
  getRateRooms: {
    parameters: {
      header: {
        /**
         * Bearer token that needs to be passed which is generated post user
         *   authentication
         */
        authorization: parameters["authorization"];
        /** Channel code */
        "x-channelCode": parameters["x-channelCode"];
        /** Client or Partner's Application Key */
        "x-app-key"?: parameters["x-app-key"];
        /** Unique tracing key e.g. 4664ab3423434a45 */
        "x-request-id"?: parameters["x-request-id"];
        /** Customer's Integration Application Id */
        "x-originating-application"?: parameters["x-originating-application"];
      };
      path: {
        /** Hotel Code */
        hotelCode: parameters["HotelCode"];
      };
      query: {
        /** If true include inactive rateRooms. Default is False */
        includeInactive?: parameters["includeInactive"];
        /** Room Type */
        roomType?: parameters["roomType"];
        /** Rate Plan code */
        ratePlanCode?: parameters["ratePlanCode"];
        /** Integer, the maximal number of item entities to be returned */
        limit?: parameters["limit"];
        /** Non-negative integer values that specifies the index of the first item to be returned. The offset index begins at 0. By default, the offset is 0, which returns all items starting from the first item in the collection */
        offset?: parameters["offset"];
      };
    };
    responses: {
      /** Response object for property info */
      200: {
        headers: {};
        schema: definitions["RateRoomsResponse"];
      };
      /** Request data provided is invalid */
      400: {
        schema: definitions["ExceptionDetail"];
      };
      /** Unauthorized */
      401: {
        schema: definitions["ExceptionDetail"];
      };
      /** Forbidden */
      403: {
        schema: definitions["ExceptionDetail"];
      };
      /** Not Found */
      404: {
        schema: definitions["ExceptionDetail"];
      };
      /** Not Allowed */
      405: {
        schema: definitions["ExceptionDetail"];
      };
      /** Not Acceptable */
      406: {
        schema: definitions["ExceptionDetail"];
      };
      /** Payload Too Large */
      413: {
        schema: definitions["ExceptionDetail"];
      };
      /** URI Too Long */
      414: {
        schema: definitions["ExceptionDetail"];
      };
      /** Unsupported Media Type */
      415: {
        schema: definitions["ExceptionDetail"];
      };
      /** Internal Server Error */
      500: {
        schema: definitions["ExceptionDetail"];
      };
      /** Bad Gateway */
      502: {
        schema: definitions["ExceptionDetail"];
      };
      /** Service Unavailable */
      503: {
        schema: definitions["ExceptionDetail"];
      };
    };
  };
}

export interface external {}
