/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/hotels/{hotelId}/externalRoomKeys": {
    /**
     * API that manages requests for Door Lock Room Keys. This operation is used by OPERA Cloud connected to external Door Lock Systems systems via Outbound Systems configuration:
     *
     * <strong>OPERA Cloud utilizes this operation </strong>
     *
     * - to request new or additional room keys - e.g. when guest checks in, or additional keys post check in.
     *
     * - to request to activate new keys after check on e.g. when a room key has been lost for a room.
     *
     * - to request a room key which is not related to a guest reservation but valid for a defined time - (for show rooms, repair) - One Shot Key.
     *
     * - to request to re-encode a key whereby other keys for this room remain active.
     *
     * - to request to read a key data from a room key and display it to the user in the PMS.
     *
     * - to request to modify existing key data - upon room move or change of departure date. (online key systems only!!)
     *
     * - to request to remove / delete a room key from a room on. Usually sent with check out of a reservation.
     *
     * Use this API to post a room key action to the active Door Lock System.
     *
     * <strong>Notes on keyType values:</strong>
     *
     * <strong>keyType = New
     *
     * keyType = Lost </strong>
     *
     * It is expected that all previous active keys for the room will become invalid.
     *
     * It is expected that partner system handles multiple keys being active in case numberOfKeys is >1.
     *
     * <strong>keyType = Duplicate
     *
     * keyType = ReEncode</strong>
     *
     * It is expected that existing active keys for this room remain active.
     *
     * <strong>keyType = OneShot</strong>
     *
     * It is expected that the room key is only valid for a room for specific time (for maintenance or Show room).
     *
     * It is never related to a reservation.
     *
     * <strong>keyType = Read</strong> A request to the Key Card system to read Key Card information from requested Key Encoder/reader.
     *
     * The Key Read functionality is of pure informational purpose. None of the received information is stored or processed in the PMS, and it is only for display to the user.
     *
     * <strong>keyType = Remove</strong>
     *
     * It is expected that with this request all active keys for a room or reservation will become inactive or invalid so they will not be able to open the room after defined validityEnd time.
     *
     * <strong>Additional KeyType actions used by Online Door Lock Systems:</strong>
     *
     * <strong>Online Key card Systems</strong> are systems which do not write guest data to the room key directly but do store guest data internally and send the information to the related door lock.
     *
     * <strong>keyType = ModifyStay</strong>
     *
     * For Online Door Lock Systems - Request to adjust Room key data when guest changes length of stay (validityEnd)
     *
     * <strong>keyType = RoomMove</strong>
     *
     * For Online Door Lock Systems - adjust Room key data when guest performs room move.
     *
     * <p><strong>OperationId:</strong> postExternalRoomKeys</p>
     */
    post: operations["postExternalRoomKeys"];
  };
  "/hotels/{hotelId}/roomKeysOutbound": {
    /**
     * API that manages requests for Door Lock Room Keys. This operation is used by OPERA Cloud connected to external Door Lock Systems systems via Outbound Systems configuration:
     *
     * <strong>OPERA Cloud utilizes this operation </strong>
     *
     * - to request new or additional room keys - e.g. when guest checks in, or additional keys post check in.
     *
     * - to request to activate new keys after check on e.g. when a room key has been lost for a room.
     *
     * - to request a room key which is not related to a guest reservation but valid for a defined time - (for show rooms, repair) - One Shot Key.
     *
     * - to request to re-encode a key whereby other keys for this room remain active.
     *
     * - to request to read a key data from a room key and display it to the user in the PMS.
     *
     * - to request to modify existing key data - upon room move or change of departure date. (online key systems only!!)
     *
     * - to request to remove / delete a room key from a room on. Usually sent with check out of a reservation.
     *
     * Use this API to post a room key action to the active Door Lock System.
     *
     * <strong>Notes on keyType values:</strong>
     *
     * <strong>keyType = New
     *
     * keyType = Lost </strong>
     *
     * It is expected that all previous active keys for the room will become invalid.
     *
     * It is expected that partner system handles multiple keys being active in case numberOfKeys is >1.
     *
     * <strong>keyType = Duplicate
     *
     * keyType = ReEncode</strong>
     *
     * It is expected that existing active keys for this room remain active.
     *
     * <strong>keyType = OneShot</strong>
     *
     * It is expected that the room key is only valid for a room for specific time (for maintenance or Show room).
     *
     * It is never related to a reservation.
     *
     * <strong>keyType = Read</strong> A request to the Key Card system to read Key Card information from requested Key Encoder/reader.
     *
     * The Key Read functionality is of pure informational purpose. None of the received information is stored or processed in the PMS, and it is only for display to the user.
     *
     * <strong>keyType = Remove</strong>
     *
     * It is expected that with this request all active keys for a room or reservation will become inactive or invalid so they will not be able to open the room after defined validityEnd time.
     *
     * <strong>Additional KeyType actions used by Online Door Lock Systems:</strong>
     *
     * <strong>Online Key card Systems</strong> are systems which do not write guest data to the room key directly but do store guest data internally and send the information to the related door lock.
     *
     * <strong>keyType = ModifyStay</strong>
     *
     * For Online Door Lock Systems - Request to adjust Room key data when guest changes length of stay (validityEnd)
     *
     * <strong>keyType = RoomMove</strong>
     *
     * For Online Door Lock Systems - adjust Room key data when guest performs room move.
     *
     * <p><strong>OperationId:</strong> postRoomKeysOutbound</p>
     */
    post: operations["postRoomKeysOutbound"];
  };
}

export interface definitions {
  /**
   * Error Detail
   * @description Complex type that contains error details for a REST call.
   */
  exceptionDetailType: {
    /** @description Absolute URI [RFC3986] that identifies the problem type.  When dereferenced, it SHOULD provide a human-readable summary of the problem (for example, using HTML). */
    type?: string;
    /** @description Short, human-readable summary of the problem.  The summary SHOULD NOT change for subsequent occurrences of the problem, except for purposes of localization. */
    title?: string;
    /** @description HTTP status code for this occurrence of the problem, set by the origin server. */
    status?: number;
    /** @description Human-readable description specific to this occurrence of the problem. */
    detail?: string;
    /** @description Absolute URI that identifies the specific occurrence of the problem.  It may or may not provide additional information if dereferenced. */
    instance?: string;
    /** @description Application error code, which is different from HTTP error code. */
    "o:errorCode"?: string;
    /** @description Path to the problem at the resource or property level. */
    "o:errorPath"?: string;
    /** @description Details of the error message, consisting of a hierarchical tree structure. */
    "o:errorDetails"?: definitions["errorInstance"][];
    links?: definitions["links"];
  };
  /**
   * Error Instance Details
   * @description Complex type that contains error instance details for a REST call.
   */
  errorInstance: {
    /** @description Absolute URI [RFC3986] that identifies the problem type.  When dereferenced, it SHOULD provide a human-readable summary of the problem (for example, using HTML). */
    type?: string;
    /** @description Short, human-readable summary of the problem.  The summary SHOULD NOT change for subsequent occurrences of the problem, except for purposes of localization. */
    title?: string;
    /** @description HTTP status code for this occurrence of the problem, set by the origin server. */
    status?: number;
    /** @description Human-readable description specific to this occurrence of the problem. */
    detail?: string;
    /** @description Absolute URI that identifies the specific occurrence of the problem.  It may or may not provide additional information if dereferenced. */
    instance?: string;
    /** @description Application error code, which is different from HTTP error code. */
    "o:errorCode"?: string;
    /** @description Path to the problem at the resource or property level. */
    "o:errorPath"?: string;
  };
  /** @description Metadata describing link description objects that MAY appear in the JSON instance representation. */
  instanceLink: {
    /** @description URI [RFC3986] or URI Template [RFC6570]. If the value is set to URI Template, then the "templated" property must be set to true. */
    href?: string;
    /** @description Name of the link relation that, in addition to the type property, can be used to retrieve link details. For example, href or profile. */
    rel?: string;
    /**
     * @description Boolean flag that specifies that "href" property is a URI or URI Template. If the property is a URI template, set this value to true. By default, this value is false.
     * @default false
     */
    templated?: boolean;
    /**
     * @description HTTP method for requesting the target of the link.
     * @enum {string}
     */
    method?: "GET" | "POST" | "PUT" | "DELETE" | "PATCH" | "OPTIONS" | "HEAD";
    /** @description Link to the metadata of the resource, such as JSON-schema, that describes the resource expected when dereferencing the target resource.. */
    targetSchema?: string;
    /** @description The operationId of the path you can call to follow this link.  This allows you to look up not only the path and method, but the description of that path and any parameters you need to supply. */
    operationId?: string;
    /** @description Exact copy of the "summary" field on the linked operation. */
    title?: string;
  };
  links: definitions["instanceLink"][];
  /** @description Unique Id that references an object uniquely in the system. */
  uniqueIDListType: definitions["uniqueID_Type"][];
  /** @description An identifier used to uniquely reference an object in a system (e.g. an airline reservation reference, customer profile reference, booking confirmation number, or a reference to a previous availability quote). */
  uniqueID_Type: {
    /** @description A unique identifying value assigned by the creating system. The ID attribute may be used to reference a primary-key value within a database or in a particular implementation. */
    id?: string;
    /** @description A reference to the type of object defined by the UniqueID element. */
    type?: string;
  };
  keyTrackType: {
    /** @description specific data if configured */
    keyTrack1?: string;
    /** @description Track2 data string sent by PMS if defined or string (e.g. RFID ID) sent by DLS system in response */
    keyTrack2?: string;
    /** @description Includes the Key Pincode or a digital key string for use (in 201 response only) */
    keyTrack3?: string;
  };
  /**
   * @description Simple type for representing room key type.
   * @enum {string}
   */
  roomKeyOutBoundType:
    | "New"
    | "Duplicate"
    | "Lost"
    | "OneShot"
    | "RoomMove"
    | "ReEncode"
    | "Remove"
    | "ModifyStay"
    | "Read";
  /**
   * @description Simple type for representing request type.  Request specific data in response message. 'R1' = request for regular room Key; 'R2' = request for UDID or Track2 of room key; 'R3' = request for PinCode; 'R4' = request for mobile key (no physical key)
   * @enum {string}
   */
  requestType: "R1" | "R2" | "R3" | "R4";
  /**
   * @description Response Codes supported: OK - Successful; BY - Encoder Busy; UR - Unprocessable Request; RY - Retry
   * @enum {string}
   */
  roomKeyResponseCodeType: "OK" | "BY" | "UR" | "RY";
  /** @description This contains code and description information for key options. */
  keyOptionsType: {
    /** @description key options code. */
    keyOptionsCode?: string;
    /** @description key options description. */
    keyOptionDescription?: string;
  };
  /** @description This contains code and description information for key options. */
  keyOptionsResponseType: {
    /** @description key options code. */
    keyOptionsCode?: string;
    /** @description key options description. */
    keyOptionDescription?: string;
    /** @description Indicates that the keyOption is enabled for this key. */
    isEnabled?: boolean;
    /** @description Indicates that this keyOption is a default access. */
    default?: boolean;
  };
  /**
   * @description Simple type for representing room key request type. 'HardKey' = request for physical key card with RFID; 'MobileKey' = request for mobile key (no physical key); 'PinCode' = request for PinCode; 'KeyPayload' = request Key image from DLS System
   * @enum {string}
   */
  externalRoomKeyType: "HardKey" | "MobileKey" | "PinCode" | "KeyPayload";
  /**
   * @description Simple type for representing key user type. 'Guest' = request Opera Guest room key
   * @enum {string}
   */
  keyUserType: "Guest";
  /** @description Lists the text, file or picture to print onto a Guest room key (only for roomKeyType is HardKey). */
  printDataType: {
    /** @description key options code. */
    printText?: string;
    /**
     * Format: byte
     * @description Base64 format of file representing data to print.
     */
    printFile?: string;
    /**
     * Format: byte
     * @description Base64 format of picture representing data to print.
     */
    printPicture?: string;
  };
  /** @description Used in conjunction with the Success element to define a business error. */
  warningsType: definitions["warningType"][];
  /** @description Used when a message has been successfully processed to report any warnings or business errors that occurred. */
  warningType: {
    /** @description Property Value */
    value?: string;
    /** @description An abbreviated version of the error in textual format. */
    shortText?: string;
    /** @description If present, this refers to a table of coded values exchanged between applications to identify errors or warnings. */
    code?: string;
    /** @description If present, this URL refers to an online description of the error that occurred. */
    docURL?: string;
    /** @description If present, recommended values are those enumerated in the ErrorRS, (NotProcessed Incomplete Complete Unknown) however, the data type is designated as string data, recognizing that trading partners may identify additional status conditions not included in the enumeration. */
    status?: string;
    /** @description If present, this attribute may identify an unknown or misspelled tag that caused an error in processing. It is recommended that the Tag attribute use XPath notation to identify the location of a tag in the event that more than one tag of the same name is present in the document. Alternatively, the tag name alone can be used to identify missing data [Type=ReqFieldMissing]. */
    tag?: string;
    /** @description If present, this attribute allows for batch processing and the identification of the record that failed amongst a group of records. This value may contain a concatenation of a unique failed transaction ID with specific record(s) associated with that transaction. */
    recordId?: string;
    /** @description The Warning element MUST contain the Type attribute that uses a recommended set of values to indicate the warning type. The validating XSD can expect to accept values that it has NOT been explicitly coded for and process them by using Type ="Unknown". */
    type?: string;
    /** @description Language identification. */
    language?: string;
    /** @description Reference Place Holder used as an index for this warning. */
    rph?: string;
  };
  /** @description Request for generation of room key used for OutBound. */
  roomKeyExternal: {
    /** @description Unique Id as defined by Door Lock System. */
    encoderId: string;
    /** @description The Unique PMS encoder name linked with the encoderId */
    encoderTerminal: string;
    /** @description The PMS room number to generate a key for. */
    roomId?: string;
    /** @description Old Room Number is used when a room move (keyType RoomMove) is performed. */
    oldRoomId?: string;
    /**
     * @description Number of keys to be created.The value is always 1
     * @default 1
     */
    noOfKeys?: number;
    /** @description Collection of unique reservation identifiers for the reservation we are trying to make a room key for. */
    reservationIdList?: definitions["uniqueIDListType"];
    /** @description Indicates if Guest is a sharer or not */
    guestShareFlag?: boolean;
    /** @description Indicates if old Guest room is a sharer or not when a room move (keyType RoomMove) is performed. */
    OldGuestShareFlag?: boolean;
    /** @description Lists the access areas defined in PMS valid for the room key. */
    keyOptions?: string;
    /**
     * Format: date-time
     * @description The date/time the room key is valid from.
     */
    keyValidityStart?: string;
    /**
     * Format: date-time
     * @description The date/time the room key is valid to.
     */
    keyValidityEnd?: string;
    keyType: definitions["roomKeyOutBoundType"];
    /** @description KeyTrack Data. */
    keyTrack?: definitions["keyTrackType"];
    /** @description Collection of additional rooms to be included in key creation of reservation room. */
    additionalRooms?: string[];
    /** @description Collection of old additional rooms in key creation of reservation room when a room move (keyType RoomMove) is performed. */
    oldAdditionalRooms?: string[];
    /** @description Unique identifier for the PMS user. */
    userId?: string;
    requestType?: definitions["requestType"];
  };
  /** @description Request for generation of room key used for OutBound. */
  roomKeysOutbound: {
    /** @description Unique Id as defined by Door Lock System. */
    encoderId: string;
    /** @description The Unique PMS encoder name linked with the encoderId */
    encoderTerminal: string;
    /** @description The PMS room number to generate a key for. */
    roomId?: string;
    /** @description Old Room Number is used when a room move (keyType RoomMove) is performed. */
    oldRoomId?: string;
    /** @description Number of keys to be created. */
    noOfKeys?: number;
    /** @description Collection of unique reservation identifiers for the reservation we are trying to make a room key for. */
    reservationIdList?: definitions["uniqueIDListType"];
    /** @description Indicates if Guest is a sharer or not */
    guestShareFlag?: boolean;
    /** @description Indicates if old Guest room is a sharer or not when a room move (keyType RoomMove) is performed. */
    OldGuestShareFlag?: boolean;
    /**
     * Format: date-time
     * @description The date/time the room key is valid from.
     */
    keyValidityStart?: string;
    /**
     * Format: date-time
     * @description The date/time the room key is valid to.
     */
    keyValidityEnd?: string;
    keyType: definitions["roomKeyOutBoundType"];
    /** @description KeyTrack Data. */
    keyTrack?: definitions["keyTrackType"];
    /** @description Collection of additional rooms to be included in key creation of reservation room. */
    additionalRooms?: string[];
    /** @description Collection of old additional rooms in key creation of reservation room when a room move (keyType RoomMove) is performed. */
    oldAdditionalRooms?: string[];
    /** @description Unique identifier for the PMS user. */
    userId?: string;
    /** @description Lists the access areas defined in PMS valid for the room key. */
    keyOptions?: definitions["keyOptionsType"][];
    /**
     * Format: date-time
     * @description The date/time the room key is requested.
     */
    keyRequestTime: string;
    roomKeyType: definitions["externalRoomKeyType"];
    keyUserType: definitions["keyUserType"];
    /** @description Unique identifier of RFID card used for KeyPayload generation. Required when roomKeyType is KeyPayload. */
    cardSerialNumber?: string;
    /** @description Lists the text, file or picture to print onto a Guest room key (only for roomKeyType is HardKey). */
    printData?: definitions["printDataType"];
  };
  /** @description Response for the key request made to DLS from OPERA Cloud. */
  roomKeyExternalDetails: {
    /** @description Unique Id as defined by Door Lock System. */
    encoderId?: string;
    /** @description The Unique PMS encoder name linked with the encoderId */
    encoderTerminal: string;
    /** @description Collection of unique reservation identifiers for the reservation we are trying to make a room key for. */
    reservationIdList?: definitions["uniqueIDListType"];
    /** @description The PMS room number to generate a key for. */
    roomId: string;
    /** @description KeyTrack Data. */
    keyTrack?: definitions["keyTrackType"][];
    /** @description Lists all PMS access areas - only send in response for keyType: 'Read' request */
    keyOptions?: string;
    /**
     * Format: date-time
     * @description Date/Time Key is valid from - only send in response for keyType: 'Read' request
     */
    keyValidityStart?: string;
    /**
     * Format: date-time
     * @description Date/Time Key is valid to - only send in response for keyType: 'Read' request
     */
    keyValidityEnd?: string;
    /** @description A user-friendly text with information on why a request is not successful */
    responseText?: string;
    responseCode: definitions["roomKeyResponseCodeType"];
    /** @description Collection of additional rooms to be included in key creation of reservation room. */
    additionalRooms?: string[];
  };
  /** @description Response for the key request made to DLS from OPERA Cloud. */
  roomKeysOutboundDetails: {
    /** @description Unique Id as defined by Door Lock System. */
    encoderId?: string;
    /** @description The Unique PMS encoder name linked with the encoderId */
    encoderTerminal: string;
    /** @description Collection of unique reservation identifiers for the reservation we are trying to make a room key for. */
    reservationIdList?: definitions["uniqueIDListType"];
    /** @description The PMS room number to generate a key for. */
    roomId: string;
    /** @description KeyTrack Data. */
    keyTrack?: definitions["keyTrackType"][];
    /**
     * Format: date-time
     * @description Date/Time Key is valid from - only send in response for keyType: 'Read' request
     */
    keyValidityStart: string;
    /**
     * Format: date-time
     * @description Date/Time Key is valid to - only send in response for keyType: 'Read' request
     */
    keyValidityEnd: string;
    /** @description Number of keys to be created.The value is always 1 */
    noOfKeys?: number;
    /** @description A user-friendly text with information on why a request is not successful */
    responseText?: string;
    responseCode: definitions["roomKeyResponseCodeType"];
    /** @description Collection of additional rooms to be included in key creation of reservation room. */
    additionalRooms?: string[];
    /** @description Lists all PMS access areas. */
    keyOptions?: definitions["keyOptionsResponseType"][];
    /** @description Unique identifier for the PMS user. */
    userId?: string;
    /**
     * Format: byte
     * @description Base64 format of Mobile Key data provided by DLS System which the external system requested - only send in response for roomKeyType: 'MobileKey'
     */
    digitalKeyData?: string;
    /**
     * Format: byte
     * @description Image of the created key - only send in response for roomKeyType: 'KeyPayload'
     */
    keyImage?: string;
    /** @description Unique identifier of RFID card used for KeyPayload generation - only send in response for roomKeyType: 'KeyPayload'. */
    cardSerialNumber?: string;
    /**
     * Format: date-time
     * @description Date/Time the key has been generated by Door Locking system.
     */
    keyCreationTime: string;
    roomKeyType: definitions["externalRoomKeyType"];
    keyUserType: definitions["keyUserType"];
  };
}

export interface parameters {
  /** @description Pass this header as true, if payload needs DVM */
  externalData: string;
  /** @description Bearer token that needs to be passed which is generated post user authentication */
  authKey: string;
  /** @description Client or Partner's Application Key */
  "x-app-key": string;
  /** @description Request Id of an incoming request */
  "x-request-id": string;
  /** @description Customer's Integration Application Id */
  "x-originating-application": string;
}

export interface responses {
  /** Bad Request */
  400: {
    schema: definitions["exceptionDetailType"];
  };
  /** Unauthorized */
  401: unknown;
  /** Forbidden */
  403: unknown;
  /** Resource not found */
  404: {
    schema: definitions["exceptionDetailType"];
  };
  /** Method not allowed */
  405: unknown;
  /** Not acceptable. */
  406: unknown;
  /** Request Entity Too Large */
  413: unknown;
  /** Request URI Too Large */
  414: unknown;
  /** Unsupported Media Type */
  415: unknown;
  /** System Error */
  500: {
    schema: definitions["exceptionDetailType"];
  };
  /** Bad Gateway */
  502: unknown;
  /** Service Unavailable */
  503: unknown;
}

export interface operations {
  /**
   * API that manages requests for Door Lock Room Keys. This operation is used by OPERA Cloud connected to external Door Lock Systems systems via Outbound Systems configuration:
   *
   * <strong>OPERA Cloud utilizes this operation </strong>
   *
   * - to request new or additional room keys - e.g. when guest checks in, or additional keys post check in.
   *
   * - to request to activate new keys after check on e.g. when a room key has been lost for a room.
   *
   * - to request a room key which is not related to a guest reservation but valid for a defined time - (for show rooms, repair) - One Shot Key.
   *
   * - to request to re-encode a key whereby other keys for this room remain active.
   *
   * - to request to read a key data from a room key and display it to the user in the PMS.
   *
   * - to request to modify existing key data - upon room move or change of departure date. (online key systems only!!)
   *
   * - to request to remove / delete a room key from a room on. Usually sent with check out of a reservation.
   *
   * Use this API to post a room key action to the active Door Lock System.
   *
   * <strong>Notes on keyType values:</strong>
   *
   * <strong>keyType = New
   *
   * keyType = Lost </strong>
   *
   * It is expected that all previous active keys for the room will become invalid.
   *
   * It is expected that partner system handles multiple keys being active in case numberOfKeys is >1.
   *
   * <strong>keyType = Duplicate
   *
   * keyType = ReEncode</strong>
   *
   * It is expected that existing active keys for this room remain active.
   *
   * <strong>keyType = OneShot</strong>
   *
   * It is expected that the room key is only valid for a room for specific time (for maintenance or Show room).
   *
   * It is never related to a reservation.
   *
   * <strong>keyType = Read</strong> A request to the Key Card system to read Key Card information from requested Key Encoder/reader.
   *
   * The Key Read functionality is of pure informational purpose. None of the received information is stored or processed in the PMS, and it is only for display to the user.
   *
   * <strong>keyType = Remove</strong>
   *
   * It is expected that with this request all active keys for a room or reservation will become inactive or invalid so they will not be able to open the room after defined validityEnd time.
   *
   * <strong>Additional KeyType actions used by Online Door Lock Systems:</strong>
   *
   * <strong>Online Key card Systems</strong> are systems which do not write guest data to the room key directly but do store guest data internally and send the information to the related door lock.
   *
   * <strong>keyType = ModifyStay</strong>
   *
   * For Online Door Lock Systems - Request to adjust Room key data when guest changes length of stay (validityEnd)
   *
   * <strong>keyType = RoomMove</strong>
   *
   * For Online Door Lock Systems - adjust Room key data when guest performs room move.
   *
   * <p><strong>OperationId:</strong> postExternalRoomKeys</p>
   */
  postExternalRoomKeys: {
    parameters: {
      path: {
        /** Unique ID of the hotel */
        hotelId: string;
      };
      body: {
        /** Request for generation of room key. */
        roomKey: definitions["roomKeyExternal"];
      };
      header: {
        /** Bearer token that needs to be passed which is generated post user authentication */
        authorization?: parameters["authKey"];
        /** Pass this header as true, if payload needs DVM */
        externalData?: parameters["externalData"];
        /** Client or Partner's Application Key */
        "x-app-key": parameters["x-app-key"];
        /** Request Id of an incoming request */
        "x-request-id"?: parameters["x-request-id"];
        /** Customer's Integration Application Id */
        "x-originating-application"?: parameters["x-originating-application"];
      };
    };
    responses: {
      /**
       * Response from the active Door Locking System Property Interface to the post request.<p><strong>Note on Response messages:</strong>
       *
       * It is necessary to specify both the PMS 'encoderTerminal' and the Key Service system's coder (encoderId) in cases where more than one PMS workstation may be addressing one key coder. ORACLE PMS will NOT send another Request command automatically should a negative response be received. The user sees the response and decides if another try should be made.<p>
       */
      201: {
        headers: {};
        schema: definitions["roomKeyExternalDetails"];
      };
      400: responses["400"];
      401: responses["401"];
      403: responses["403"];
      404: responses["404"];
      405: responses["405"];
      406: responses["406"];
      413: responses["413"];
      414: responses["414"];
      415: responses["415"];
      500: responses["500"];
      502: responses["502"];
      503: responses["503"];
    };
  };
  /**
   * API that manages requests for Door Lock Room Keys. This operation is used by OPERA Cloud connected to external Door Lock Systems systems via Outbound Systems configuration:
   *
   * <strong>OPERA Cloud utilizes this operation </strong>
   *
   * - to request new or additional room keys - e.g. when guest checks in, or additional keys post check in.
   *
   * - to request to activate new keys after check on e.g. when a room key has been lost for a room.
   *
   * - to request a room key which is not related to a guest reservation but valid for a defined time - (for show rooms, repair) - One Shot Key.
   *
   * - to request to re-encode a key whereby other keys for this room remain active.
   *
   * - to request to read a key data from a room key and display it to the user in the PMS.
   *
   * - to request to modify existing key data - upon room move or change of departure date. (online key systems only!!)
   *
   * - to request to remove / delete a room key from a room on. Usually sent with check out of a reservation.
   *
   * Use this API to post a room key action to the active Door Lock System.
   *
   * <strong>Notes on keyType values:</strong>
   *
   * <strong>keyType = New
   *
   * keyType = Lost </strong>
   *
   * It is expected that all previous active keys for the room will become invalid.
   *
   * It is expected that partner system handles multiple keys being active in case numberOfKeys is >1.
   *
   * <strong>keyType = Duplicate
   *
   * keyType = ReEncode</strong>
   *
   * It is expected that existing active keys for this room remain active.
   *
   * <strong>keyType = OneShot</strong>
   *
   * It is expected that the room key is only valid for a room for specific time (for maintenance or Show room).
   *
   * It is never related to a reservation.
   *
   * <strong>keyType = Read</strong> A request to the Key Card system to read Key Card information from requested Key Encoder/reader.
   *
   * The Key Read functionality is of pure informational purpose. None of the received information is stored or processed in the PMS, and it is only for display to the user.
   *
   * <strong>keyType = Remove</strong>
   *
   * It is expected that with this request all active keys for a room or reservation will become inactive or invalid so they will not be able to open the room after defined validityEnd time.
   *
   * <strong>Additional KeyType actions used by Online Door Lock Systems:</strong>
   *
   * <strong>Online Key card Systems</strong> are systems which do not write guest data to the room key directly but do store guest data internally and send the information to the related door lock.
   *
   * <strong>keyType = ModifyStay</strong>
   *
   * For Online Door Lock Systems - Request to adjust Room key data when guest changes length of stay (validityEnd)
   *
   * <strong>keyType = RoomMove</strong>
   *
   * For Online Door Lock Systems - adjust Room key data when guest performs room move.
   *
   * <p><strong>OperationId:</strong> postRoomKeysOutbound</p>
   */
  postRoomKeysOutbound: {
    parameters: {
      path: {
        /** Unique ID of the hotel */
        hotelId: string;
      };
      body: {
        /** Request for generation of room key. */
        roomKey: definitions["roomKeysOutbound"];
      };
      header: {
        /** Bearer token that needs to be passed which is generated post user authentication */
        authorization?: parameters["authKey"];
        /** Pass this header as true, if payload needs DVM */
        externalData?: parameters["externalData"];
        /** Client or Partner's Application Key */
        "x-app-key": parameters["x-app-key"];
        /** Request Id of an incoming request */
        "x-request-id"?: parameters["x-request-id"];
        /** Customer's Integration Application Id */
        "x-originating-application"?: parameters["x-originating-application"];
      };
    };
    responses: {
      /**
       * Response from the active Door Locking System Property Interface to the post request.<p><strong>Note on Response messages:</strong>
       *
       * It is necessary to specify both the PMS 'encoderTerminal' and the Key Service system's coder (encoderId) in cases where more than one PMS workstation may be addressing one key coder. ORACLE PMS will NOT send another Request command automatically should a negative response be received. The user sees the response and decides if another try should be made.<p>
       */
      201: {
        headers: {};
        schema: definitions["roomKeysOutboundDetails"];
      };
      400: responses["400"];
      401: responses["401"];
      403: responses["403"];
      404: responses["404"];
      405: responses["405"];
      406: responses["406"];
      413: responses["413"];
      414: responses["414"];
      415: responses["415"];
      500: responses["500"];
      502: responses["502"];
      503: responses["503"];
    };
  };
}

export interface external {}
