/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/content": {
    /** This message will provide channel property content  <p><strong>OperationId:</strong>postContent</p> */
    post: operations["postContent"];
  };
}

export interface definitions {
  /**
   * @description The unique identifier element allows the trading partners to uniquely identify each request of the same message, (i.e.  the entire message) for transaction traceability
   * @example 234512-3432-234234234
   */
  UniqueId: string;
  /**
   * Format: DATE_TIME
   * @description Indicates the creation date and time of the message in UTC using the following format specified by ISO 8601; YYYY-MM-DDThh:mm:ss.zzzZ with time values using the 24 hour clock (e.g. 20 November 2003, 1:59:38 pm UTC becomes 2003-11-20T13:59:38.000Z).
   * @example 2021-11-20T13:59:38.000Z
   */
  Timestamp: string;
  ExceptionObj: {
    /** @example 884366976 */
    logId: number;
    /** @description Short, human-readable summary of the problem.  The summary SHOULD NOT change for subsequent occurrences of the problem, except for purposes of localization. */
    title: string;
    /**
     * @description HTTP status code for this occurrence of the problem, set by the origin server.
     * @example 400
     */
    status: number;
    /**
     * @description HDP error code, which is different from HTTP error code.
     * @example DARI00001
     */
    "o.errorCode"?: string;
    /**
     * @description Absolute URI [RFC3986] that identifies the problem type.  When dereferenced, it SHOULD provide a human-readable summary of the problem.
     * @example http://www.w3.org/Protocols/rfc2616/rfc2616-sec10.html#sec10.x
     */
    type?: string;
    /**
     * Format: date-time
     * @example 2021-09-17T08:17:18.321Z
     */
    timestamp?: string;
  };
  ExceptionDetail: definitions["ExceptionObj"] & {
    "o.errorDetails"?: definitions["ExceptionObj"][];
  };
  /** @description The object provides the channel content detail. */
  ChannelContent: {
    /** @example ChannelContent */
    moduleName?: string;
    /**
     * @description The action type for the event
     * @example UPDATE CHANNEL ROOM TYPE
     */
    actionType?: string;
    uniqueId?: definitions["UniqueId"];
    timeStamp?: definitions["Timestamp"];
    /**
     * @description The Enterprise ID of the property it belongs to
     * @example ENTERPRISEID
     */
    enterpriseId?: string;
    /**
     * @description A unique identifier value for the property/hotel associated with channel
     * @example HOTELCODE
     */
    hotelCode?: string;
    /**
     * @description Code for the channel which is receiving published data.
     * @example CHANNELCODE
     */
    channelCode?: string;
    transactionKey?: definitions["TransactionKeyDetail"][];
  };
  TransactionKeyDetail: {
    /** @example roomType */
    name?: string;
    /** @example ROOMTYPECODE */
    value?: string;
  };
}

export interface responses {
  /** Request data provided is invalid */
  400: {
    schema: definitions["ExceptionDetail"];
  };
  /** Unauthorized */
  401: {
    schema: definitions["ExceptionDetail"];
  };
  /** Forbidden */
  403: {
    schema: definitions["ExceptionDetail"];
  };
  /** Not Found */
  404: {
    schema: definitions["ExceptionDetail"];
  };
  /** Not Allowed */
  405: {
    schema: definitions["ExceptionDetail"];
  };
  /** Not Acceptable */
  406: {
    schema: definitions["ExceptionDetail"];
  };
  /** Payload Too Large */
  413: {
    schema: definitions["ExceptionDetail"];
  };
  /** URI Too Long */
  414: {
    schema: definitions["ExceptionDetail"];
  };
  /** Unsupported Media Type */
  415: {
    schema: definitions["ExceptionDetail"];
  };
  /** Internal Server Error */
  500: {
    schema: definitions["ExceptionDetail"];
  };
  /** Bad Gateway */
  502: {
    schema: definitions["ExceptionDetail"];
  };
  /** Service Unavailable */
  503: {
    schema: definitions["ExceptionDetail"];
  };
}

export interface operations {
  /** This message will provide channel property content  <p><strong>OperationId:</strong>postContent</p> */
  postContent: {
    parameters: {
      header: {
        /** Bearer token that needs to be passed which is generated post user authentication */
        Authorization: string;
      };
      body: {
        body: definitions["ChannelContent"];
      };
    };
    responses: {
      /** Response for publishing content */
      201: unknown;
      /** Request data provided is invalid */
      400: {
        schema: definitions["ExceptionDetail"];
      };
      /** Unauthorized */
      401: {
        schema: definitions["ExceptionDetail"];
      };
      /** Forbidden */
      403: {
        schema: definitions["ExceptionDetail"];
      };
      /** Not Found */
      404: {
        schema: definitions["ExceptionDetail"];
      };
      /** Not Allowed */
      405: {
        schema: definitions["ExceptionDetail"];
      };
      /** Not Acceptable */
      406: {
        schema: definitions["ExceptionDetail"];
      };
      /** Payload Too Large */
      413: {
        schema: definitions["ExceptionDetail"];
      };
      /** URI Too Long */
      414: {
        schema: definitions["ExceptionDetail"];
      };
      /** Unsupported Media Type */
      415: {
        schema: definitions["ExceptionDetail"];
      };
      /** Internal Server Error */
      500: {
        schema: definitions["ExceptionDetail"];
      };
      /** Bad Gateway */
      502: {
        schema: definitions["ExceptionDetail"];
      };
      /** Service Unavailable */
      503: {
        schema: definitions["ExceptionDetail"];
      };
    };
  };
}

export interface external {}
