/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/externalSystems/{extSystemCode}/hotels/{hotelId}/blocks/allocationSummary": {
    /** This API will fetch Block allocation information for a hotel, and specified date range. The block allocated inventory, rates and room type statistics are returned as part of the response. The maximum limit of date range (whether using start/endDate or startLastModifiedDate/endLastModifiedDate) is 94 days, but the recommendation is to use a date range proportionate to the size of the hotel.   Every identical request (employing the same query parameters) for the getBlockAllocationSummary operation when requesting data with start/endDate or startLastModifiedDate/endLastModifiedDate, necessitates a mandatory 30-minute interval between submissions. Please note that this limit applies regardless of whether the POST, HEAD, and GET cycle has been completed. The API returns a header parameter location that can be used in the getBlockAllocationSummaryProcessStatus operation.  Use event-driven APIs -(see https://docs.oracle.com/cd/F29336_01/doc.201/f27480/c_business_events.htm#OHIPU-BusinessEvents-F0AC1F1C) -to get real-time block updates. <p><strong>OperationId:</strong>startBlockAllocationSummaryProcess</p> */
    post: operations["startBlockAllocationSummaryProcess"];
  };
  "/externalSystems/{extSystemCode}/hotels/{hotelId}/blocks/allocationSummary/{requestId}": {
    /** This API will fetch Block allocation information for a hotel, and specified date range.  The block allocated inventory, rates and room type statistics are returned as part of the response. <p><strong>OperationId:</strong>getBlockAllocationSummary</p> */
    get: operations["getBlockAllocationSummary"];
    /** <p><strong>OperationId:</strong>getBlockAllocationSummaryProcessStatus</p> */
    head: operations["getBlockAllocationSummaryProcessStatus"];
  };
  "/hotels/{hotelId}/blocks/{blockId}/allocation": {
    /** Use this API to add block room type allocations and rates to a specified Block. <p><strong>OperationId:</strong>startBlockAllocationProcess</p> */
    post: operations["startBlockAllocationProcess"];
  };
  "/hotels/{hotelId}/blocks/{blockId}/allocation/{requestId}": {
    /** This API will fetch Block allocation warnings for a hotel to allow for overbooking information to be returned as part of the response. <p><strong>OperationId:</strong>getBlockAllocationProcessInfo</p> */
    get: operations["getBlockAllocationProcessInfo"];
    /** <p><strong>OperationId:</strong>getBlockAllocationProcessStatus</p> */
    head: operations["getBlockAllocationProcessStatus"];
  };
  "/hotels/{hotelId}/blocks/{blockId}/allocationRanges": {
    /** Use this API to set business block allocation for one or more date ranges, which are within business block date range, and for a list of room types. <p><strong>OperationId:</strong>startAllocationRangesProcess</p> */
    post: operations["startAllocationRangesProcess"];
  };
  "/hotels/{hotelId}/blocks/{blockId}/allocationRanges/{requestId}": {
    /** This API will fetch Block allocation ranges warnings for a hotel to allow for overbooking information to be returned as part of the response. <p><strong>OperationId:</strong>getAllocationRangesProcessInfo</p> */
    get: operations["getAllocationRangesProcessInfo"];
    /** <p><strong>OperationId:</strong>getAllocationRangesProcessStatus</p> */
    head: operations["getAllocationRangesProcessStatus"];
  };
  "/hotels/{hotelId}/blocks/{blockId}/shift": {
    /** Use this API to move or shift the dates of a block in OPERA. <p><strong>OperationId:</strong>startShiftBlockProcess</p> */
    post: operations["startShiftBlockProcess"];
  };
  "/hotels/{hotelId}/blocks/{blockId}/shift/{requestId}": {
    /** This API will fetch shift Block warnings and errors to be returned as part of the response. <p><strong>OperationId:</strong>getShiftBlockProcessInfo</p> */
    get: operations["getShiftBlockProcessInfo"];
    /** <p><strong>OperationId:</strong>getShiftBlockProcessStatus</p> */
    head: operations["getShiftBlockProcessStatus"];
  };
  "/hotels/{hotelId}/blocks/{blockId}/recalculateRoomForecast": {
    /** Use this API to recalculate room forecast rates */
    post: operations["startRecalculateRoomForecastProcess"];
  };
  "/hotels/{hotelId}/blocks/{blockId}/recalculateRoomForecast/{requestId}": {
    /** This API will fetch recalculate room forecast warnings and errors to be returned as part of the response.<p><strong>OperationId:</strong>getRecalculateRoomForecastProcessInfo</p> */
    get: operations["getRecalculateRoomForecastProcessInfo"];
    /** <p><strong>OperationId:</strong>getRecalculateRoomForecastProcessStatus</p> */
    head: operations["getRecalculateRoomForecastProcessStatus"];
  };
  "/hotels/{hotelId}/blocks/{blockId}/refreshProjectedRevenues": {
    /** Use this API to refresh Business Block projected revenues */
    post: operations["startRefreshProjectedRevenuesProcess"];
  };
  "/hotels/{hotelId}/blocks/{blockId}/refreshProjectedRevenues/{requestId}": {
    /** To include as part of response, this API will fetch warnings and/or errors (if any) from Business Block projected revenues refresh process.<p><strong>OperationId:</strong>getRefreshProjectedRevenuesProcessInfo</p> */
    get: operations["getRefreshProjectedRevenuesProcessInfo"];
    /** <p><strong>OperationId:</strong>getRefreshProjectedRevenuesProcessStatus</p> */
    head: operations["getRefreshProjectedRevenuesProcessStatus"];
  };
}

export interface definitions {
  /**
   * Error Detail
   * @description Complex type that contains error details for a REST call.
   */
  exceptionDetailType: {
    /** @description Absolute URI [RFC3986] that identifies the problem type.  When dereferenced, it SHOULD provide a human-readable summary of the problem (for example, using HTML). */
    type?: string;
    /** @description Short, human-readable summary of the problem.  The summary SHOULD NOT change for subsequent occurrences of the problem, except for purposes of localization. */
    title?: string;
    /** @description HTTP status code for this occurrence of the problem, set by the origin server. */
    status?: number;
    /** @description Human-readable description specific to this occurrence of the problem. */
    detail?: string;
    /** @description Absolute URI that identifies the specific occurrence of the problem.  It may or may not provide additional information if dereferenced. */
    instance?: string;
    /** @description Application error code, which is different from HTTP error code. */
    "o:errorCode"?: string;
    /** @description Path to the problem at the resource or property level. */
    "o:errorPath"?: string;
    /** @description Details of the error message, consisting of a hierarchical tree structure. */
    "o:errorDetails"?: definitions["errorInstance"][];
    links?: definitions["links"];
  };
  /**
   * Error Instance Details
   * @description Complex type that contains error instance details for a REST call.
   */
  errorInstance: {
    /** @description Absolute URI [RFC3986] that identifies the problem type.  When dereferenced, it SHOULD provide a human-readable summary of the problem (for example, using HTML). */
    type?: string;
    /** @description Short, human-readable summary of the problem.  The summary SHOULD NOT change for subsequent occurrences of the problem, except for purposes of localization. */
    title?: string;
    /** @description HTTP status code for this occurrence of the problem, set by the origin server. */
    status?: number;
    /** @description Human-readable description specific to this occurrence of the problem. */
    detail?: string;
    /** @description Absolute URI that identifies the specific occurrence of the problem.  It may or may not provide additional information if dereferenced. */
    instance?: string;
    /** @description Application error code, which is different from HTTP error code. */
    "o:errorCode"?: string;
    /** @description Path to the problem at the resource or property level. */
    "o:errorPath"?: string;
  };
  /** @description Metadata describing link description objects that MAY appear in the JSON instance representation. */
  instanceLink: {
    /** @description URI [RFC3986] or URI Template [RFC6570]. If the value is set to URI Template, then the "templated" property must be set to true. */
    href?: string;
    /** @description Name of the link relation that, in addition to the type property, can be used to retrieve link details. For example, href or profile. */
    rel?: string;
    /**
     * @description Boolean flag that specifies that "href" property is a URI or URI Template. If the property is a URI template, set this value to true. By default, this value is false.
     * @default false
     */
    templated?: boolean;
    /**
     * @description HTTP method for requesting the target of the link.
     * @enum {string}
     */
    method?: "GET" | "POST" | "PUT" | "DELETE" | "PATCH" | "OPTIONS" | "HEAD";
    /** @description Link to the metadata of the resource, such as JSON-schema, that describes the resource expected when dereferencing the target resource.. */
    targetSchema?: string;
    /** @description The operationId of the path you can call to follow this link.  This allows you to look up not only the path and method, but the description of that path and any parameters you need to supply. */
    operationId?: string;
    /** @description Exact copy of the "summary" field on the linked operation. */
    title?: string;
  };
  links: definitions["instanceLink"][];
  /** @description Used when a message has been successfully processed to report any warnings or business errors that occurred. */
  warningType: {
    /** @description Property Value */
    value?: string;
    /** @description An abbreviated version of the error in textual format. */
    shortText?: string;
    /** @description If present, this refers to a table of coded values exchanged between applications to identify errors or warnings. */
    code?: string;
    /** @description If present, this URL refers to an online description of the error that occurred. */
    docURL?: string;
    /** @description If present, recommended values are those enumerated in the ErrorRS, (NotProcessed Incomplete Complete Unknown) however, the data type is designated as string data, recognizing that trading partners may identify additional status conditions not included in the enumeration. */
    status?: string;
    /** @description If present, this attribute may identify an unknown or misspelled tag that caused an error in processing. It is recommended that the Tag attribute use XPath notation to identify the location of a tag in the event that more than one tag of the same name is present in the document. Alternatively, the tag name alone can be used to identify missing data [Type=ReqFieldMissing]. */
    tag?: string;
    /** @description If present, this attribute allows for batch processing and the identification of the record that failed amongst a group of records. This value may contain a concatenation of a unique failed transaction ID with specific record(s) associated with that transaction. */
    recordId?: string;
    /** @description The Warning element MUST contain the Type attribute that uses a recommended set of values to indicate the warning type. The validating XSD can expect to accept values that it has NOT been explicitly coded for and process them by using Type ="Unknown". */
    type?: string;
    /** @description Language identification. */
    language?: string;
    /** @description Reference Place Holder used as an index for this warning. */
    rph?: string;
  };
  /** @description Used in conjunction with the Success element to define a business error. */
  warningsType: definitions["warningType"][];
  blockAllocationSummaryType: {
    /** @description Hotel code for the block */
    hotelId?: string;
    /** @description A unique identifying value assigned by the creating system. The ID attribute may be used to reference a primary-key value within a database or in a particular implementation. */
    blockId?: number;
    /** @description Defined block code for the block. */
    blockCode?: string;
    /** @description Name of the block. */
    blockName?: string;
    /** @description A unique identifying value assigned by the creating system. The ID attribute may be used to reference a primary-key value within a database or in a particular implementation. */
    masterBlockId?: number;
    /** @description Booking Status of the block. */
    status?: string;
    /** @description Market Code of the block. */
    marketCode?: string;
    /** Format: date-time */
    startDate?: string;
    /** Format: date-time */
    endDate?: string;
    /** Format: date-time */
    cutOffDate?: string;
    cutOffDays?: number;
    /**
     * Format: date-time
     * @description Cancellation Date.
     */
    cancellationDate?: string;
    /** @description Code that idenfies the reason for cancellation. */
    cancellationCode?: string;
    /** @description Description that explains the reason for cancellation. */
    cancellationDescription?: string;
    /** @description Catering Owner */
    cateringOwner?: number;
    /** @description Primary Catering Owner Code */
    cateringOwnerCode?: string;
    /** @description Property of Catering Owner */
    cateringOwnerResort?: string;
    /** @description Owner ID */
    owner?: number;
    /** @description Block Owner Code */
    ownerCode?: string;
    /** @description Property of Business Block Owner */
    ownerResort?: string;
    /** @description Rooms Owner */
    roomsOwner?: number;
    /** @description Primary Rooms Owner Code */
    roomsOwnerCode?: string;
    /** @description Property of Rooms Owner */
    roomsOwnerResort?: string;
    /**
     * Format: date-time
     * @description The business date the block was created.
     */
    createDateTime?: string;
    /** @description Indicates the internal type of the block like G, etc. */
    blockType?: string;
    /** @description Booking Method. */
    reservationMethod?: string;
    /** @description Rate code associated with Block. */
    ratePlanCode?: string;
    /**
     * Format: date-time
     * @description Date Time when the block was modified last.
     */
    lastModifiedDate?: string;
    /** @description Source of the Block. */
    sourceCode?: string;
    allocationDates?: definitions["roomAllocationDateType"][];
    /** @description Booking Medium/Origin Code of the Block. */
    bookingMedium?: string;
    /** @description A collection of all the Primary Profiles associated to a this block. */
    blockProfiles?: {
      /** @description The list of primary profiles associated with the block. */
      blockProfile?: definitions["blockProfilesType"][];
    };
  };
  /** @description A collection of Profile objects or Unique IDs of Profiles. */
  blockProfilesType: {
    /** @description Unique identifiers for the Profile for both internal and external systems. */
    profileIdList?: definitions["uniqueIDListType"];
    /** @description Provides detailed information regarding either a company or a customer profile. */
    profile?: definitions["profileType"];
    /** @description Determines the type of the block profile. */
    blockProfileType?: definitions["blockProfileTypeType"];
  };
  /** @description Unique Id that references an object uniquely in the system. */
  uniqueIDListType: definitions["uniqueID_Type"][];
  /** @description An identifier used to uniquely reference an object in a system. */
  uniqueID_Type: {
    /** @description A unique identifying value assigned by the creating system. */
    id?: string;
    /** @description A reference to the type of object defined by the UniqueID element. */
    type?: string;
  };
  /** @description Type provides the detailed information about the profile and its children. */
  profileType: {
    /** @description Detailed customer information for this profile. */
    customer?: definitions["customerType"];
    /** @description Detailed company information for this profile. */
    company?: definitions["companyType"];
    /** @description Type of profile such as Guest, Agent, Company, Group, Source, Employee, Hotel, Vendor or Contact. */
    profileType?: definitions["profileTypeType"];
  };
  /** @description Contains basic data on the customer's identity. */
  customerType: {
    /** @description Detailed name information for thecustomer. */
    personName?: definitions["personNameType"][];
  };
  /**
   * @description The types of Profile handled by the web service.
   * @enum {string}
   */
  profileTypeType:
    | "Guest"
    | "Agent"
    | "Company"
    | "Group"
    | "Source"
    | "Employee"
    | "Hotel"
    | "Vendor"
    | "Contact"
    | "Purge"
    | "BusinessHeader"
    | "BillingAccount"
    | "Activity"
    | "Potential"
    | "Account";
  /** @description This provides name information for a person. */
  personNameType: {
    /** @description Given name, first name or names. */
    givenName?: string;
    /** @description Family name, last name. */
    surname?: string;
  };
  companyType: {
    /** @description Name of the company. */
    companyName?: string;
  };
  /**
   * @description Simple type for block profile types.
   * @enum {string}
   */
  blockProfileTypeType:
    | "Company"
    | "Group"
    | "Agent"
    | "Source"
    | "CompanyContact"
    | "AgentContact"
    | "SourceContact";
  roomAllocationDateType: {
    /**
     * Format: date-time
     * @description The block date for which the allocation details are listed.
     */
    allocationDate?: string;
    allocations?: definitions["roomAllocationDetailsType"][];
  };
  roomAllocationDetailsType: {
    /** @description The total original( forecasted ) rooms for the block. */
    originalRooms?: number;
    /** @description The room type for which the allocation details are listed. */
    roomType?: string;
    /** @description The total current( projected + pickup ) rooms for the block. */
    currentRooms?: number;
    /** @description The total pickup rooms for the block. */
    pickupRooms?: number;
    /** @description The break up of projected rooms by occupancy. */
    inventory?: definitions["blockGridInvType"];
    /** @description The break up of occupancy rates. */
    rates?: definitions["blockGridRatesType"];
    /** @description Net occupancy rates. */
    netRates?: definitions["blockGridRatesType"];
    /** @description The break up of actual revenue for room type. Applicable for past dates, business date or future dates. */
    actualRevenue?: definitions["blockActualRevenueType"];
    /** @description The break up of potential revenue for room type. Applicable for business date or future dates. */
    potentialRevenue?: definitions["blockPotenitalRevenueType"];
  };
  /** @description Indicates the inventory values ( occupancy or availability ) per person occupancy. */
  blockGridInvType: {
    /** @description Indicates the one person inventory value ( occupancy or availability ). */
    onePerson?: number;
    /** @description Indicates the two person inventory value ( occupancy or availability ). */
    twoPerson?: number;
    /** @description Indicates the three person inventory value ( occupancy or availability ). */
    threePerson?: number;
    /** @description Indicates the four person inventory value ( occupancy or availability ). */
    fourPerson?: number;
    /** @description Indicates the sell limit */
    sellLimit?: number;
    /**
     * Format: date
     * @description Indicates the cutoff date.Date when inventory left in the block will be cut-off.
     */
    cutoffDate?: string;
  };
  /** @description Indicates the sum of revenue breakup per room type per block per allocation date for the reservations. Applicable for past dates, business date or future dates. */
  blockActualRevenueType: {
    /** @description Indicates room revenue amount. */
    roomRevenue?: number;
    /** @description Indicates food revenue amount. */
    foodRevenue?: number;
    /** @description Indicates other revenue amount. */
    otherRevenue?: number;
    /** @description Indicates non revenue amount. */
    nonRevenue?: number;
    /** @description Indicates total revenue amount. */
    totalRevenue?: number;
    /** @description Indicates room revenue tax amount. */
    roomRevenueTax?: number;
    /** @description Indicates food revenue tax amount. */
    foodRevenueTax?: number;
    /** @description Indicates other revenue tax amount. */
    otherRevenueTax?: number;
    /** @description Indicates non revenue tax amount. */
    nonRevenueTax?: number;
    /** @description Indicates total revenue tax amount. */
    totalRevenueTax?: number;
    /** @description Currency code to reflect the currency in which an amount may be expressed. */
    currency?: string;
  };
  /** @description Indicates the sum of revenue breakup per room type per block per allocation date for the reservations. Applicable for business date or future dates. */
  blockPotenitalRevenueType: {
    /** @description Indicates room revenue amount. */
    roomRevenue?: number;
    /** @description Indicates food revenue amount. */
    foodRevenue?: number;
    /** @description Indicates other revenue amount. */
    otherRevenue?: number;
    /** @description Indicates non revenue amount. */
    nonRevenue?: number;
    /** @description Indicates total revenue amount. */
    totalRevenue?: number;
    /** @description Indicates room revenue tax amount. */
    roomRevenueTax?: number;
    /** @description Indicates food revenue tax amount. */
    foodRevenueTax?: number;
    /** @description Indicates other revenue tax amount. */
    otherRevenueTax?: number;
    /** @description Indicates non revenue tax amount. */
    nonRevenueTax?: number;
    /** @description Indicates total revenue tax amount. */
    totalRevenueTax?: number;
    /** @description Currency code to reflect the currency in which an amount may be expressed. */
    currency?: string;
  };
  /** @description Indicates the rate amount values per person occupancy. */
  blockGridRatesType: {
    /** @description Indicates the one person occupancy rate amount. */
    onePerson?: number;
    /** @description Indicates the two person occupancy rate amount. */
    twoPerson?: number;
    /** @description Indicates the three person occupancy rate amount. */
    threePerson?: number;
    /** @description Indicates the four person occupancy rate amount. */
    fourPerson?: number;
    /** @description Indicates the extra person occupancy rate amount. */
    extraPerson?: number;
  };
  /** @description Request object for fetching block allocation summary asynchronously. */
  criteria: {
    /** Format: date */
    startDate?: string;
    /** Format: date */
    endDate?: string;
    /** Format: date */
    occupancyDate?: string;
    /** Format: date-time */
    startLastModifiedDate?: string;
    /** Format: date-time */
    endLastModifiedDate?: string;
    /**
     * @description Boolean flag that indicates whether net rates are to be fetched or not. By default, this value is false.
     * @default false
     */
    includeNetRates?: boolean;
  };
  /** @description Response object for fetched block allocation summary. */
  blockAllocationSummary: definitions["blockAllocationSummaryType"][];
  /** @description An identifier used to uniquely reference an object in a system (e.g. an airline reservation reference, customer profile reference, booking confirmation number, or a reference to a previous availability quote). */
  blockId: {
    /** @description URL that identifies the location associated with the record identified by the UniqueID. */
    url?: string;
    /** @description A reference to the type of object defined by the UniqueID element. */
    type?: string;
    /** @description The identification of a record as it exists at a point in time. An instance is used in update messages where the sender must assure the server that the update sent refers to the most recent modification level of the object being updated. */
    instance?: string;
    /** @description Used to identify the source of the identifier (e.g., IATA, ABTA). */
    idContext?: string;
    /** @description A unique identifying value assigned by the creating system. The ID attribute may be used to reference a primary-key value within a database or in a particular implementation. */
    id?: string;
    /** @description Additional identifying value assigned by the creating system. */
    idExtension?: number;
  };
  /** @description Indicates the inventory values (occupancy or availability) per person occupancy. */
  setBlockGridInvType: {
    /** @description Indicates the one person inventory value (occupancy or availability). */
    onePerson?: number;
    /** @description Indicates the two person inventory value (occupancy or availability). */
    twoPerson?: number;
    /** @description Indicates the three person inventory value (occupancy or availability). */
    threePerson?: number;
    /** @description Indicates the four person inventory value (occupancy or availability). */
    fourPerson?: number;
    /** @description Indicates the sell limit */
    sellLimit?: number;
    /**
     * Format: date
     * @description Indicates the cutoff date.Date when inventory left in the block will be cut-off.
     */
    cutoffDate?: string;
    /** @description Indicates whether to overbook the rooms in case there are not enough rooms at the house or room type level. */
    forceOverbook?: boolean;
  };
  /** @description Indicates the block allocations for a date range. This can be rooms or rate amounts. */
  allocationGridByDateRangeType: {
    /** @description Indicates the room inventory values per person occupancy. */
    inventory?: definitions["setBlockGridInvType"];
    /** @description Indicates the rate amount values per person occupancy. */
    rate?: definitions["blockGridRatesType"];
    /**
     * Format: date
     * @description The starting value of the date range.
     */
    start?: string;
    /**
     * Format: date
     * @description The ending value of the date range.
     */
    end?: string;
    sunday?: boolean;
    monday?: boolean;
    tuesday?: boolean;
    wednesday?: boolean;
    thursday?: boolean;
    friday?: boolean;
    saturday?: boolean;
  };
  /** @description A collection of Allocation objects for a block, such as Current Rooms, Original Rooms, Rate Amounts, etc. */
  allocationGridByDateRangesType: {
    /** @description Allocation objects for a block. */
    roomAllocationInfo?: definitions["allocationGridByDateRangeType"][];
    /** @description Indicates the type of the Allocation objects. */
    allocation?: string;
  };
  /** @description Indicates the sell limits for a date range. This will be rooms. */
  sellLimitGridByDateRangeType: {
    /**
     * Format: date
     * @description The starting value of the date range.
     */
    start?: string;
    /**
     * Format: date
     * @description The ending value of the date range.
     */
    end?: string;
    sunday?: boolean;
    monday?: boolean;
    tuesday?: boolean;
    wednesday?: boolean;
    thursday?: boolean;
    friday?: boolean;
    saturday?: boolean;
    /** @description Indicates the sell limit for the date range. */
    sellLimit?: number;
  };
  /** @description A collection of Allocation objects for a block defined by room type. */
  allocationGridByRoomTypeType: {
    /** @description Allocation objects for a block by date ranges. */
    allocationGridDates?: definitions["allocationGridByDateRangesType"][];
    /** @description Sell limits for a block by date ranges. */
    sellLimitGridDates?: definitions["sellLimitGridByDateRangeType"][];
    /** @description Indicates the room type of the Allocation objects. */
    roomType?: string;
  };
  /** @description A collection of Allocation objects for a block defined by room type. */
  allocationGridByRoomTypesType: {
    /** @description Opera Hotel code for the Set Allocation Grid request. */
    hotelId?: string;
    /** @description Unique block identifier of the block for which the allocations need to be set. */
    blockId?: definitions["blockId"];
    /** @description Allocation objects of a block grouped by room types. */
    allocationRoomTypes?: definitions["allocationGridByRoomTypeType"][];
    /** @description Indicates if the Allocation objects refer to Generic Room Types (Room Pools). */
    genericRoomType?: boolean;
  };
  /** @description A Request message that sets the room allocations as a collection of room types and dates. */
  allocation: {
    /** @description This element contains the block allocations as a collection of room types and dates. */
    criteria?: definitions["allocationGridByRoomTypesType"];
    links?: definitions["links"];
    warnings?: definitions["warningsType"];
  };
  /**
   * @description Status of the process.
   * @enum {string}
   */
  statusType:
    | "Success"
    | "Error"
    | "Running"
    | "Stopped"
    | "Warning"
    | "Failed"
    | "Started"
    | "CompletedWithLogs";
  /** @description This contains a generic code and description information. */
  codeDescriptionType: {
    /** @description Code. */
    code?: string;
    /** @description description. */
    description?: string;
  };
  /** @description Status/Info of the processed events. */
  cateringEventsProcessedInfoType: {
    /** @description Hotel code where event will be copied. */
    hotelId?: string;
    /** @description BlockID of the event. */
    blockId?: definitions["blockId"];
    /** @description Name of event. */
    eventName?: string;
    /** @description Type of event. */
    eventType?: string;
    /**
     * Format: date
     * @description Date of the event
     */
    eventDate?: string;
    /** @description The function space room where the event takes place . */
    room?: definitions["codeDescriptionType"];
    /** @description Status of the processed event. e.g Completed, Not Processed. */
    status?: string;
    /** @description Reason for not processing the event. */
    reason?: string;
    /** @description Flag to indicate the warning messages from the API */
    processingInfoType?: string;
    /** @description Erorr/Warning code for not processing th event. */
    processingInfoCode?: string;
  };
  /** @description Status/Info of the processed events. */
  cateringEventsProcessedInfoList: definitions["cateringEventsProcessedInfoType"][];
  /** @description Response object to hold the details of process. */
  processDetails: {
    /** @description Status of the process. */
    status?: definitions["statusType"];
    /** @description Status of the processed events after the process. */
    cateringEventsProcessedInfo?: definitions["cateringEventsProcessedInfoList"];
    links?: definitions["links"];
    warnings?: definitions["warningsType"];
  };
  /**
   * @description Simple type for block allocation used in room rate grid.
   * @enum {string}
   */
  allocationType:
    | "Initial"
    | "Actual"
    | "Rates"
    | "Pickup"
    | "Contract"
    | "Available"
    | "Pickupperc"
    | "Changes"
    | "Released"
    | "Houseavailability"
    | "SellLimit"
    | "AvailableSellLimit"
    | "MasterAllocInitial"
    | "Allocated"
    | "SubAllocResv"
    | "CutoffDate"
    | "ForecastRooms"
    | "ForecastRates";
  /**
   * @description Enumerates range operation modes.
   * @enum {string}
   */
  blockRangeModeType: "Core" | "ShoulderStart" | "ShoulderEnd";
  /** @description Container for information related to block allocation range update operation */
  blockAllocationRangeType: {
    /** @description Specifies the Block ID which is the unique identifier for the Block for both internal and external systems. */
    blockId?: definitions["blockId"];
    hotelId?: string;
    /** @description List of room types for which the range update has to be applied. */
    roomTypes?: string[];
    /**
     * Format: date
     * @description Begin date for range update operation.
     */
    beginDate?: string;
    /**
     * Format: date
     * @description End date for range update operation.
     */
    endDate?: string;
    /** @description Allocation type for which the range operation is applied. */
    allocationType?: definitions["allocationType"];
    /** @description Flag to indicate if the occupancy data is absolute or relative to the current value. */
    incrementFlag?: boolean;
    /** @description Occupancy data for range operation. */
    blockInventory?: definitions["blockGridInvType"];
    /** @description Rate details for range operation. */
    blockRates?: definitions["blockGridRatesType"];
    /**
     * Format: date
     * @description Date after which unused block rooms should be returned to house.
     */
    cutoffDate?: string;
    /** @description Number of days from block start date after which unused block rooms should be returned to house. */
    cutoffDays?: number;
    /** @description A true value indicates that the cutoff schedule, if added to Business Block, can be overridden. */
    overrideCutoffSchedule?: boolean;
    includedDays?: string;
    /** @description Indicates whether the range is being applied on shoulder dates or core dates. */
    rangeMode?: definitions["blockRangeModeType"];
    /** @description Date which has to be overbooked or excluded. */
    overbookList?: {
      /**
       * Format: date
       * @description Date which has to be overbooked or excluded.
       */
      stayDate?: string;
      /** @description Room type that has to be overbooked or excluded. */
      roomType?: string;
      /** @description A true value indicates that the date/room type should be overbooked for inventory. A false value indicates that this combination should be excluded from range. */
      overbook?: boolean;
    }[];
    /** @description Indicates if the Allocation objects refer to Generic Room Types (Room Pools). */
    genericRoomType?: boolean;
  };
  /** @description Collection of block allocation ranges. */
  blockAllocationRanges: {
    /** @description Collection of Range information for the block allocation ranges operation. */
    blockAllocationRanges?: definitions["blockAllocationRangeType"][];
  };
  /** @description Request for setting block allocation for ranges of dates for a list of room types. */
  allocationRanges: {
    /** @description Collection of Range information for the block allocation ranges operation. */
    allocationRanges?: definitions["blockAllocationRanges"];
    /** @description Indicates if the Allocation objects refer to Generic Room Types (Room Pools). */
    genericRoomType?: boolean;
    links?: definitions["links"];
    warnings?: definitions["warningsType"];
  };
  shiftBlockCriteriaType: {
    /**
     * Format: date
     * @description New start date of the business block.
     */
    newStartDate?: string;
    /** @description When true, this will remove alternate dates for this block before shifting dates. */
    removeAlternateDates?: boolean;
    /** @description When true, this will validate alternate dates for this block before shifting dates. */
    validateAlternateDates?: boolean;
    /** @description When true, this will overbook allocated rooms if needed. */
    overbookAll?: boolean;
    /** @description When true, this will validate if there are rooms pre-allocated before shifting the block dates. */
    validatePreAllocatedRooms?: boolean;
    /** @description When true, this will validate if there are active traces before shifting the block dates. */
    validateTraces?: boolean;
    /** @description Indicates whether to ignore any warning during applying the changes to the events associated with the current block. */
    overrideEventsProcessingWarnings?: boolean;
  };
  /** @description Request object to shift business block starting date. */
  blockToShift: {
    /** @description Contains details of the block to be shifted along with the new start date to be applied. */
    criteria?: definitions["shiftBlockCriteriaType"];
    links?: definitions["links"];
    warnings?: definitions["warningsType"];
  };
}

export interface parameters {
  /** @description Pass this header as true, if payload needs DVM */
  externalData: string;
  /** @description Bearer token that needs to be passed which is generated post user authentication */
  authKey: string;
  /** @description Client or Partner's Application Key */
  "x-app-key": string;
  /** @description Request Id of an incoming request */
  "x-request-id": string;
  /** @description Customer's Integration Application Id */
  "x-originating-application": string;
  /** @description Mandatory parameter to identify the hotel code where the end user is logged in */
  "x-hotelid": string;
  /** @description Language code */
  "Accept-Language": string;
}

export interface responses {
  /** Bad Request */
  400: {
    schema: definitions["exceptionDetailType"];
  };
  /** Unauthorized */
  401: unknown;
  /** Forbidden */
  403: unknown;
  /** Resource not found */
  404: {
    schema: definitions["exceptionDetailType"];
  };
  /** Method not allowed */
  405: unknown;
  /** Not acceptable. */
  406: unknown;
  /** Request Entity Too Large */
  413: unknown;
  /** Request URI Too Large */
  414: unknown;
  /** Unsupported Media Type */
  415: unknown;
  /** System Error */
  500: {
    schema: definitions["exceptionDetailType"];
  };
  /** Bad Gateway */
  502: unknown;
  /** Service Unavailable */
  503: unknown;
}

export interface operations {
  /** This API will fetch Block allocation information for a hotel, and specified date range. The block allocated inventory, rates and room type statistics are returned as part of the response. The maximum limit of date range (whether using start/endDate or startLastModifiedDate/endLastModifiedDate) is 94 days, but the recommendation is to use a date range proportionate to the size of the hotel.   Every identical request (employing the same query parameters) for the getBlockAllocationSummary operation when requesting data with start/endDate or startLastModifiedDate/endLastModifiedDate, necessitates a mandatory 30-minute interval between submissions. Please note that this limit applies regardless of whether the POST, HEAD, and GET cycle has been completed. The API returns a header parameter location that can be used in the getBlockAllocationSummaryProcessStatus operation.  Use event-driven APIs -(see https://docs.oracle.com/cd/F29336_01/doc.201/f27480/c_business_events.htm#OHIPU-BusinessEvents-F0AC1F1C) -to get real-time block updates. <p><strong>OperationId:</strong>startBlockAllocationSummaryProcess</p> */
  startBlockAllocationSummaryProcess: {
    parameters: {
      path: {
        hotelId: string;
        extSystemCode: string;
      };
      body: {
        /** Request object for fetching block allocation summary asynchronously. */
        criteria: definitions["criteria"];
      };
      header: {
        /** Bearer token that needs to be passed which is generated post user authentication */
        authorization: parameters["authKey"];
        /** Pass this header as true, if payload needs DVM */
        externalData?: parameters["externalData"];
        /** Client or Partner's Application Key */
        "x-app-key": parameters["x-app-key"];
        /** Request Id of an incoming request */
        "x-request-id"?: parameters["x-request-id"];
        /** Customer's Integration Application Id */
        "x-originating-application"?: parameters["x-originating-application"];
        /** Mandatory parameter to identify the hotel code where the end user is logged in */
        "x-hotelid": parameters["x-hotelid"];
        /** Language code */
        "Accept-Language"?: parameters["Accept-Language"];
      };
    };
    responses: {
      /** HATEOAS links which help the consumer to navigate to resources */
      202: {
        headers: {};
        schema: definitions["links"];
      };
      400: responses["400"];
      401: responses["401"];
      403: responses["403"];
      404: responses["404"];
      405: responses["405"];
      406: responses["406"];
      413: responses["413"];
      414: responses["414"];
      415: responses["415"];
      500: responses["500"];
      502: responses["502"];
      503: responses["503"];
    };
  };
  /** This API will fetch Block allocation information for a hotel, and specified date range.  The block allocated inventory, rates and room type statistics are returned as part of the response. <p><strong>OperationId:</strong>getBlockAllocationSummary</p> */
  getBlockAllocationSummary: {
    parameters: {
      path: {
        requestId: string;
        hotelId: string;
        extSystemCode: string;
      };
      header: {
        /** Bearer token that needs to be passed which is generated post user authentication */
        authorization: parameters["authKey"];
        /** Pass this header as true, if payload needs DVM */
        externalData?: parameters["externalData"];
        /** Client or Partner's Application Key */
        "x-app-key": parameters["x-app-key"];
        /** Request Id of an incoming request */
        "x-request-id"?: parameters["x-request-id"];
        /** Customer's Integration Application Id */
        "x-originating-application"?: parameters["x-originating-application"];
        /** Mandatory parameter to identify the hotel code where the end user is logged in */
        "x-hotelid": parameters["x-hotelid"];
        /** Language code */
        "Accept-Language"?: parameters["Accept-Language"];
      };
    };
    responses: {
      /** Callback request object for fetched block allocation summary. */
      200: {
        headers: {};
        schema: definitions["blockAllocationSummary"];
      };
      /** BlockAllocationSummary not found. */
      204: never;
      400: responses["400"];
      401: responses["401"];
      403: responses["403"];
      404: responses["404"];
      405: responses["405"];
      406: responses["406"];
      413: responses["413"];
      414: responses["414"];
      415: responses["415"];
      500: responses["500"];
      502: responses["502"];
      503: responses["503"];
    };
  };
  /** <p><strong>OperationId:</strong>getBlockAllocationSummaryProcessStatus</p> */
  getBlockAllocationSummaryProcessStatus: {
    parameters: {
      path: {
        requestId: string;
        extSystemCode: string;
        hotelId: string;
      };
      header: {
        /** Bearer token that needs to be passed which is generated post user authentication */
        authorization: parameters["authKey"];
        /** Pass this header as true, if payload needs DVM */
        externalData?: parameters["externalData"];
        /** Client or Partner's Application Key */
        "x-app-key": parameters["x-app-key"];
        /** Request Id of an incoming request */
        "x-request-id"?: parameters["x-request-id"];
        /** Customer's Integration Application Id */
        "x-originating-application"?: parameters["x-originating-application"];
        /** Mandatory parameter to identify the hotel code where the end user is logged in */
        "x-hotelid": parameters["x-hotelid"];
        /** Language code */
        "Accept-Language"?: parameters["Accept-Language"];
      };
    };
    responses: {
      /** Response for status of scheduled asynchronous process. */
      200: unknown;
      /** Response for status of scheduled asynchronous process. */
      201: unknown;
      400: responses["400"];
      401: responses["401"];
      403: responses["403"];
      404: responses["404"];
      405: responses["405"];
      406: responses["406"];
      413: responses["413"];
      414: responses["414"];
      415: responses["415"];
      500: responses["500"];
      502: responses["502"];
      503: responses["503"];
    };
  };
  /** Use this API to add block room type allocations and rates to a specified Block. <p><strong>OperationId:</strong>startBlockAllocationProcess</p> */
  startBlockAllocationProcess: {
    parameters: {
      path: {
        hotelId: string;
        /** Unique OPERA Block ID which is used to find a Block from OPERA. This ID is a primary identification of a Block in OPERA. */
        blockId: string;
      };
      body: {
        /** A Request message that sets the room allocations as a collection of room types and dates. */
        allocation: definitions["allocation"];
      };
      header: {
        /** Bearer token that needs to be passed which is generated post user authentication */
        authorization: parameters["authKey"];
        /** Pass this header as true, if payload needs DVM */
        externalData?: parameters["externalData"];
        /** Client or Partner's Application Key */
        "x-app-key": parameters["x-app-key"];
        /** Request Id of an incoming request */
        "x-request-id"?: parameters["x-request-id"];
        /** Customer's Integration Application Id */
        "x-originating-application"?: parameters["x-originating-application"];
        /** Mandatory parameter to identify the hotel code where the end user is logged in */
        "x-hotelid": parameters["x-hotelid"];
        /** Language code */
        "Accept-Language"?: parameters["Accept-Language"];
      };
    };
    responses: {
      /** HATEOAS links which help the consumer to navigate to resources */
      202: {
        headers: {};
        schema: definitions["links"];
      };
      400: responses["400"];
      401: responses["401"];
      403: responses["403"];
      404: responses["404"];
      405: responses["405"];
      406: responses["406"];
      413: responses["413"];
      414: responses["414"];
      415: responses["415"];
      500: responses["500"];
      502: responses["502"];
      503: responses["503"];
    };
  };
  /** This API will fetch Block allocation warnings for a hotel to allow for overbooking information to be returned as part of the response. <p><strong>OperationId:</strong>getBlockAllocationProcessInfo</p> */
  getBlockAllocationProcessInfo: {
    parameters: {
      path: {
        hotelId: string;
        /** Unique OPERA Block ID which is used to find a Block from OPERA. This ID is a primary identification of a Block in OPERA. */
        blockId: string;
        requestId: string;
      };
      header: {
        /** Bearer token that needs to be passed which is generated post user authentication */
        authorization: parameters["authKey"];
        /** Pass this header as true, if payload needs DVM */
        externalData?: parameters["externalData"];
        /** Client or Partner's Application Key */
        "x-app-key": parameters["x-app-key"];
        /** Request Id of an incoming request */
        "x-request-id"?: parameters["x-request-id"];
        /** Customer's Integration Application Id */
        "x-originating-application"?: parameters["x-originating-application"];
        /** Mandatory parameter to identify the hotel code where the end user is logged in */
        "x-hotelid": parameters["x-hotelid"];
        /** Language code */
        "Accept-Language"?: parameters["Accept-Language"];
      };
    };
    responses: {
      /** Callback request object for fetched block allocation process information. */
      200: {
        headers: {};
        schema: definitions["processDetails"];
      };
      /** BlockAllocationProcessInfo not found. */
      204: never;
      400: responses["400"];
      401: responses["401"];
      403: responses["403"];
      404: responses["404"];
      405: responses["405"];
      406: responses["406"];
      413: responses["413"];
      414: responses["414"];
      415: responses["415"];
      500: responses["500"];
      502: responses["502"];
      503: responses["503"];
    };
  };
  /** <p><strong>OperationId:</strong>getBlockAllocationProcessStatus</p> */
  getBlockAllocationProcessStatus: {
    parameters: {
      path: {
        hotelId: string;
        /** Unique OPERA Block ID which is used to find a Block from OPERA. This ID is a primary identification of a Block in OPERA. */
        blockId: string;
        requestId: string;
      };
      header: {
        /** Bearer token that needs to be passed which is generated post user authentication */
        authorization: parameters["authKey"];
        /** Pass this header as true, if payload needs DVM */
        externalData?: parameters["externalData"];
        /** Client or Partner's Application Key */
        "x-app-key": parameters["x-app-key"];
        /** Request Id of an incoming request */
        "x-request-id"?: parameters["x-request-id"];
        /** Customer's Integration Application Id */
        "x-originating-application"?: parameters["x-originating-application"];
        /** Mandatory parameter to identify the hotel code where the end user is logged in */
        "x-hotelid": parameters["x-hotelid"];
        /** Language code */
        "Accept-Language"?: parameters["Accept-Language"];
      };
    };
    responses: {
      /** Response for status of scheduled asynchronous process. */
      200: unknown;
      /** Response for status of scheduled asynchronous process. */
      201: unknown;
      400: responses["400"];
      401: responses["401"];
      403: responses["403"];
      404: responses["404"];
      405: responses["405"];
      406: responses["406"];
      413: responses["413"];
      414: responses["414"];
      415: responses["415"];
      500: responses["500"];
      502: responses["502"];
      503: responses["503"];
    };
  };
  /** Use this API to set business block allocation for one or more date ranges, which are within business block date range, and for a list of room types. <p><strong>OperationId:</strong>startAllocationRangesProcess</p> */
  startAllocationRangesProcess: {
    parameters: {
      path: {
        hotelId: string;
        /** Unique OPERA Block ID which is used to find a Block from OPERA. This ID is a primary identification of a Block in OPERA. */
        blockId: string;
      };
      body: {
        /** Request for updating block allocations for ranges of dates and list of room types. */
        allocationRanges: definitions["allocationRanges"];
      };
      header: {
        /** Bearer token that needs to be passed which is generated post user authentication */
        authorization: parameters["authKey"];
        /** Pass this header as true, if payload needs DVM */
        externalData?: parameters["externalData"];
        /** Client or Partner's Application Key */
        "x-app-key": parameters["x-app-key"];
        /** Request Id of an incoming request */
        "x-request-id"?: parameters["x-request-id"];
        /** Customer's Integration Application Id */
        "x-originating-application"?: parameters["x-originating-application"];
        /** Mandatory parameter to identify the hotel code where the end user is logged in */
        "x-hotelid": parameters["x-hotelid"];
        /** Language code */
        "Accept-Language"?: parameters["Accept-Language"];
      };
    };
    responses: {
      /** HATEOAS links which help the consumer to navigate to resources */
      202: {
        headers: {};
        schema: definitions["links"];
      };
      400: responses["400"];
      401: responses["401"];
      403: responses["403"];
      404: responses["404"];
      405: responses["405"];
      406: responses["406"];
      413: responses["413"];
      414: responses["414"];
      415: responses["415"];
      500: responses["500"];
      502: responses["502"];
      503: responses["503"];
    };
  };
  /** This API will fetch Block allocation ranges warnings for a hotel to allow for overbooking information to be returned as part of the response. <p><strong>OperationId:</strong>getAllocationRangesProcessInfo</p> */
  getAllocationRangesProcessInfo: {
    parameters: {
      path: {
        hotelId: string;
        /** Unique OPERA Block ID which is used to find a Block from OPERA. This ID is a primary identification of a Block in OPERA. */
        blockId: string;
        requestId: string;
      };
      header: {
        /** Bearer token that needs to be passed which is generated post user authentication */
        authorization: parameters["authKey"];
        /** Pass this header as true, if payload needs DVM */
        externalData?: parameters["externalData"];
        /** Client or Partner's Application Key */
        "x-app-key": parameters["x-app-key"];
        /** Request Id of an incoming request */
        "x-request-id"?: parameters["x-request-id"];
        /** Customer's Integration Application Id */
        "x-originating-application"?: parameters["x-originating-application"];
        /** Mandatory parameter to identify the hotel code where the end user is logged in */
        "x-hotelid": parameters["x-hotelid"];
        /** Language code */
        "Accept-Language"?: parameters["Accept-Language"];
      };
    };
    responses: {
      /** Callback request object for fetched block allocation process information. */
      200: {
        headers: {};
        schema: definitions["processDetails"];
      };
      /** AllocationRangesProcessInfo not found. */
      204: never;
      400: responses["400"];
      401: responses["401"];
      403: responses["403"];
      404: responses["404"];
      405: responses["405"];
      406: responses["406"];
      413: responses["413"];
      414: responses["414"];
      415: responses["415"];
      500: responses["500"];
      502: responses["502"];
      503: responses["503"];
    };
  };
  /** <p><strong>OperationId:</strong>getAllocationRangesProcessStatus</p> */
  getAllocationRangesProcessStatus: {
    parameters: {
      path: {
        hotelId: string;
        /** Unique OPERA Block ID which is used to find a Block from OPERA. This ID is a primary identification of a Block in OPERA. */
        blockId: string;
        requestId: string;
      };
      header: {
        /** Bearer token that needs to be passed which is generated post user authentication */
        authorization: parameters["authKey"];
        /** Pass this header as true, if payload needs DVM */
        externalData?: parameters["externalData"];
        /** Client or Partner's Application Key */
        "x-app-key": parameters["x-app-key"];
        /** Request Id of an incoming request */
        "x-request-id"?: parameters["x-request-id"];
        /** Customer's Integration Application Id */
        "x-originating-application"?: parameters["x-originating-application"];
        /** Mandatory parameter to identify the hotel code where the end user is logged in */
        "x-hotelid": parameters["x-hotelid"];
        /** Language code */
        "Accept-Language"?: parameters["Accept-Language"];
      };
    };
    responses: {
      /** Response for status of scheduled asynchronous process. */
      200: unknown;
      /** Response for status of scheduled asynchronous process. */
      201: unknown;
      400: responses["400"];
      401: responses["401"];
      403: responses["403"];
      404: responses["404"];
      405: responses["405"];
      406: responses["406"];
      413: responses["413"];
      414: responses["414"];
      415: responses["415"];
      500: responses["500"];
      502: responses["502"];
      503: responses["503"];
    };
  };
  /** Use this API to move or shift the dates of a block in OPERA. <p><strong>OperationId:</strong>startShiftBlockProcess</p> */
  startShiftBlockProcess: {
    parameters: {
      path: {
        hotelId: string;
        /** Unique OPERA Block ID which is used to find a Block from OPERA. This ID is a primary identification of a Block in OPERA. */
        blockId: string;
      };
      body: {
        /** Request object to shift business block starting date. */
        blockToShift: definitions["blockToShift"];
      };
      header: {
        /** Bearer token that needs to be passed which is generated post user authentication */
        authorization: parameters["authKey"];
        /** Pass this header as true, if payload needs DVM */
        externalData?: parameters["externalData"];
        /** Client or Partner's Application Key */
        "x-app-key": parameters["x-app-key"];
        /** Request Id of an incoming request */
        "x-request-id"?: parameters["x-request-id"];
        /** Customer's Integration Application Id */
        "x-originating-application"?: parameters["x-originating-application"];
        /** Mandatory parameter to identify the hotel code where the end user is logged in */
        "x-hotelid": parameters["x-hotelid"];
        /** Language code */
        "Accept-Language"?: parameters["Accept-Language"];
      };
    };
    responses: {
      /** HATEOAS links which help the consumer to navigate to resources */
      202: {
        headers: {};
        schema: definitions["links"];
      };
      400: responses["400"];
      401: responses["401"];
      403: responses["403"];
      404: responses["404"];
      405: responses["405"];
      406: responses["406"];
      413: responses["413"];
      414: responses["414"];
      415: responses["415"];
      500: responses["500"];
      502: responses["502"];
      503: responses["503"];
    };
  };
  /** This API will fetch shift Block warnings and errors to be returned as part of the response. <p><strong>OperationId:</strong>getShiftBlockProcessInfo</p> */
  getShiftBlockProcessInfo: {
    parameters: {
      path: {
        hotelId: string;
        /** Unique OPERA Block ID which is used to find a Block from OPERA. This ID is a primary identification of a Block in OPERA. */
        blockId: string;
        requestId: string;
      };
      header: {
        /** Bearer token that needs to be passed which is generated post user authentication */
        authorization: parameters["authKey"];
        /** Pass this header as true, if payload needs DVM */
        externalData?: parameters["externalData"];
        /** Client or Partner's Application Key */
        "x-app-key": parameters["x-app-key"];
        /** Request Id of an incoming request */
        "x-request-id"?: parameters["x-request-id"];
        /** Customer's Integration Application Id */
        "x-originating-application"?: parameters["x-originating-application"];
        /** Mandatory parameter to identify the hotel code where the end user is logged in */
        "x-hotelid": parameters["x-hotelid"];
        /** Language code */
        "Accept-Language"?: parameters["Accept-Language"];
      };
    };
    responses: {
      /** Callback request object for fetched shift block process information. */
      200: {
        headers: {};
        schema: definitions["processDetails"];
      };
      /** Shift Block information not found. */
      204: never;
      400: responses["400"];
      401: responses["401"];
      403: responses["403"];
      404: responses["404"];
      405: responses["405"];
      406: responses["406"];
      413: responses["413"];
      414: responses["414"];
      415: responses["415"];
      500: responses["500"];
      502: responses["502"];
      503: responses["503"];
    };
  };
  /** <p><strong>OperationId:</strong>getShiftBlockProcessStatus</p> */
  getShiftBlockProcessStatus: {
    parameters: {
      path: {
        hotelId: string;
        /** Unique OPERA Block ID which is used to find a Block from OPERA. This ID is a primary identification of a Block in OPERA. */
        blockId: string;
        requestId: string;
      };
      header: {
        /** Bearer token that needs to be passed which is generated post user authentication */
        authorization: parameters["authKey"];
        /** Pass this header as true, if payload needs DVM */
        externalData?: parameters["externalData"];
        /** Client or Partner's Application Key */
        "x-app-key": parameters["x-app-key"];
        /** Request Id of an incoming request */
        "x-request-id"?: parameters["x-request-id"];
        /** Customer's Integration Application Id */
        "x-originating-application"?: parameters["x-originating-application"];
        /** Mandatory parameter to identify the hotel code where the end user is logged in */
        "x-hotelid": parameters["x-hotelid"];
        /** Language code */
        "Accept-Language"?: parameters["Accept-Language"];
      };
    };
    responses: {
      /** Response for status of scheduled asynchronous process. */
      200: unknown;
      /** Response for status of scheduled asynchronous process. */
      201: unknown;
      400: responses["400"];
      401: responses["401"];
      403: responses["403"];
      404: responses["404"];
      405: responses["405"];
      406: responses["406"];
      413: responses["413"];
      414: responses["414"];
      415: responses["415"];
      500: responses["500"];
      502: responses["502"];
      503: responses["503"];
    };
  };
  /** Use this API to recalculate room forecast rates */
  startRecalculateRoomForecastProcess: {
    parameters: {
      path: {
        /** Hotel code where the Block resides. */
        hotelId: string;
        /** Unique OPERA Block ID which is used to find a Block from OPERA. This ID is a primary identification of a Block in OPERA. */
        blockId: string;
      };
      body: {
        /** Unique OPERA Block ID which is used to find a Block from OPERA. */
        blockId?: definitions["blockId"];
      };
      header: {
        /** Bearer token that needs to be passed which is generated post user authentication */
        authorization: parameters["authKey"];
        /** Pass this header as true, if payload needs DVM */
        externalData?: parameters["externalData"];
        /** Client or Partner's Application Key */
        "x-app-key": parameters["x-app-key"];
        /** Request Id of an incoming request */
        "x-request-id"?: parameters["x-request-id"];
        /** Customer's Integration Application Id */
        "x-originating-application"?: parameters["x-originating-application"];
        /** Mandatory parameter to identify the hotel code where the end user is logged in */
        "x-hotelid": parameters["x-hotelid"];
        /** Language code */
        "Accept-Language"?: parameters["Accept-Language"];
      };
    };
    responses: {
      /** HATEOAS links which help the consumer to navigate to resources */
      202: {
        headers: {};
        schema: definitions["links"];
      };
    };
  };
  /** This API will fetch recalculate room forecast warnings and errors to be returned as part of the response.<p><strong>OperationId:</strong>getRecalculateRoomForecastProcessInfo</p> */
  getRecalculateRoomForecastProcessInfo: {
    parameters: {
      path: {
        hotelId: string;
        /** Unique OPERA Block ID which is used to find a Block from OPERA. This ID is a primary identification of a Block in OPERA. */
        blockId: string;
        requestId: string;
      };
      header: {
        /** Bearer token that needs to be passed which is generated post user authentication */
        authorization: parameters["authKey"];
        /** Pass this header as true, if payload needs DVM */
        externalData?: parameters["externalData"];
        /** Client or Partner's Application Key */
        "x-app-key": parameters["x-app-key"];
        /** Request Id of an incoming request */
        "x-request-id"?: parameters["x-request-id"];
        /** Customer's Integration Application Id */
        "x-originating-application"?: parameters["x-originating-application"];
        /** Mandatory parameter to identify the hotel code where the end user is logged in */
        "x-hotelid": parameters["x-hotelid"];
        /** Language code */
        "Accept-Language"?: parameters["Accept-Language"];
      };
    };
    responses: {
      /** Callback request object for fetched recalculate room forecast process information. */
      200: {
        headers: {};
        schema: definitions["processDetails"];
      };
      /** Information related to recalculateRoomForecast request not found. */
      204: never;
    };
  };
  /** <p><strong>OperationId:</strong>getRecalculateRoomForecastProcessStatus</p> */
  getRecalculateRoomForecastProcessStatus: {
    parameters: {
      path: {
        hotelId: string;
        /** Unique OPERA Block ID which is used to find a Block from OPERA. This ID is a primary identification of a Block in OPERA. */
        blockId: string;
        requestId: string;
      };
      header: {
        /** Bearer token that needs to be passed which is generated post user authentication */
        authorization: parameters["authKey"];
        /** Pass this header as true, if payload needs DVM */
        externalData?: parameters["externalData"];
        /** Client or Partner's Application Key */
        "x-app-key": parameters["x-app-key"];
        /** Request Id of an incoming request */
        "x-request-id"?: parameters["x-request-id"];
        /** Customer's Integration Application Id */
        "x-originating-application"?: parameters["x-originating-application"];
        /** Mandatory parameter to identify the hotel code where the end user is logged in */
        "x-hotelid": parameters["x-hotelid"];
        /** Language code */
        "Accept-Language"?: parameters["Accept-Language"];
      };
    };
    responses: {
      /** Response for status of scheduled asynchronous process. */
      200: unknown;
      /** Response for status of scheduled asynchronous process. */
      201: unknown;
    };
  };
  /** Use this API to refresh Business Block projected revenues */
  startRefreshProjectedRevenuesProcess: {
    parameters: {
      path: {
        /** Hotel code where the Business Block resides. */
        hotelId: string;
        /** Unique OPERA ID which is used to find a Block in OPERA Cloud. This ID is a primary identification of a Business Block in OPERA Cloud. */
        blockId: string;
      };
      body: {
        /** Unique OPERA ID which is used to find a Business Block in OPERA Cloud. */
        blockId?: definitions["blockId"];
      };
      header: {
        /** Bearer token that needs to be passed which is generated post user authentication */
        authorization: parameters["authKey"];
        /** Pass this header as true, if payload needs DVM */
        externalData?: parameters["externalData"];
        /** Client or Partner's Application Key */
        "x-app-key": parameters["x-app-key"];
        /** Request Id of an incoming request */
        "x-request-id"?: parameters["x-request-id"];
        /** Customer's Integration Application Id */
        "x-originating-application"?: parameters["x-originating-application"];
        /** Mandatory parameter to identify the hotel code where the end user is logged in */
        "x-hotelid": parameters["x-hotelid"];
        /** Language code */
        "Accept-Language"?: parameters["Accept-Language"];
      };
    };
    responses: {
      /** HATEOAS links which help the consumer to navigate to resources */
      202: {
        headers: {};
        schema: definitions["links"];
      };
    };
  };
  /** To include as part of response, this API will fetch warnings and/or errors (if any) from Business Block projected revenues refresh process.<p><strong>OperationId:</strong>getRefreshProjectedRevenuesProcessInfo</p> */
  getRefreshProjectedRevenuesProcessInfo: {
    parameters: {
      path: {
        /** Hotel code where the Business Block resides. */
        hotelId: string;
        /** Unique OPERA ID which is used to find a Block in OPERA Cloud. This ID is a primary identification of a Business Block in OPERA Cloud. */
        blockId: string;
        requestId: string;
      };
      header: {
        /** Bearer token that needs to be passed which is generated post user authentication */
        authorization: parameters["authKey"];
        /** Pass this header as true, if payload needs DVM */
        externalData?: parameters["externalData"];
        /** Client or Partner's Application Key */
        "x-app-key": parameters["x-app-key"];
        /** Request Id of an incoming request */
        "x-request-id"?: parameters["x-request-id"];
        /** Customer's Integration Application Id */
        "x-originating-application"?: parameters["x-originating-application"];
        /** Mandatory parameter to identify the hotel code where the end user is logged in */
        "x-hotelid": parameters["x-hotelid"];
        /** Language code */
        "Accept-Language"?: parameters["Accept-Language"];
      };
    };
    responses: {
      /** Callback request object for fetched recalculate room forecast process information. */
      200: {
        headers: {};
        schema: definitions["processDetails"];
      };
      /** Information related to recalculateRoomForecast request not found. */
      204: never;
    };
  };
  /** <p><strong>OperationId:</strong>getRefreshProjectedRevenuesProcessStatus</p> */
  getRefreshProjectedRevenuesProcessStatus: {
    parameters: {
      path: {
        /** Hotel code where the Business Block resides. */
        hotelId: string;
        /** Unique OPERA ID which is used to find a Block in OPERA Cloud. This ID is a primary identification of a Business Block in OPERA Cloud. */
        blockId: string;
        requestId: string;
      };
      header: {
        /** Bearer token that needs to be passed which is generated post user authentication */
        authorization: parameters["authKey"];
        /** Pass this header as true, if payload needs DVM */
        externalData?: parameters["externalData"];
        /** Client or Partner's Application Key */
        "x-app-key": parameters["x-app-key"];
        /** Request Id of an incoming request */
        "x-request-id"?: parameters["x-request-id"];
        /** Customer's Integration Application Id */
        "x-originating-application"?: parameters["x-originating-application"];
        /** Mandatory parameter to identify the hotel code where the end user is logged in */
        "x-hotelid": parameters["x-hotelid"];
        /** Language code */
        "Accept-Language"?: parameters["Accept-Language"];
      };
    };
    responses: {
      /** Response for status of scheduled asynchronous process. */
      200: unknown;
      /** Response for status of scheduled asynchronous process. */
      201: unknown;
    };
  };
}

export interface external {}
