/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/stayRecords": {
    /** A user can upload various stay records to OPERA by specifying stay record column details in the request.<p><strong>OperationId:</strong>stayRecords</p> */
    post: operations["stayRecords"];
  };
  "/stayRecords/{requestId}": {
    /** Use this to check whether the request sent have been processed. <p><strong>OperationId:</strong>getStayRecordsProcess</p> */
    get: operations["getStayRecordsProcess"];
    /** Use this to check whether the request sent have been processed. <p><strong>OperationId:</strong>getStayRecordsProcessStatus</p> */
    head: operations["getStayRecordsProcessStatus"];
  };
}

export interface definitions {
  /**
   * Error Detail
   * @description Complex type that contains error details for a REST call.
   */
  exceptionDetailType: {
    /** @description Absolute URI [RFC3986] that identifies the problem type.  When dereferenced, it SHOULD provide a human-readable summary of the problem (for example, using HTML). */
    type?: string;
    /** @description Short, human-readable summary of the problem.  The summary SHOULD NOT change for subsequent occurrences of the problem, except for purposes of localization. */
    title?: string;
    /** @description HTTP status code for this occurrence of the problem, set by the origin server. */
    status?: number;
    /** @description Human-readable description specific to this occurrence of the problem. */
    detail?: string;
    /** @description Absolute URI that identifies the specific occurrence of the problem.  It may or may not provide additional information if dereferenced. */
    instance?: string;
    /** @description Application error code, which is different from HTTP error code. */
    "o:errorCode"?: string;
    /** @description Path to the problem at the resource or property level. */
    "o:errorPath"?: string;
    /** @description Details of the error message, consisting of a hierarchical tree structure. */
    "o:errorDetails"?: definitions["errorInstance"][];
    links?: definitions["links"];
  };
  /** @description Metadata describing link description objects that MAY appear in the JSON instance representation. */
  instanceLink: {
    /** @description URI [RFC3986] or URI Template [RFC6570]. If the value is set to URI Template, then the "templated" property must be set to true. */
    href?: string;
    /** @description Name of the link relation that, in addition to the type property, can be used to retrieve link details. For example, href or profile. */
    rel?: string;
    /**
     * @description Boolean flag that specifies that "href" property is a URI or URI Template. If the property is a URI template, set this value to true. By default, this value is false.
     * @default false
     */
    templated?: boolean;
    /**
     * @description HTTP method for requesting the target of the link.
     * @enum {string}
     */
    method?: "GET" | "POST" | "PUT" | "DELETE" | "PATCH" | "OPTIONS" | "HEAD";
    /** @description Link to the metadata of the resource, such as JSON-schema, that describes the resource expected when dereferencing the target resource.. */
    targetSchema?: string;
    /** @description The operationId of the path you can call to follow this link.  This allows you to look up not only the path and method, but the description of that path and any parameters you need to supply. */
    operationId?: string;
    /** @description Exact copy of the "summary" field on the linked operation. */
    title?: string;
  };
  links: definitions["instanceLink"][];
  /**
   * Error Instance Details
   * @description Complex type that contains error instance details for a REST call.
   */
  errorInstance: {
    /** @description Absolute URI [RFC3986] that identifies the problem type.  When dereferenced, it SHOULD provide a human-readable summary of the problem (for example, using HTML). */
    type?: string;
    /** @description Short, human-readable summary of the problem.  The summary SHOULD NOT change for subsequent occurrences of the problem, except for purposes of localization. */
    title?: string;
    /** @description HTTP status code for this occurrence of the problem, set by the origin server. */
    status?: number;
    /** @description Human-readable description specific to this occurrence of the problem. */
    detail?: string;
    /** @description Absolute URI that identifies the specific occurrence of the problem.  It may or may not provide additional information if dereferenced. */
    instance?: string;
    /** @description Application error code, which is different from HTTP error code. */
    "o:errorCode"?: string;
    /** @description Path to the problem at the resource or property level. */
    "o:errorPath"?: string;
  };
  /** @description Used when a stay record is successfully processed to repory any warnings or business error. */
  warningType: {
    /** @description Property Value */
    value?: string;
    /** @description An abbreviated version of the error in textual format. */
    shortText?: string;
    /** @description If present, this refers to a table of coded values exchanged between applications to identify errors or warnings. */
    code?: string;
    /** @description If present, this URL refers to an online description of the error that occurred. */
    docURL?: string;
    /** @description If present, recommended values are those enumerated in the ErrorRS, (NotProcessed Incomplete Complete Unknown) however, the data type is designated as string data, recognizing that trading partners may identify additional status conditions not included in the enumeration. */
    status?: string;
    /** @description If present, this attribute may identify an unknown or misspelled tag that caused an error in processing. It is recommended that the Tag attribute use XPath notation to identify the location of a tag in the event that more than one tag of the same name is present in the document. Alternatively, the tag name alone can be used to identify missing data [Type=ReqFieldMissing]. */
    tag?: string;
    /** @description If present, this attribute allows for batch processing and the identification of the record that failed amongst a group of records. This value may contain a concatenation of a unique failed transaction ID with specific record(s) associated with that transaction. */
    recordId?: string;
    /** @description The Warning element MUST contain the Type attribute that uses a recommended set of values to indicate the warning type. The validating XSD can expect to accept values that it has NOT been explicitly coded for and process them by using Type ="Unknown". */
    type?: string;
    /** @description Language identification. */
    language?: string;
    /** @description Reference Place Holder used as an index for this warning. */
    rph?: string;
  };
  stayDailyRatesType: {
    /**
     * Format: date
     * @description Date on which the transaction was done.
     */
    transactionDate: string;
    /** @description Specifies the type of room booked. */
    bookedRoomType?: string;
    /** @description Specifies the code assigned to the currency. */
    currencyCode?: string;
    /** @description Specifies if the room is a pseudo room. */
    pseudoRoom?: boolean;
    /** @description Specifies the market code. */
    marketCode?: string;
    /** @description Specifies the rate code. */
    rateCode: string;
    /** @description Specifies the amount added to a particular rate code. */
    rateAmount?: number;
    /** @description Describes the number assigned to a room. */
    roomNumber?: string;
    /** @description Describes the type of the room. */
    roomType?: string;
  };
  stayMembershipsType: {
    /** @description A unique value given to a membership. */
    membershipNumber?: string;
    /** @description Specifies the type of membership. */
    membershipType?: string;
  };
  stayProfilesType: {
    /** @description Checks if the profile is primary. */
    primary?: boolean;
    /** @description Specifies the unique id that is assigned to a profile. */
    nameId?: number;
    /** @description Specifies the pms id that is assigned to a profile. */
    pmsNameId?: string;
    /** @description Describes the role associated with the profile. */
    profileRole: string;
  };
  stayRecordsType: {
    /** @description Describes the user defined field 01 */
    UDFC01?: string;
    /** @description Describes the user defined field 02 */
    UDFC02?: string;
    /** @description Describes the user defined field 03 */
    UDFC03?: string;
    /** @description Describes the user defined field 04 */
    UDFC04?: string;
    /** @description Describes the user defined field 05 */
    UDFC05?: string;
    /** @description Describes the user defined field 06 */
    UDFC06?: string;
    /** @description Describes the user defined field 07 */
    UDFC07?: string;
    /** @description Describes the user defined field 08 */
    UDFC08?: string;
    /** @description Describes the user defined field 09 */
    UDFC09?: string;
    /** @description Describes the user defined field 10 */
    UDFC10?: string;
    /**
     * Format: date
     * @description Describes the user defined field 01
     */
    UDFD01?: string;
    /**
     * Format: date
     * @description Describes the user defined field 02
     */
    UDFD02?: string;
    /**
     * Format: date
     * @description Describes the user defined field 03
     */
    UDFD03?: string;
    /**
     * Format: date
     * @description Describes the user defined field 04
     */
    UDFD04?: string;
    /**
     * Format: date
     * @description Describes the user defined field 05
     */
    UDFD05?: string;
    /** @description Describes the user defined field 10 */
    UDFN01?: number;
    /** @description Describes the user defined field 10 */
    UDFN02?: number;
    /** @description Describes the user defined field 10 */
    UDFN03?: number;
    /** @description Describes the user defined field 10 */
    UDFN04?: number;
    /** @description Describes the user defined field 10 */
    UDFN05?: number;
    /** @description Describes the number of adults */
    adults?: number;
    /**
     * Format: date
     * @description Specifies the date of arrival
     */
    arrivalDate?: string;
    /** @description Specifies the base rate amount */
    baseRateAmount?: number;
    /** @description Specifies the base rate code */
    baseRateCode?: string;
    /** @description Specifies the currency code of the base rate */
    baseRateCurrencyCode?: string;
    /** @description Specifies the block code */
    blockCode?: string;
    /** @description Specifies the type of room booked. */
    bookedRoomType?: string;
    /**
     * Format: date
     * @description Specifies the date of booking.
     */
    bookingDate?: string;
    /**
     * Format: date
     * @description Specifies the date of cancellation
     */
    cancellationDate?: string;
    /** @description Specifies the channel */
    channel?: string;
    /** @description specifies the number of children */
    children?: number;
    /** @description Specifies the id assigned to the company */
    companyId?: string;
    /** @description Specifies the confirmation leg number */
    confirmationLegNumber?: number;
    /** @description Specifies the confirmation number. If externalReservationId is not passed as part of POST stayRecords API then length of confirmation number should be less than 43 digits */
    confirmationNumber?: string;
    /** @description Specifies the currency code */
    currencyCode?: string;
    /**
     * Format: date
     * @description Specifies the date of departure
     */
    departureDate?: string;
    /** @description Specifies the exchange rate */
    exhangeRate?: number;
    /** @description Describes the id assigned to an external reservation */
    externalReservationId?: string;
    /** @description Specifies the id assigned to a group */
    groupId?: string;
    /** @description Specifies the id assigned to a guest name */
    guestNameId?: string;
    /** @description Specifies the code assigned to a property */
    hotelCode?: string;
    /** @description Describes if complimentary or not */
    complimentary?: boolean;
    /** @description Describes if it is a primary share */
    primaryShare?: boolean;
    /** @description Specifies the miscellaneous id */
    miscellaneousId?: string;
    /** @description Specifies the payment method used */
    paymentMethod?: string;
    /** @description Specifies the postal code */
    posCode?: string;
    /** @description Specifies the promotion code */
    promotionCode?: string;
    /** @description Describes the reservation status ie CANCELLED, CHECKED OUT, ARRIVAL etc */
    reservationStatus?: string;
    /**
     * Format: date
     * @description Specifies the expected arrival time of the reservation
     */
    reservationExpectedArrivalTime?: string;
    /**
     * Format: date
     * @description Specifies the expected departure time of the reservation
     */
    reservationExpectedDepartureTime?: string;
    /** @description Specifies the insert source for the reservation */
    reservationInsertSource?: string;
    /** @description Specifies the insert source type for the reservation */
    reservationInsertSourceType?: string;
    /** @description Describes the number assigned to a room. */
    roomNumber?: string;
    /** @description Specifies the revenue for the room. */
    roomRevenue?: number;
    /** @description Describes the type of the room. */
    roomType?: string;
    /** @description Specifies the share id. */
    shareId?: string;
    /** @description Specifies the source code. */
    sourceCode?: string;
    /** @description Specifies the source id. */
    sourceId?: string;
    /** @description Specifies the stage status. */
    stageStatus?: string;
    /** @description Specifies the stage suspense reason. */
    stageSuspenseReason?: string;
    /** @description Specifies the total revenue. */
    totalRevenue?: number;
    /** @description Specifies the travel agent id */
    travelAgentId?: string;
  };
  stayRevenuesDetailsType: {
    folioView?: string;
    /** @description Specifies the amount of revenue. */
    revenueAmount?: number;
    stayRevenues?: definitions["stayRevenuesType"][];
  };
  stayRevenuesType: {
    /** @description Specifies the amount of revenue. */
    revenueAmount?: number;
    /** @description Specifies the bucket code to which the revenue belongs. */
    revenueBucketCode: string;
    /**
     * Format: date
     * @description Date on which the transaction was done.
     */
    transactionDate: string;
  };
  stayRecord: {
    /** @description Specifies the property name */
    resort?: string;
    stayDailyRates?: definitions["stayDailyRatesType"][];
    stayMemberships?: definitions["stayMembershipsType"][];
    stayProfiles?: definitions["stayProfilesType"][];
    stayRecordsList?: definitions["stayRecordsType"][];
    stayRevenuesDetails?: definitions["stayRevenuesDetailsType"][];
  };
  /** @description Complex type that contains list of stay record types */
  stayRecords: {
    /** @description Array list of stay records */
    stayRecords?: definitions["stayRecord"][];
  };
  /** @description Used in conjunction with the Success element to define a business error. */
  warningsType: definitions["warningType"][];
  /** @description Response for stay record uploaded status. */
  stayRecordStatus: {
    /** @description List of warnings that occurred. */
    warnings?: definitions["warningsType"];
    links?: definitions["links"];
  };
}

export interface parameters {
  /** @description Pass this header as true, if payload needs DVM */
  externalData: string;
  /** @description Bearer token that needs to be passed which is generated post user authentication */
  authKey: string;
  /** @description Client or PartnerAC/AAs Application Key */
  "x-app-key": string;
  /** @description Request Id of an incoming request */
  "x-request-id": string;
  /** @description Customer's Integration Application Id */
  "x-originating-application": string;
  /** @description Mandatory parameter to identify the hotel code where the end user is logged in */
  "x-hotelid": string;
  /** @description Language code */
  "Accept-Language": string;
}

export interface responses {
  /** Bad Request */
  400: {
    schema: definitions["exceptionDetailType"];
  };
  /** Unauthorized */
  401: unknown;
  /** Forbidden */
  403: unknown;
  /** Resource not found */
  404: {
    schema: definitions["exceptionDetailType"];
  };
  /** Method not allowed */
  405: unknown;
  /** Not acceptable. */
  406: unknown;
  /** Request Entity Too Large */
  413: unknown;
  /** Request URI Too Large */
  414: unknown;
  /** Unsupported Media Type */
  415: unknown;
  /** System Error */
  500: {
    schema: definitions["exceptionDetailType"];
  };
  /** Bad Gateway */
  502: unknown;
  /** Service Unavailable */
  503: unknown;
}

export interface operations {
  /** A user can upload various stay records to OPERA by specifying stay record column details in the request.<p><strong>OperationId:</strong>stayRecords</p> */
  stayRecords: {
    parameters: {
      body: {
        /** Request object for uploading stage records to LCS asynchronously. */
        criteria: definitions["stayRecords"];
      };
      header: {
        /** Bearer token that needs to be passed which is generated post user authentication */
        authorization: parameters["authKey"];
        /** Pass this header as true, if payload needs DVM */
        externalData?: parameters["externalData"];
        /** Client or PartnerAC/AAs Application Key */
        "x-app-key": parameters["x-app-key"];
        /** Request Id of an incoming request */
        "x-request-id"?: parameters["x-request-id"];
        /** Customer's Integration Application Id */
        "x-originating-application"?: parameters["x-originating-application"];
        /** Mandatory parameter to identify the hotel code where the end user is logged in */
        "x-hotelid": parameters["x-hotelid"];
        /** Language code */
        "Accept-Language"?: parameters["Accept-Language"];
      };
    };
    responses: {
      /** HATEOAS links which help the consumer to navigate to resources */
      202: {
        headers: {};
        schema: definitions["links"];
      };
      400: responses["400"];
      401: responses["401"];
      403: responses["403"];
      404: responses["404"];
      405: responses["405"];
      406: responses["406"];
      413: responses["413"];
      414: responses["414"];
      415: responses["415"];
      500: responses["500"];
      502: responses["502"];
      503: responses["503"];
    };
  };
  /** Use this to check whether the request sent have been processed. <p><strong>OperationId:</strong>getStayRecordsProcess</p> */
  getStayRecordsProcess: {
    parameters: {
      path: {
        requestId: string;
      };
      header: {
        /** Bearer token that needs to be passed which is generated post user authentication */
        authorization: parameters["authKey"];
        /** Pass this header as true, if payload needs DVM */
        externalData?: parameters["externalData"];
        /** Client or PartnerAC/AAs Application Key */
        "x-app-key": parameters["x-app-key"];
        /** Request Id of an incoming request */
        "x-request-id"?: parameters["x-request-id"];
        /** Customer's Integration Application Id */
        "x-originating-application"?: parameters["x-originating-application"];
        /** Mandatory parameter to identify the hotel code where the end user is logged in */
        "x-hotelid": parameters["x-hotelid"];
        /** Language code */
        "Accept-Language"?: parameters["Accept-Language"];
      };
    };
    responses: {
      /** Response for stay records uploaded */
      200: {
        headers: {};
        schema: definitions["stayRecordStatus"];
      };
      /** Stay Record not found. */
      204: never;
      400: responses["400"];
      401: responses["401"];
      403: responses["403"];
      404: responses["404"];
      405: responses["405"];
      406: responses["406"];
      413: responses["413"];
      414: responses["414"];
      415: responses["415"];
      500: responses["500"];
      502: responses["502"];
      503: responses["503"];
    };
  };
  /** Use this to check whether the request sent have been processed. <p><strong>OperationId:</strong>getStayRecordsProcessStatus</p> */
  getStayRecordsProcessStatus: {
    parameters: {
      path: {
        requestId: string;
      };
      header: {
        /** Bearer token that needs to be passed which is generated post user authentication */
        authorization: parameters["authKey"];
        /** Pass this header as true, if payload needs DVM */
        externalData?: parameters["externalData"];
        /** Client or PartnerAC/AAs Application Key */
        "x-app-key": parameters["x-app-key"];
        /** Request Id of an incoming request */
        "x-request-id"?: parameters["x-request-id"];
        /** Customer's Integration Application Id */
        "x-originating-application"?: parameters["x-originating-application"];
        /** Mandatory parameter to identify the hotel code where the end user is logged in */
        "x-hotelid": parameters["x-hotelid"];
        /** Language code */
        "Accept-Language"?: parameters["Accept-Language"];
      };
    };
    responses: {
      /** Response for status of scheduled asynchronous process. */
      200: unknown;
      /** Response for status of scheduled asynchronous process. */
      201: unknown;
      400: responses["400"];
      401: responses["401"];
      403: responses["403"];
      404: responses["404"];
      405: responses["405"];
      406: responses["406"];
      413: responses["413"];
      414: responses["414"];
      415: responses["415"];
      500: responses["500"];
      502: responses["502"];
      503: responses["503"];
    };
  };
}

export interface external {}
