/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/externalSystems/{extSystemCode}/hotels/{externalHotelId}/conversions": {
    /** This API allows you to get the converted hotel code <p><strong>OperationId:</strong>getOperaHotelCode</p> */
    get: operations["getOperaHotelCode"];
  };
  "/externalSystems/{extSystemCode}/hotels/{operaHotelId}/convertedValues": {
    /** This API allows you to get the converted values <p><strong>OperationId:</strong>getConvertedValues</p> */
    get: operations["getConvertedValues"];
  };
  "/externalSystems/{extSystemCode}/hotels/{operaHotelId}/defaultValues": {
    /** This API allows you to get default values <p><strong>OperationId:</strong>getDefaultValues</p> */
    get: operations["getDefaultValues"];
  };
  "/externalSystems/{externalSystem}/conversionCodes": {
    /** API to fetch Data Value Mapping Conversion Codes for a given external system. Filters include optional hotelId and group (XML Type).<p><strong>OperationId:</strong>getDvmConversionCodes</p> */
    get: operations["getDvmConversionCodes"];
  };
  "/externalSystems/{externalSystem}/conversionCodes/{conversionCode}/dataValueMappings": {
    /** Retrieve mappings for a specific conversion code configured for external system, hotelId and Global mappings.<p><strong>OperationId:</strong>getDataValueMappings</p> */
    get: operations["getDataValueMappings"];
    /** API to update existing Data Value Mapping (DVM) Conversion Code records for a given External System and Conversion Code. <p><strong>OperationId:</strong>putDataValueMappings</p> */
    put: operations["putDataValueMappings"];
    /** API to create Data Value Mapping (DVM) Conversion Codes by External System and Conversion Code. <p><strong>OperationId:</strong>postDataValueMappings</p> */
    post: operations["postDataValueMappings"];
    /** API to Delete Interface Mapping Conversion Codes by providing one or more Mapping IDs as query parameter. <p><strong>OperationId:</strong>deleteDataValueMappings</p> */
    delete: operations["deleteDataValueMappings"];
  };
  "/services/datavaluemapping/defaultValueCache": {
    /** This API allows you to delete the default values cache <p><strong>OperationId:</strong>clearDefaultValueCache</p> */
    delete: operations["clearDefaultValueCache"];
  };
  "/services/datavaluemapping/status": {
    /** ping Data Value Mapping Service <p><strong>OperationId:</strong>pingDataValueMappingService</p> */
    get: operations["pingDataValueMappingService"];
  };
}

export interface definitions {
  convertedHotelCode: {
    /** @description ExternalSystem for which the conversion is needed. */
    externalSystem?: string;
    /** @description Converted hotel information. */
    hotelInfo?: definitions["conversionHotelInfoType"];
    links?: definitions["links"];
    warnings?: definitions["warningsType"];
  };
  /** @description Generic information of the resort , external resort and external system. */
  conversionHotelInfoType: {
    /** @description Opera Resort for which conversion is needed. */
    operaHotelCode?: string;
    /** @description External value of resort for which conversion is needed. */
    externalHotelCode?: string;
  };
  links: definitions["instanceLink"][];
  /** @description Metadata describing link description objects that MAY appear in the JSON instance representation. */
  instanceLink: {
    /** @description URI [RFC3986] or URI Template [RFC6570]. If the value is set to URI Template, then the "templated" property must be set to true. */
    href?: string;
    /** @description Name of the link relation that, in addition to the type property, can be used to retrieve link details. For example, href or profile. */
    rel?: string;
    /**
     * @description Boolean flag that specifies that "href" property is a URI or URI Template. If the property is a URI template, set this value to true. By default, this value is false.
     * @default false
     */
    templated?: boolean;
    /**
     * @description HTTP method for requesting the target of the link.
     * @enum {string}
     */
    method?: "GET" | "POST" | "PUT" | "DELETE" | "PATCH" | "OPTIONS" | "HEAD";
    /** @description Link to the metadata of the resource, such as JSON-schema, that describes the resource expected when dereferencing the target resource.. */
    targetSchema?: string;
    /** @description The operationId of the path you can call to follow this link.  This allows you to look up not only the path and method, but the description of that path and any parameters you need to supply. */
    operationId?: string;
    /** @description Exact copy of the "summary" field on the linked operation. */
    title?: string;
  };
  /** @description Used in conjunction with the Success element to define a business error. */
  warningsType: definitions["warningType"][];
  /** @description Used when a message has been successfully processed to report any warnings or business errors that occurred. */
  warningType: {
    /** @description Property Value */
    value?: string;
    /** @description An abbreviated version of the error in textual format. */
    shortText?: string;
    /** @description If present, this refers to a table of coded values exchanged between applications to identify errors or warnings. */
    code?: string;
    /** @description If present, this URL refers to an online description of the error that occurred. */
    docURL?: string;
    /** @description If present, recommended values are those enumerated in the ErrorRS, (NotProcessed Incomplete Complete Unknown) however, the data type is designated as string data, recognizing that trading partners may identify additional status conditions not included in the enumeration. */
    status?: string;
    /** @description If present, this attribute may identify an unknown or misspelled tag that caused an error in processing. It is recommended that the Tag attribute use XPath notation to identify the location of a tag in the event that more than one tag of the same name is present in the document. Alternatively, the tag name alone can be used to identify missing data [Type=ReqFieldMissing]. */
    tag?: string;
    /** @description If present, this attribute allows for batch processing and the identification of the record that failed amongst a group of records. This value may contain a concatenation of a unique failed transaction ID with specific record(s) associated with that transaction. */
    recordId?: string;
    /** @description The Warning element MUST contain the Type attribute that uses a recommended set of values to indicate the warning type. The validating XSD can expect to accept values that it has NOT been explicitly coded for and process them by using Type ="Unknown". */
    type?: string;
    /** @description Language identification. */
    language?: string;
    /** @description Reference Place Holder used as an index for this warning. */
    rph?: string;
  };
  /**
   * Error Detail
   * @description Complex type that contains error details for a REST call.
   */
  exceptionDetailType: {
    /** @description Absolute URI [RFC3986] that identifies the problem type.  When dereferenced, it SHOULD provide a human-readable summary of the problem (for example, using HTML). */
    type: string;
    /** @description Short, human-readable summary of the problem.  The summary SHOULD NOT change for subsequent occurrences of the problem, except for purposes of localization. */
    title: string;
    /** @description HTTP status code for this occurrence of the problem, set by the origin server. */
    status?: number;
    /** @description Human-readable description specific to this occurrence of the problem. */
    detail?: string;
    /** @description Absolute URI that identifies the specific occurrence of the problem.  It may or may not provide additional information if dereferenced. */
    instance?: string;
    /** @description Application error code, which is different from HTTP error code. */
    "o:errorCode"?: string;
    /** @description Path to the problem at the resource or property level. */
    "o:errorPath"?: string;
    /** @description Details of the error message, consisting of a hierarchical tree structure. */
    "o:errorDetails"?: definitions["errorInstance"][];
    links?: definitions["links"];
  };
  /**
   * Error Instance Details
   * @description Complex type that contains error instance details for a REST call.
   */
  errorInstance: {
    /** @description Absolute URI [RFC3986] that identifies the problem type.  When dereferenced, it SHOULD provide a human-readable summary of the problem (for example, using HTML). */
    type: string;
    /** @description Short, human-readable summary of the problem.  The summary SHOULD NOT change for subsequent occurrences of the problem, except for purposes of localization. */
    title: string;
    /** @description HTTP status code for this occurrence of the problem, set by the origin server. */
    status?: number;
    /** @description Human-readable description specific to this occurrence of the problem. */
    detail?: string;
    /** @description Absolute URI that identifies the specific occurrence of the problem.  It may or may not provide additional information if dereferenced. */
    instance?: string;
    /** @description Application error code, which is different from HTTP error code. */
    "o:errorCode"?: string;
    /** @description Path to the problem at the resource or property level. */
    "o:errorPath"?: string;
  };
  convertedValues: {
    /** @description ExternalSystem for which the conversion is needed. */
    externalSystem?: string;
    /** @description Converted hotel information. */
    hotelInfo?: definitions["conversionHotelInfoType"];
    /** @description List all the converted values fetched for an interface, resort. */
    convertedValues?: definitions["convertedValuesType"];
    links?: definitions["links"];
    warnings?: definitions["warningsType"];
  };
  /** @description A collection of converted values. */
  convertedValuesType: definitions["convertedValueType"][];
  /** @description Details of the converted value. */
  convertedValueType: {
    /** @description Opera Value */
    operaValue?: string;
    /** @description Value used by the external vendors. */
    externalValue?: string;
    /** @description Enumeration of conversion codes. */
    conversionCode?: definitions["dataValueMappingCodeType"];
    /** @description Opera Master Value */
    masterValue?: string;
    /** @description The flag will be true for all the conversions that are pms defaults. In case there are more than one conversions available in opera. */
    pmsDefaultConversion?: boolean;
    /** @description The flag will be true for all the conversions that are crs defaults. In case there are more than one conversions available in opera. */
    crsDefaultConversion?: boolean;
  };
  /**
   * @description Enumeration of the different conversion codes needed for data value mapping.
   * @enum {string}
   */
  dataValueMappingCodeType:
    | "AccountType"
    | "ActionCode"
    | "ActionType"
    | "ActivityLocation"
    | "ActivityStatus"
    | "ActivityType"
    | "ActivityTypeSc"
    | "AddressTypes"
    | "ArrangementCode"
    | "BlockCancellationCodes"
    | "BlockCodes"
    | "BlockConversion"
    | "BlockRanking"
    | "BlockRateOverrideReason"
    | "BookingStatus"
    | "BookingType"
    | "BusiinessSegment"
    | "CalendarEvent"
    | "CancellationCodes"
    | "CategoryCode"
    | "CatItemrate"
    | "CatRate"
    | "CatServing"
    | "CatSetup"
    | "ChannelCodes"
    | "ComboRoom"
    | "CommentType"
    | "CompetitionCode"
    | "CountryCode"
    | "CurrencyCode"
    | "DayType"
    | "DepartmentId"
    | "DeptNoteCode"
    | "DiscountReason"
    | "DocumentType"
    | "EventType"
    | "FitContractType"
    | "Frequency"
    | "FunctionSpaceLocation"
    | "FunctionSpaceRateType"
    | "GenderMf"
    | "GtdReq"
    | "GuestPreferenceCode"
    | "GuestPreferenceType"
    | "IndustryCode"
    | "InfluenceCode"
    | "LanguageCodes"
    | "MarketingCity"
    | "MarketingRegion"
    | "MarketCode"
    | "MeetingRoomtype"
    | "MembershipLevel"
    | "MembershipType"
    | "MembershipTypeAirline"
    | "Nationality"
    | "OcrmBounceType"
    | "OcrmEventType"
    | "OtaGuestPreferenceCode"
    | "PaymentMethod"
    | "PhoneType"
    | "PosFamilyGroup"
    | "PosMajorGroup"
    | "PosMenuDef"
    | "PosRevenueCenter"
    | "PriceCode"
    | "ProductCode"
    | "ProfilePriority"
    | "ProfileSource"
    | "ProfileType"
    | "RateCategory"
    | "RateCode"
    | "RateProgram"
    | "RateToRateBlock"
    | "RateType"
    | "ReasonCode"
    | "Relationship"
    | "ReservationStatus"
    | "ReservationType"
    | "ResvBookingMethod"
    | "RevenueGroups"
    | "RevenueType"
    | "Room"
    | "RoomsPotential"
    | "RoomCategoryLabel"
    | "RoomClass"
    | "RoomPool"
    | "RoomRepairsReasonCode"
    | "RoomStatusReasons"
    | "RoutingCode"
    | "Scope"
    | "ScopeCity"
    | "ScAccPriority"
    | "ScAccRoomsPot"
    | "ScAccSource"
    | "ScDestination"
    | "ScFunctionSpace"
    | "ScFunctionSpaceRateCode"
    | "ScFunctionSpaceSetup"
    | "ScRevenueTypes"
    | "ScSetupCode"
    | "ScTaskCode"
    | "ScTerritory"
    | "ServiceRequestType"
    | "SgiLanguage"
    | "SgiRequestCodes"
    | "SgiTitle"
    | "SourceCode"
    | "State"
    | "Title"
    | "TraceCode"
    | "TraceDepartment"
    | "TransportTypes"
    | "TravelAgentCommissionCodes"
    | "TravelAgentCurrencyCodes"
    | "Trxgenerates"
    | "TrxCode"
    | "VipLevel"
    | "WaitlistCodes"
    | "WebuserSecurityQuestion";
  defaultValues: {
    /** @description List all the Opera and External default values fetched for an interface, resort. */
    defaultValues?: definitions["defaultValuesType"];
    links?: definitions["links"];
    warnings?: definitions["warningsType"];
  };
  /** @description A collection of default values. */
  defaultValuesType: definitions["defaultValueType"][];
  /** @description Details of the default value fetched for an interface and resort. */
  defaultValueType: {
    /** @description Opera Value */
    operaDefault?: string;
    /** @description Value used by the external vendors. */
    externalDefault?: string;
    /** @description This element states the type of Default value. For example if the operaDefault and external default is Market code's default then the value will be MarketCode. */
    defaultValueType?: definitions["defaultValueCodeType"];
  };
  /**
   * @description Enumeration of the different default codes.
   * @enum {string}
   */
  defaultValueCodeType:
    | "AddressTypes"
    | "AvailabilityType"
    | "BlockCancellationCodes"
    | "BlockChannelCode"
    | "BlockMarketCode"
    | "BlockOwner"
    | "BlockRateCode"
    | "BlockReservationType"
    | "BlockSourceCode"
    | "BlockStatus"
    | "BlockType"
    | "CancellationCodes"
    | "CashierId"
    | "CountryCode"
    | "ChannelCodes"
    | "ConfLetterId"
    | "ConfLetterName"
    | "CrsCurrencyCode"
    | "CrsCurrencyFmtDisplay"
    | "CrsCurrencyFormat"
    | "CrsCurrencyMultiplier"
    | "CurrencyCode"
    | "Custom1"
    | "Custom2"
    | "DeleteCharInd"
    | "DeleteDateInd"
    | "DeleteNumberInd"
    | "DepositPaymentMethod"
    | "DeptCodes"
    | "DiscountReason"
    | "GuestPreferences"
    | "HighPrioMemTypes"
    | "KeepingCharInd"
    | "KeepingDateInd"
    | "KeepingNumberInd"
    | "LanguageCodes"
    | "MarketCode"
    | "MaxAvailInAdvance"
    | "PaymentMethod"
    | "PhoneType"
    | "RateCategory"
    | "RateClass"
    | "RateCode"
    | "RateDisplaySet"
    | "ReservationType"
    | "RoomCategoryLabel"
    | "ScDestination"
    | "SourceCode"
    | "StartDayOfWeek"
    | "TaCompanyOwner"
    | "Trace1"
    | "Trace2"
    | "TraceArrivalDept1"
    | "TraceArrivalDept2"
    | "TraceOverrideDept1"
    | "TraceOverrideDept2"
    | "TraceOverrideWarning"
    | "TraceWarning"
    | "TravelAgentCommissionCodes"
    | "TravelAgentCurrencyCodes"
    | "TravelAgentCurrencyCodesCentral"
    | "VipLevel"
    | "WaitlistCodes"
    | "ProfileNoteType"
    | "BlockNoteType";
  /** @description Response Body. */
  status: {
    warnings?: definitions["warningsType"];
    links?: definitions["links"];
  };
  /** @description Response for Ping operation. */
  operaVersion: {
    /** @description Current Opera Version Number */
    operaVersion?: string;
    links?: definitions["links"];
    warnings?: definitions["warningsType"];
  };
  fetchDvmConversionCodes: {
    /** @description List of conversion codes for the given filters. */
    conversionCodes?: definitions["dvmConversionCodeType"][];
    links?: definitions["links"];
    warnings?: definitions["warningsType"];
  };
  dvmConversionCodeType: {
    /** @description Type of conversion code. */
    conversionCode?: string;
    /** @description Label of the conversion code. */
    label?: string;
    /** @description Description of the conversion code. */
    description?: string;
    /** @description Group or XML Type the conversion code belongs to. */
    group?: string;
    /** @description Associated hotel Id if applicable. */
    hotelId?: string;
  };
  fetchDvmMappings: {
    /** @description List of value mappings. */
    conversionCodeMappings?: definitions["dvmMappingType"][];
    links?: definitions["links"];
  };
  dvmMappingType: {
    /** @description Unique ID of the conversion code in  OPERA. */
    id?: number;
    /** @description Indicates OPERA value. */
    operaValue?: string;
    /** @description External system's mapped value. */
    externalValue?: string;
    /** @description Description of the external value mapping. */
    description?: string;
    /** @description Hotel code if the mappings are property-specific. */
    hotelId?: string;
    /** @description Flag to indicate whether the mapping is global. */
    isGlobal?: boolean;
    /** @description Flag indicating this mapping is default from OPERA to external system. */
    operaToExternalDefault?: boolean;
    /** @description Flag indicating this mapping is default from external system to OPERA. */
    externalToOperaDefault?: boolean;
  };
  dvmConversionCodeMappingsToBeCreated: {
    /** @description Conversion Code Mapping details that should be created. */
    conversionCodeMappings?: definitions["dvmConversionCodeMappingType"][];
    links?: definitions["links"];
    warnings?: definitions["warningsType"];
  };
  /** @description A type containing DVM Conversion Code Mapping information. */
  dvmConversionCodeMappingType: {
    /** @description Mapping identifier for tracking. */
    id?: string;
    /** @description Internal OPERA value to be mapped. */
    operaValue?: string;
    /** @description External system value to be mapped. */
    externalValue?: string;
    /** @description Description for the external value. */
    description?: string;
    /** @description Flag indicating if the mapping is default from OPERA to External. */
    operaToExternalDefault?: boolean;
    /** @description Flag indicating if the mapping is default from External to OPERA. */
    externalToOperaDefault?: boolean;
    /** @description Flag to indicate whether the mapping is global. */
    isGlobal?: boolean;
    /** @description Hotel Id for which this mapping applies. */
    hotelId?: string;
    /** @description A flag to indicate whether the current External Value should be considered as default, when there is already a default External Value mapped for the same OPERA Value. */
    overrideExternalDefault?: boolean;
    /** @description A flag to indicate whether the current OPERA Value should be considered as default, when there is already a default OPERA Value mapped for the same External Value. */
    overrideOperaDefault?: boolean;
  };
  createdDvmConversionCodeMappings: {
    /** @description List of successfully created Conversion Codes with the request Id and OPERA Id. */
    conversionCodesCreated?: definitions["ConversionCodeCreatedType"][];
    /** @description List of Conversion Codes failed to create in OPERA System. */
    conversionCodesFailed?: definitions["ConversionCodeFailedType"][];
    warnings?: definitions["warningsType"];
    links?: definitions["links"];
  };
  /** @description Request object for updating DVM Conversion Code Mappings. */
  dvmConversionCodeMappingsToBeUpdated: {
    /** @description DVM Conversion Code Mapping details that should be updated. */
    conversionCodeMappings?: definitions["dvmConversionCodeMappingType"][];
    links?: definitions["links"];
    warnings?: definitions["warningsType"];
  };
  updatedDvmConversionCodeMappings: {
    /** @description List of successfully updated Conversion Codes Mapping Id's. */
    conversionCodesUpdated?: number[];
    /** @description List of Conversion Code Mappings that failed to update with reasons. */
    conversionCodeFailed?: definitions["ConversionCodeFailedType"][];
    links?: definitions["links"];
    warnings?: definitions["warningsType"];
  };
  /** @description Response for delete operation on DVM mappings. */
  deleteDvmMappingResponse: {
    /** @description List of successfully deleted mapping Id's */
    conversionCodesDeleted?: number[];
    /** @description List of failed deletions with reasons */
    conversionCodesDeleteFailed?: definitions["ConversionCodeFailedType"][];
  };
  ConversionCodeCreatedType: {
    /** @description Id value sent in Request object. */
    id?: number;
    /** @description Conversion Code Id in OPERA System. */
    operaId?: number;
  };
  ConversionCodeFailedType: {
    /** @description Id of the failed Conversion Code Mapping from the request */
    id?: number;
    /** @description Reason for the Conversion Code Mapping failure. */
    reason?: string;
  };
}

export interface parameters {
  /** @description Pass this header as true, if payload needs DVM */
  externalData: string;
  /** @description Bearer token that needs to be passed which is generated post user authentication */
  authKey: string;
  /** @description Client or Partner's Application Key */
  "x-app-key": string;
  /** @description Request Id of an incoming request */
  "x-request-id": string;
  /** @description Customer's Integration Application Id */
  "x-originating-application": string;
  /** @description Mandatory parameter to identify the hotel code where the end user is logged in */
  "x-hotelid": string;
  /** @description External system code. */
  "x-externalsystem": string;
  /** @description Language code */
  "Accept-Language": string;
  /** @description x-hubid is a logical grouping of multiple properties that allows api consumers to manage data from a group of properties. This x-hubid is a valid list of hub codes configured in OPERA to which the user has access. Rest APIs without hotelId in the operation path can support hub level integration using x-hubid */
  "x-hubid": string;
}

export interface responses {
  /** Bad Request */
  400: {
    schema: definitions["exceptionDetailType"];
  };
  /** Unauthorized */
  401: unknown;
  /** Forbidden */
  403: unknown;
  /** Resource not found */
  404: {
    schema: definitions["exceptionDetailType"];
  };
  /** Method not allowed */
  405: unknown;
  /** Not acceptable. */
  406: unknown;
  /** Request Entity Too Large */
  413: unknown;
  /** Request URI Too Large */
  414: unknown;
  /** Unsupported Media Type */
  415: unknown;
  /** System Error */
  500: {
    schema: definitions["exceptionDetailType"];
  };
  /** Bad Gateway */
  502: unknown;
  /** Service Unavailable */
  503: unknown;
}

export interface operations {
  /** This API allows you to get the converted hotel code <p><strong>OperationId:</strong>getOperaHotelCode</p> */
  getOperaHotelCode: {
    parameters: {
      path: {
        externalHotelId: string;
        extSystemCode: string;
      };
      query: {
        /** Opera Resort for which conversion is needed. */
        operaHotelCode?: string;
      };
      header: {
        /** Bearer token that needs to be passed which is generated post user authentication */
        authorization: parameters["authKey"];
        /** Pass this header as true, if payload needs DVM */
        externalData?: parameters["externalData"];
        /** Client or Partner's Application Key */
        "x-app-key": parameters["x-app-key"];
        /** Request Id of an incoming request */
        "x-request-id"?: parameters["x-request-id"];
        /** Customer's Integration Application Id */
        "x-originating-application"?: parameters["x-originating-application"];
        /** Mandatory parameter to identify the hotel code where the end user is logged in */
        "x-hotelid": parameters["x-hotelid"];
        /** External system code. */
        "x-externalsystem"?: parameters["x-externalsystem"];
        /** Language code */
        "Accept-Language"?: parameters["Accept-Language"];
      };
    };
    responses: {
      /** Response to fetch the opera resort for an interface and given the external resort value or vice versa. */
      200: {
        headers: {};
        schema: definitions["convertedHotelCode"];
      };
      /** OperaHotelCode not found. */
      204: never;
      400: responses["400"];
      401: responses["401"];
      403: responses["403"];
      404: responses["404"];
      405: responses["405"];
      406: responses["406"];
      413: responses["413"];
      414: responses["414"];
      415: responses["415"];
      500: responses["500"];
      502: responses["502"];
      503: responses["503"];
    };
  };
  /** This API allows you to get the converted values <p><strong>OperationId:</strong>getConvertedValues</p> */
  getConvertedValues: {
    parameters: {
      path: {
        operaHotelId: string;
        extSystemCode: string;
      };
      query: {
        /** External value of resort for which conversion is needed. */
        externalHotelId?: string;
        /** Enumeration of the different conversion codes needed for data value mapping. */
        conversionCode?: (
          | "AccountType"
          | "ActionCode"
          | "ActionType"
          | "ActivityLocation"
          | "ActivityStatus"
          | "ActivityType"
          | "ActivityTypeSc"
          | "AddressTypes"
          | "ArrangementCode"
          | "BlockCancellationCodes"
          | "BlockCodes"
          | "BlockConversion"
          | "BlockRanking"
          | "BlockRateOverrideReason"
          | "BookingStatus"
          | "BookingType"
          | "BusiinessSegment"
          | "CalendarEvent"
          | "CancellationCodes"
          | "CategoryCode"
          | "CatItemrate"
          | "CatRate"
          | "CatServing"
          | "CatSetup"
          | "ChannelCodes"
          | "ComboRoom"
          | "CommentType"
          | "CompetitionCode"
          | "CountryCode"
          | "CurrencyCode"
          | "DayType"
          | "DepartmentId"
          | "DeptNoteCode"
          | "DiscountReason"
          | "DocumentType"
          | "EventType"
          | "FitContractType"
          | "Frequency"
          | "FunctionSpaceLocation"
          | "FunctionSpaceRateType"
          | "GenderMf"
          | "GtdReq"
          | "GuestPreferenceCode"
          | "GuestPreferenceType"
          | "IndustryCode"
          | "InfluenceCode"
          | "LanguageCodes"
          | "MarketingCity"
          | "MarketingRegion"
          | "MarketCode"
          | "MeetingRoomtype"
          | "MembershipLevel"
          | "MembershipType"
          | "MembershipTypeAirline"
          | "Nationality"
          | "OcrmBounceType"
          | "OcrmEventType"
          | "OtaGuestPreferenceCode"
          | "PaymentMethod"
          | "PhoneType"
          | "PosFamilyGroup"
          | "PosMajorGroup"
          | "PosMenuDef"
          | "PosRevenueCenter"
          | "PriceCode"
          | "ProductCode"
          | "ProfilePriority"
          | "ProfileSource"
          | "ProfileType"
          | "RateCategory"
          | "RateCode"
          | "RateProgram"
          | "RateToRateBlock"
          | "RateType"
          | "ReasonCode"
          | "Relationship"
          | "ReservationStatus"
          | "ReservationType"
          | "ResvBookingMethod"
          | "RevenueGroups"
          | "RevenueType"
          | "Room"
          | "RoomsPotential"
          | "RoomCategoryLabel"
          | "RoomClass"
          | "RoomPool"
          | "RoomRepairsReasonCode"
          | "RoomStatusReasons"
          | "RoutingCode"
          | "Scope"
          | "ScopeCity"
          | "ScAccPriority"
          | "ScAccRoomsPot"
          | "ScAccSource"
          | "ScDestination"
          | "ScFunctionSpace"
          | "ScFunctionSpaceRateCode"
          | "ScFunctionSpaceSetup"
          | "ScRevenueTypes"
          | "ScSetupCode"
          | "ScTaskCode"
          | "ScTerritory"
          | "ServiceRequestType"
          | "SgiLanguage"
          | "SgiRequestCodes"
          | "SgiTitle"
          | "SourceCode"
          | "State"
          | "Title"
          | "TraceCode"
          | "TraceDepartment"
          | "TransportTypes"
          | "TravelAgentCommissionCodes"
          | "TravelAgentCurrencyCodes"
          | "Trxgenerates"
          | "TrxCode"
          | "VipLevel"
          | "WaitlistCodes"
          | "WebuserSecurityQuestion"
        )[];
        /** Value to be converted. It can be opera or external value. */
        valueToBeConverted?: string[];
        /** Master value is supposed to be Opera value. */
        masterValue?: string[];
      };
      header: {
        /** Bearer token that needs to be passed which is generated post user authentication */
        authorization: parameters["authKey"];
        /** Pass this header as true, if payload needs DVM */
        externalData?: parameters["externalData"];
        /** Client or Partner's Application Key */
        "x-app-key": parameters["x-app-key"];
        /** Request Id of an incoming request */
        "x-request-id"?: parameters["x-request-id"];
        /** Customer's Integration Application Id */
        "x-originating-application"?: parameters["x-originating-application"];
        /** Mandatory parameter to identify the hotel code where the end user is logged in */
        "x-hotelid": parameters["x-hotelid"];
        /** External system code. */
        "x-externalsystem"?: parameters["x-externalsystem"];
        /** Language code */
        "Accept-Language"?: parameters["Accept-Language"];
      };
    };
    responses: {
      /** Response for all the converted values. */
      200: {
        headers: {};
        schema: definitions["convertedValues"];
      };
      /** ConvertedValues not found. */
      204: never;
      400: responses["400"];
      401: responses["401"];
      403: responses["403"];
      404: responses["404"];
      405: responses["405"];
      406: responses["406"];
      413: responses["413"];
      414: responses["414"];
      415: responses["415"];
      500: responses["500"];
      502: responses["502"];
      503: responses["503"];
    };
  };
  /** This API allows you to get default values <p><strong>OperationId:</strong>getDefaultValues</p> */
  getDefaultValues: {
    parameters: {
      path: {
        operaHotelId: string;
        extSystemCode: string;
      };
      header: {
        /** Bearer token that needs to be passed which is generated post user authentication */
        authorization: parameters["authKey"];
        /** Pass this header as true, if payload needs DVM */
        externalData?: parameters["externalData"];
        /** Client or Partner's Application Key */
        "x-app-key": parameters["x-app-key"];
        /** Request Id of an incoming request */
        "x-request-id"?: parameters["x-request-id"];
        /** Customer's Integration Application Id */
        "x-originating-application"?: parameters["x-originating-application"];
        /** Mandatory parameter to identify the hotel code where the end user is logged in */
        "x-hotelid": parameters["x-hotelid"];
        /** External system code. */
        "x-externalsystem"?: parameters["x-externalsystem"];
        /** Language code */
        "Accept-Language"?: parameters["Accept-Language"];
      };
    };
    responses: {
      /** Response for all the converted values. */
      200: {
        headers: {};
        schema: definitions["defaultValues"];
      };
      /** DefaultValues not found. */
      204: never;
      400: responses["400"];
      401: responses["401"];
      403: responses["403"];
      404: responses["404"];
      405: responses["405"];
      406: responses["406"];
      413: responses["413"];
      414: responses["414"];
      415: responses["415"];
      500: responses["500"];
      502: responses["502"];
      503: responses["503"];
    };
  };
  /** API to fetch Data Value Mapping Conversion Codes for a given external system. Filters include optional hotelId and group (XML Type).<p><strong>OperationId:</strong>getDvmConversionCodes</p> */
  getDvmConversionCodes: {
    parameters: {
      path: {
        /** Identifier of the external system. */
        externalSystem: string;
      };
      query: {
        /** Unique OPERA internal ID used to identify a Hotel in OPERA. */
        hotelId?: string;
        /** List of XML Types (groups) to filter conversion codes. */
        group?: string[];
        /** List of specific conversion codes to filter. */
        conversionCode?: string[];
        /** If 'Y', returns only configured conversion codes for the interface. Otherwise, returns all conversion codes. */
        configuredOnly?: string;
      };
      header: {
        /** Bearer token that needs to be passed which is generated post user authentication */
        authorization: parameters["authKey"];
        /** Pass this header as true, if payload needs DVM */
        externalData?: parameters["externalData"];
        /** Client or Partner's Application Key */
        "x-app-key": parameters["x-app-key"];
        /** Request Id of an incoming request */
        "x-request-id"?: parameters["x-request-id"];
        /** Customer's Integration Application Id */
        "x-originating-application"?: parameters["x-originating-application"];
        /** Mandatory parameter to identify the hotel code where the end user is logged in */
        "x-hotelid": parameters["x-hotelid"];
        /** External system code. */
        "x-externalsystem"?: parameters["x-externalsystem"];
        /** Language code */
        "Accept-Language"?: parameters["Accept-Language"];
      };
    };
    responses: {
      /** Response to fetch Data Value Mapping Conversion Codes. */
      200: {
        headers: {};
        schema: definitions["fetchDvmConversionCodes"];
      };
      /** No conversion codes found for the given filters. */
      204: never;
      400: responses["400"];
      401: responses["401"];
      403: responses["403"];
      404: responses["404"];
      405: responses["405"];
      406: responses["406"];
      413: responses["413"];
      414: responses["414"];
      415: responses["415"];
      500: responses["500"];
      502: responses["502"];
      503: responses["503"];
    };
  };
  /** Retrieve mappings for a specific conversion code configured for external system, hotelId and Global mappings.<p><strong>OperationId:</strong>getDataValueMappings</p> */
  getDataValueMappings: {
    parameters: {
      path: {
        /** Identifier of the external system. */
        externalSystem: string;
        /** Type of Conversion Code configured in OPERA. */
        conversionCode: string;
      };
      query: {
        /** Unique OPERA hotel Id used to identify a Hotel in OPERA. */
        hotelId?: string;
        /** Fetch data based on scope: Filtered by All(default), Global, hotelId. */
        scope?: string;
        /** List of mapping Id's to filter. */
        mappingIds?: string[];
        /** Search string to filter by OPERA value, external value, or description. */
        searchText?: string;
      };
      header: {
        /** Bearer token that needs to be passed which is generated post user authentication */
        authorization: parameters["authKey"];
        /** Client or Partner's Application Key */
        "x-app-key": parameters["x-app-key"];
        /** Request Id of an incoming request */
        "x-request-id"?: parameters["x-request-id"];
        /** Customer's Integration Application Id */
        "x-originating-application"?: parameters["x-originating-application"];
        /** Language code */
        "Accept-Language"?: parameters["Accept-Language"];
      };
    };
    responses: {
      /** Retrieve Data Value Mapping response */
      200: {
        headers: {};
        schema: definitions["fetchDvmMappings"];
      };
      400: responses["400"];
      401: responses["401"];
      403: responses["403"];
      404: responses["404"];
      405: responses["405"];
      406: responses["406"];
      413: responses["413"];
      414: responses["414"];
      415: responses["415"];
      500: responses["500"];
      502: responses["502"];
      503: responses["503"];
    };
  };
  /** API to update existing Data Value Mapping (DVM) Conversion Code records for a given External System and Conversion Code. <p><strong>OperationId:</strong>putDataValueMappings</p> */
  putDataValueMappings: {
    parameters: {
      path: {
        /** Unique Id used to identify an external system. */
        externalSystem: string;
        /** Conversion Code configured in OPERA. */
        conversionCode: string;
      };
      body: {
        /** Request to update existing Conversion Code Mappings. */
        conversionCodeMappingsToBeUpdated: definitions["dvmConversionCodeMappingsToBeUpdated"];
      };
      header: {
        /** Bearer token that needs to be passed which is generated post user authentication */
        authorization: parameters["authKey"];
        /** Pass this header as true, if payload needs DVM */
        externalData?: parameters["externalData"];
        /** Client or Partner's Application Key */
        "x-app-key": parameters["x-app-key"];
        /** Request Id of an incoming request */
        "x-request-id"?: parameters["x-request-id"];
        /** Customer's Integration Application Id */
        "x-originating-application"?: parameters["x-originating-application"];
        /** Mandatory parameter to identify the hotel code where the end user is logged in */
        "x-hotelid": parameters["x-hotelid"];
        /** External system code. */
        "x-externalsystem"?: parameters["x-externalsystem"];
        /** Language code */
        "Accept-Language"?: parameters["Accept-Language"];
      };
    };
    responses: {
      /** Response for updating Conversion Code Mappings. */
      200: {
        headers: {};
        schema: definitions["updatedDvmConversionCodeMappings"];
      };
      400: responses["400"];
      401: responses["401"];
      403: responses["403"];
      404: responses["404"];
      405: responses["405"];
      406: responses["406"];
      413: responses["413"];
      414: responses["414"];
      415: responses["415"];
      500: responses["500"];
      502: responses["502"];
      503: responses["503"];
    };
  };
  /** API to create Data Value Mapping (DVM) Conversion Codes by External System and Conversion Code. <p><strong>OperationId:</strong>postDataValueMappings</p> */
  postDataValueMappings: {
    parameters: {
      path: {
        /** Unique ID used to identify an external system. */
        externalSystem: string;
        /** Type of conversion code configured in the system. */
        conversionCode: string;
      };
      body: {
        /** Request Object to Create Conversion Code Mappings. */
        conversionCodeMappingsToBeCreated: definitions["dvmConversionCodeMappingsToBeCreated"];
      };
      header: {
        /** Bearer token that needs to be passed which is generated post user authentication */
        authorization: parameters["authKey"];
        /** Pass this header as true, if payload needs DVM */
        externalData?: parameters["externalData"];
        /** Client or Partner's Application Key */
        "x-app-key": parameters["x-app-key"];
        /** Request Id of an incoming request */
        "x-request-id"?: parameters["x-request-id"];
        /** Customer's Integration Application Id */
        "x-originating-application"?: parameters["x-originating-application"];
        /** Language code */
        "Accept-Language"?: parameters["Accept-Language"];
      };
    };
    responses: {
      /** Response Object for creating Conversion Code Mappings. */
      201: {
        headers: {};
        schema: definitions["createdDvmConversionCodeMappings"];
      };
      400: responses["400"];
      401: responses["401"];
      403: responses["403"];
      404: responses["404"];
      405: responses["405"];
      406: responses["406"];
      413: responses["413"];
      414: responses["414"];
      415: responses["415"];
      500: responses["500"];
      502: responses["502"];
      503: responses["503"];
    };
  };
  /** API to Delete Interface Mapping Conversion Codes by providing one or more Mapping IDs as query parameter. <p><strong>OperationId:</strong>deleteDataValueMappings</p> */
  deleteDataValueMappings: {
    parameters: {
      path: {
        /** External System code */
        externalSystem: string;
        /** Conversion Code */
        conversionCode: string;
      };
      query: {
        /** List of Mapping IDs to delete */
        mappingIds: number[];
      };
      header: {
        /** Bearer token that needs to be passed which is generated post user authentication */
        authorization: parameters["authKey"];
        /** Pass this header as true, if payload needs DVM */
        externalData?: parameters["externalData"];
        /** Client or Partner's Application Key */
        "x-app-key": parameters["x-app-key"];
        /** Request Id of an incoming request */
        "x-request-id"?: parameters["x-request-id"];
        /** Customer's Integration Application Id */
        "x-originating-application"?: parameters["x-originating-application"];
        /** Mandatory parameter to identify the hotel code where the end user is logged in */
        "x-hotelid": parameters["x-hotelid"];
        /** Language code */
        "Accept-Language"?: parameters["Accept-Language"];
      };
    };
    responses: {
      /** Id's deleted and any failures with reasons. */
      200: {
        headers: {};
        schema: definitions["deleteDvmMappingResponse"];
      };
      400: responses["400"];
      401: responses["401"];
      403: responses["403"];
      404: responses["404"];
      405: responses["405"];
      406: responses["406"];
      413: responses["413"];
      414: responses["414"];
      415: responses["415"];
      500: responses["500"];
      502: responses["502"];
      503: responses["503"];
    };
  };
  /** This API allows you to delete the default values cache <p><strong>OperationId:</strong>clearDefaultValueCache</p> */
  clearDefaultValueCache: {
    parameters: {
      header: {
        /** Bearer token that needs to be passed which is generated post user authentication */
        authorization: parameters["authKey"];
        /** Pass this header as true, if payload needs DVM */
        externalData?: parameters["externalData"];
        /** Client or Partner's Application Key */
        "x-app-key": parameters["x-app-key"];
        /** Request Id of an incoming request */
        "x-request-id"?: parameters["x-request-id"];
        /** Customer's Integration Application Id */
        "x-originating-application"?: parameters["x-originating-application"];
        /** Mandatory parameter to identify the hotel code where the end user is logged in */
        "x-hotelid": parameters["x-hotelid"];
        /** External system code. */
        "x-externalsystem"?: parameters["x-externalsystem"];
        /** Language code */
        "Accept-Language"?: parameters["Accept-Language"];
      };
    };
    responses: {
      /** HATEOAS links which help the consumer to navigate to resources */
      200: {
        headers: {};
        schema: definitions["status"];
      };
      400: responses["400"];
      401: responses["401"];
      403: responses["403"];
      404: responses["404"];
      405: responses["405"];
      406: responses["406"];
      413: responses["413"];
      414: responses["414"];
      415: responses["415"];
      500: responses["500"];
      502: responses["502"];
      503: responses["503"];
    };
  };
  /** ping Data Value Mapping Service <p><strong>OperationId:</strong>pingDataValueMappingService</p> */
  pingDataValueMappingService: {
    parameters: {
      header: {
        /** Bearer token that needs to be passed which is generated post user authentication */
        authorization: parameters["authKey"];
        /** Pass this header as true, if payload needs DVM */
        externalData?: parameters["externalData"];
        /** Client or Partner's Application Key */
        "x-app-key": parameters["x-app-key"];
        /** Request Id of an incoming request */
        "x-request-id"?: parameters["x-request-id"];
        /** Customer's Integration Application Id */
        "x-originating-application"?: parameters["x-originating-application"];
        /** Mandatory parameter to identify the hotel code where the end user is logged in */
        "x-hotelid": parameters["x-hotelid"];
        /** External system code. */
        "x-externalsystem"?: parameters["x-externalsystem"];
        /** Language code */
        "Accept-Language"?: parameters["Accept-Language"];
      };
    };
    responses: {
      /** Response for Ping operation. */
      200: {
        headers: {};
        schema: definitions["operaVersion"];
      };
      /** pingDataValueMappingService not found. */
      204: never;
      400: responses["400"];
      401: responses["401"];
      403: responses["403"];
      404: responses["404"];
      405: responses["405"];
      406: responses["406"];
      413: responses["413"];
      414: responses["414"];
      415: responses["415"];
      500: responses["500"];
      502: responses["502"];
      503: responses["503"];
    };
  };
}

export interface external {}
