/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/externalSystems/{extSystemCode}/hotels/{hotelId}/revenueInventoryStatistics": {
    /** Use this API to start the process to get a hotel inventory&apos;s revenue statistics for a given date range. Maximum limit of the date range is 94 days with a single request, but the recommendation is to use a date range proportionate to the size of the hotel. Returns a header parameter Location that can be used in the getRevenueInventoryStatisticsProcessStatus operation.  Use event driven APIs (see https://docs.oracle.com/cd/F29336_01/doc.201/f27480/c_business_events.htm#OHIPU-BusinessEvents-F0AC1F1C) to get real time inventory updates.<p><strong>OperationId:</strong>startRevenueInventoryStatisticsProcess</p> */
    post: operations["startRevenueInventoryStatisticsProcess"];
  };
  "/externalSystems/{extSystemCode}/hotels/{hotelId}/revenueInventoryStatistics/{requestId}": {
    /** This API returns inventory revenue&apos;s statistics for a hotel within dates given in the startRevenueInventoryStatisticsProcess API request. You can get the value of the summaryId from the Location header returned by the getRevenueInventoryStatisticsProcessStatus operation after the process is completed.<p><strong>OperationId:</strong>getRevenueInventoryStatistics</p> */
    get: operations["getRevenueInventoryStatistics"];
    /** Use this API to check whether the process to collate inventory revenue statistics is complete. You can get value of summaryId from the Location header returned by the startRevenueInventoryStatisticsProcess operation.<p><strong>OperationId:</strong>getRevenueInventoryStatisticsProcessStatus</p> */
    head: operations["getRevenueInventoryStatisticsProcessStatus"];
  };
  "/externalSystems/{extSystemCode}/hotels/{hotelId}/inventoryStatistics": {
    /** Use this API to start the process to get a hotel's inventory statistics for a given date range. The maximum limit of the date range is 365 days with a single request, but the recommendation is to use a date range proportionate to the size of the hotel. Returns a header parameter Location that can be used in the getInventoryStatisticsProcessStatus operation.<p><strong>OperationId:</strong>startInventoryStatisticsProcess</p> */
    post: operations["startInventoryStatisticsProcess"];
  };
  "/externalSystems/{extSystemCode}/hotels/{hotelId}/inventoryStatistics/{requestId}": {
    /** This API returns inventory statistics for a hotel by given dates in the startInventoryStatisticsProcess API request. You can get the value of the summaryId with the getInventoryStatisticsProcessStatus API response (under header location). <p><strong>OperationId:</strong>getInventoryStatisticsAsync</p> */
    get: operations["getInventoryStatisticsAsync"];
    /** Use this API to check whether the statistics of the hotel's inventory statistics is ready yet. You can get value of summaryId with startInventoryStatisticsProcess API response (under header location). <p><strong>OperationId:</strong>getInventoryStatisticsProcessStatus</p> */
    head: operations["getInventoryStatisticsProcessStatus"];
  };
  "/externalSystems/{extSystemCode}/hotels/{hotelId}/sellLimits": {
    /** You can use this API to create sell limits in OPERA by date. <p><strong>OperationId:</strong>postSellLimitsProcess</p> */
    post: operations["postSellLimitsProcess"];
  };
  "/externalSystems/{extSystemCode}/hotels/{hotelId}/sellLimits/{requestId}": {
    /** This API returns the status log if any of sell limit data creation is failed. You can get the value of summaryId with the getSellLimitsProcessStatus API response (under header location). <p><strong>OperationId:</strong>getSellLimits</p> */
    get: operations["getSellLimits"];
    /** Use this API to check whether the sell limit data creation is completed yet. You can get the value of the summaryId with the postSellLimitsProcess API response (under header location). <p><strong>OperationId:</strong>getSellLimitsProcessStatus</p> */
    head: operations["getSellLimitsProcessStatus"];
  };
}

export interface definitions {
  /**
   * Error Detail
   * @description Complex type that contains error details for a REST call.
   */
  exceptionDetailType: {
    /** @description Absolute URI [RFC3986] that identifies the problem type.  When dereferenced, it SHOULD provide a human-readable summary of the problem (for example, using HTML). */
    type?: string;
    /** @description Short, human-readable summary of the problem.  The summary SHOULD NOT change for subsequent occurrences of the problem, except for purposes of localization. */
    title?: string;
    /** @description HTTP status code for this occurrence of the problem, set by the origin server. */
    status?: number;
    /** @description Human-readable description specific to this occurrence of the problem. */
    detail?: string;
    /** @description Absolute URI that identifies the specific occurrence of the problem.  It may or may not provide additional information if dereferenced. */
    instance?: string;
    /** @description Application error code, which is different from HTTP error code. */
    "o:errorCode"?: string;
    /** @description Path to the problem at the resource or property level. */
    "o:errorPath"?: string;
    /** @description Details of the error message, consisting of a hierarchical tree structure. */
    "o:errorDetails"?: definitions["errorInstance"][];
    links?: definitions["links"];
  };
  /**
   * Error Instance Details
   * @description Complex type that contains error instance details for a REST call.
   */
  errorInstance: {
    /** @description Absolute URI [RFC3986] that identifies the problem type.  When dereferenced, it SHOULD provide a human-readable summary of the problem (for example, using HTML). */
    type?: string;
    /** @description Short, human-readable summary of the problem.  The summary SHOULD NOT change for subsequent occurrences of the problem, except for purposes of localization. */
    title?: string;
    /** @description HTTP status code for this occurrence of the problem, set by the origin server. */
    status?: number;
    /** @description Human-readable description specific to this occurrence of the problem. */
    detail?: string;
    /** @description Absolute URI that identifies the specific occurrence of the problem.  It may or may not provide additional information if dereferenced. */
    instance?: string;
    /** @description Application error code, which is different from HTTP error code. */
    "o:errorCode"?: string;
    /** @description Path to the problem at the resource or property level. */
    "o:errorPath"?: string;
  };
  /** @description Metadata describing link description objects that MAY appear in the JSON instance representation. */
  instanceLink: {
    /** @description URI [RFC3986] or URI Template [RFC6570]. If the value is set to URI Template, then the "templated" property must be set to true. */
    href?: string;
    /** @description Name of the link relation that, in addition to the type property, can be used to retrieve link details. For example, href or profile. */
    rel?: string;
    /**
     * @description Boolean flag that specifies that "href" property is a URI or URI Template. If the property is a URI template, set this value to true. By default, this value is false.
     * @default false
     */
    templated?: boolean;
    /**
     * @description HTTP method for requesting the target of the link.
     * @enum {string}
     */
    method?: "GET" | "POST" | "PUT" | "DELETE" | "PATCH" | "OPTIONS" | "HEAD";
    /** @description Link to the metadata of the resource, such as JSON-schema, that describes the resource expected when dereferencing the target resource.. */
    targetSchema?: string;
    /** @description The operationId of the path you can call to follow this link.  This allows you to look up not only the path and method, but the description of that path and any parameters you need to supply. */
    operationId?: string;
    /** @description Exact copy of the "summary" field on the linked operation. */
    title?: string;
  };
  links: definitions["instanceLink"][];
  /** @description Fetch criteria type for fetching revenue inventory statistics. */
  revenueInventoryStatisticsSearchType: {
    /**
     * Format: date
     * @description The starting value of the date range.
     */
    dateRangeStart?: string;
    /**
     * Format: date
     * @description The ending value of the date range.
     */
    dateRangeEnd?: string;
    /** @description The optional room types by which revenue and inventory statistics will be grouped. */
    roomTypes?: string[];
    /** @description The market codes for which revenue and inventory statistics will be gathered. */
    marketCodes?: string[];
    /** @description The reservation guarantee codes for which revenue and inventory statistics will be gathered. */
    guaranteeCodes?: string[];
    /** @description Group by instructions for revenue inventory statistics that can be used in request operation. Response data will be grouped according to the values provided in this array. MarketCode and RoomType grouping is used for past and future revenue and inventory statistics while GuaranteeType is used only for future revenue and inventory statistics. */
    groupBy?: ("MarketCode" | "RoomType" | "GuaranteeType")[];
  };
  /** @description Revenue Inventory Statistics for the current occupancy date which might include data grouped by room type, market and reservation guarantee code. */
  revenueInventoryStatisticsDetails: {
    revInvStats?: definitions["revenueInventoryStatisticsType"][];
  };
  /** @description Revenue and statistics for an occupancy date and hotel code. */
  revenueInventoryStatisticsType: {
    /** @description The property for which revenue inventory statistics are fetched */
    property?: string;
    /**
     * Format: date
     * @description The occupancy date for which the revenue inventory statistics are fetched.
     */
    occupancyDate?: string;
    resType?: string;
    /** @description The market code for which the revenue inventory statistics are fetched. */
    marketCode?: string;
    /** @description The room type for which the revenue inventory statistics are fetched. */
    roomType?: string;
    /** @description The statistical figure for physical rooms. */
    physicalRooms?: string;
    /** @description The statistical figure for out of order rooms. */
    ooRooms?: string;
    /** @description The statistical figure for out of service rooms. */
    osRooms?: string;
    /** @description The statistical figure for rooms sold. */
    roomsSold?: string;
    /** @description The statistical figure for room revenue. */
    roomRevenue?: string;
    /** @description The statistical figure for arrival rooms. */
    roomArrivals?: string;
    /** @description The statistical figure of departure rooms. */
    roomDepartures?: string;
    /** @description The statistical figure for food revenue. */
    foodRevenue?: string;
    /** @description The statistical figure for total revenue. */
    totalRevenue?: string;
    /** @description The statistical figure for canceled rooms. */
    cancelledRooms?: string;
    /** @description The statistical figure of no show rooms. */
    noShowRooms?: string;
  };
  /** @description Used in conjunction with the Success element to define a business error. */
  warningsType: definitions["warningType"][];
  /** @description Used when a message has been successfully processed to report any warnings or business errors that occurred. */
  warningType: {
    /** @description Property Value */
    value?: string;
    /** @description An abbreviated version of the error in textual format. */
    shortText?: string;
    /** @description If present, this refers to a table of coded values exchanged between applications to identify errors or warnings. */
    code?: string;
    /** @description If present, this URL refers to an online description of the error that occurred. */
    docURL?: string;
    /** @description If present, recommended values are those enumerated in the ErrorRS, (NotProcessed Incomplete Complete Unknown) however, the data type is designated as string data, recognizing that trading partners may identify additional status conditions not included in the enumeration. */
    status?: string;
    /** @description If present, this attribute may identify an unknown or misspelled tag that caused an error in processing. It is recommended that the Tag attribute use XPath notation to identify the location of a tag in the event that more than one tag of the same name is present in the document. Alternatively, the tag name alone can be used to identify missing data [Type=ReqFieldMissing]. */
    tag?: string;
    /** @description If present, this attribute allows for batch processing and the identification of the record that failed amongst a group of records. This value may contain a concatenation of a unique failed transaction ID with specific record(s) associated with that transaction. */
    recordId?: string;
    /** @description The Warning element MUST contain the Type attribute that uses a recommended set of values to indicate the warning type. The validating XSD can expect to accept values that it has NOT been explicitly coded for and process them by using Type ="Unknown". */
    type?: string;
    /** @description Language identification. */
    language?: string;
    /** @description Reference Place Holder used as an index for this warning. */
    rph?: string;
  };
  /** @description Fetch criteria type for fetching revenue inventory statistics. */
  inventoryCriteriaType: {
    /**
     * Format: date
     * @description The starting value of the date range.
     */
    dateRangeStart: string;
    /**
     * Format: date
     * @description The ending value of the date range.
     */
    dateRangeEnd: string;
    /**
     * @description Identifies the type of statistics collected. Each ReportCode corresponds to a set of category summaries based upon a predetermined agreement.
     * @enum {string}
     */
    reportCode: "RoomsAvailabilitySummary";
    /** @description List of supported parameter names and its parameter values. */
    paramList?: definitions["paramListType"][];
    /** @description List of supported filter names and its filter values. */
    filterList?: definitions["filterListType"][];
    /**
     * @description Group by instructions for inventory statistics that can be used in request operation.
     * @enum {string}
     */
    groupBy?: "RoomType" | "RoomClass";
    /** @description Channel Code. */
    channel?: string;
  };
  /** @description Parameter name and its Parameter value as a pair. */
  paramListType: {
    /**
     * @description Property Name.
     * @enum {string}
     */
    paramName:
      | "CancelledYN"
      | "DeductRoomsYN"
      | "HouseArrPersonsYN"
      | "HouseArrRoomsYN"
      | "HouseAvailPercYN"
      | "HouseAvailRoomsExcludingOverbookingYN"
      | "HouseAvailRoomsYN"
      | "HouseAvailTenPercYN"
      | "HouseBlkDeductNpuYN"
      | "HouseBlkDeductPuYN"
      | "HouseBlkTentNpuYN"
      | "HouseBlkTentPuYN"
      | "HouseDayUsePersonYN"
      | "HouseDayUseRoomYN"
      | "HouseDepPersonsYN"
      | "HouseDepRoomsYN"
      | "HouseInventoryRoomsYN"
      | "HouseMaxAvailabilityExcludingOverbookingYN"
      | "HouseMaxAvailabilityYN"
      | "HouseMaxOccupancyYN"
      | "HouseMinAvailabilityExcludingOverbookingYN"
      | "HouseMinAvailabilityYN"
      | "HouseOccPercYN"
      | "HouseOccTenPercYN"
      | "HouseOccupancyYN"
      | "HouseOOOYN"
      | "HouseOOSRoomsYN"
      | "HouseOverBookingYN"
      | "HousePeopleInHouseYN"
      | "HousePhysicalRoomsYN"
      | "HouseRoomsSoldYN"
      | "HouseSellLimitYN"
      | "HouseTentRoomsExcludingOverbookingYN"
      | "HouseTentRoomsSoldYN"
      | "HouseTentRoomsYN"
      | "NonOwnerExclusiveYN"
      | "OutOfOrderRoomsYN"
      | "OwnerExclusiveYN"
      | "RestrictionsYN"
      | "RoomArrPersonsYN"
      | "RoomArrRoomsYN"
      | "RoomAvailRoomsExcludingOverbookingYN"
      | "RoomAvailRoomsYN"
      | "RoomBlkDeductNpuYN"
      | "RoomBlkDeductPuYN"
      | "RoomBlkTentNpuYN"
      | "RoomBlkTentPuYN"
      | "RoomCancelledYN"
      | "RoomDayUsePersonYN"
      | "RoomDayUseRoomYN"
      | "RoomDepPersonsYN"
      | "RoomDepRoomsYN"
      | "RoomInventoryRoomsYN"
      | "RoomMaxAvailabilityExcludingOverbookingYN"
      | "RoomMaxAvailabilityYN"
      | "RoomMaxOccupancyYN"
      | "RoomMinAvailabilityExcludingOverbookingYN"
      | "RoomMinAvailabilityYN"
      | "RoomOccupancyYN"
      | "RoomOOOYN"
      | "RoomOOSRoomsYN"
      | "RoomOverBookingYN"
      | "RoomPeopleInHouseYN"
      | "RoomPhysicalRoomsYN"
      | "RoomRestrictionsYN"
      | "RoomRoomsSoldYN"
      | "RoomSellLimitYN"
      | "RoomTentRoomsExcludingOverbookingYN"
      | "RoomTentRoomsYN"
      | "RoomTentYN";
    /**
     * @description Property Value.
     * @enum {string}
     */
    paramValue: "Y" | "N";
  };
  /** @description Filter name with its value. */
  filterListType: {
    /**
     * @description Filter Name.
     * @enum {string}
     */
    filterName: "RoomClassList" | "RoomTypeWildCardList";
    /** @description Filter Value. Mulitple values can be passed as comma separated values. example : if filterName is say 'RoomClassList' then its corresponding filterValue would mean room class which can be comma separated like 'DAILY,RACK' */
    filterValue: string;
  };
  /** @description List of inventory statistics that is grouped by statistic date. */
  inventoryStatisticsDetails: definitions["statisticType"][];
  /** @description Defines all details needed to create a statistical report. */
  statisticType: {
    /** @description Statistic Codes. */
    statistics?: definitions["statisticCodeType"][];
    /** @description A text field used to communicate the proper name of the hotel. */
    hotelName?: string;
    /** @description Identifies the type of statistics collected. Each ReportCode corresponds to a set of category summaries based upon a predetermined agreement. */
    reportCode?: string;
    /** @description This element has revenue amount data for its revenue category such as Room Revenue, Food and Beverage Revenue. */
    description?: string;
  };
  /** @description Defines the codes and corresponding categories for which the data in the other elements has been gathered. */
  statisticCodeType: {
    /** @description Collection of statistic summary data. */
    statisticDate?: definitions["statisticSetType"][];
    /** @description Actual code used by the system to collect the statistics (e.g. CORP, RACK if category is Market Segment). */
    statCode?: string;
    /** @description Category Code category of StatCode attribute (e.g. Market Segment). */
    statCategoryCode?: string;
    /** @description Class grouping of StatCode attribute. */
    statCodeClass?: string;
    /** @description Statistic code description. */
    description?: string;
  };
  /** @description An instance of a statistic, which is a set containing revenue category and number category summaries. */
  statisticSetType: {
    /** @description Collection of RevenueCategorySummary elements. Used if revenue values reported. */
    revenue?: definitions["revenueCategorySummaryType"][];
    /** @description Collection of CountCategorySummary elements. Used if count values reported. */
    inventory?: definitions["numericCategorySummaryType"][];
    /**
     * Format: date
     * @description Date of the statistic.
     */
    statisticDate?: string;
    /** @description Determines whether statistic date is a weekend date. */
    weekendDate?: boolean;
  };
  /** @description This element has count data for each count category such as number of guests, rooms occupied, etc. */
  numericCategorySummaryType: {
    /** @description The total count for the category in NumericCategoryCode. */
    value?: number;
    /** @description The representation of a numeric category such as Guests : Number of guests, RoomsOcc : Rooms occupied. */
    code?: string;
  };
  /** @description This element has revenue amount data for its revenue category such as Room Revenue, Food and Beverage Revenue. */
  revenueCategorySummaryType: {
    /** @description The representation of a revenue category. */
    code?: string;
    /** @description A monetary amount. */
    amount?: number;
    /** @description Provides a currency code to reflect the currency in which an amount may be expressed. */
    currencyCode?: string;
  };
  /** @description Response for sell limits status */
  sellLimitByDateStatus: {
    /** @description List of warnings that occurred. */
    warnings?: definitions["warningsType"];
    links?: definitions["links"];
  };
  /** @description Request for setting sell limits for house, room type, room class. */
  sellLimitsByDate: definitions["sellLimitByDateType"][];
  /** @description This type is used by sell limit request. */
  sellLimitByDateType: {
    /** @description Collection of House level sell limit by the date. */
    houseSellLimits?: definitions["houseSellLimitType"][];
    /** @description Collection of Room type level sell limit by the date. */
    roomTypeSellLimits?: definitions["roomTypeSellLimitType"][];
    /** @description Collection of Room Class level sell limit by the date. */
    roomClassSellLimits?: definitions["roomClassSellLimitType"][];
  };
  houseSellLimitType: {
    /** Format: date */
    date?: string;
    amount?: number;
    /**
     * @description Indicates if sell limit is flat or percentage.
     * @enum {string}
     */
    flatOrPercentage?: "Flat" | "Percentage";
  };
  roomClassSellLimitType: {
    /** Format: date */
    date?: string;
    amount?: number;
    /**
     * @description Indicates if sell limit is flat or percentage.
     * @enum {string}
     */
    flatOrPercentage?: "Flat" | "Percentage";
    roomClass?: string;
  };
  roomTypeSellLimitType: {
    /** Format: date */
    date?: string;
    amount?: number;
    /**
     * @description Indicates if sell limit is flat or percentage.
     * @enum {string}
     */
    flatOrPercentage?: "Flat" | "Percentage";
    roomType?: string;
  };
}

export interface parameters {
  /** @description Pass this header as true, if payload needs DVM */
  externalData: string;
  /** @description Bearer token that needs to be passed which is generated post user authentication */
  authKey: string;
  /** @description Client or Partner's Application Key */
  "x-app-key": string;
  /** @description Request Id of an incoming request */
  "x-request-id": string;
  /** @description Customer's Integration Application Id */
  "x-originating-application": string;
  /** @description Mandatory parameter to identify the hotel code where the end user is logged in */
  "x-hotelid": string;
  /** @description Language code */
  "Accept-Language": string;
}

export interface responses {
  /** Bad Request */
  400: {
    schema: definitions["exceptionDetailType"];
  };
  /** Unauthorized */
  401: unknown;
  /** Forbidden */
  403: unknown;
  /** Resource not found */
  404: {
    schema: definitions["exceptionDetailType"];
  };
  /** Method not allowed */
  405: unknown;
  /** Not acceptable. */
  406: unknown;
  /** Request Entity Too Large */
  413: unknown;
  /** Request URI Too Large */
  414: unknown;
  /** Unsupported Media Type */
  415: unknown;
  /** System Error */
  500: {
    schema: definitions["exceptionDetailType"];
  };
  /** Bad Gateway */
  502: unknown;
  /** Service Unavailable */
  503: unknown;
}

export interface operations {
  /** Use this API to start the process to get a hotel inventory&apos;s revenue statistics for a given date range. Maximum limit of the date range is 94 days with a single request, but the recommendation is to use a date range proportionate to the size of the hotel. Returns a header parameter Location that can be used in the getRevenueInventoryStatisticsProcessStatus operation.  Use event driven APIs (see https://docs.oracle.com/cd/F29336_01/doc.201/f27480/c_business_events.htm#OHIPU-BusinessEvents-F0AC1F1C) to get real time inventory updates.<p><strong>OperationId:</strong>startRevenueInventoryStatisticsProcess</p> */
  startRevenueInventoryStatisticsProcess: {
    parameters: {
      path: {
        extSystemCode: string;
        hotelId: string;
      };
      body: {
        /** Request object for fetching revenue inventory statistics asynchronously. */
        criteria: definitions["revenueInventoryStatisticsSearchType"];
      };
      header: {
        /** Bearer token that needs to be passed which is generated post user authentication */
        authorization: parameters["authKey"];
        /** Pass this header as true, if payload needs DVM */
        externalData?: parameters["externalData"];
        /** Client or Partner's Application Key */
        "x-app-key": parameters["x-app-key"];
        /** Request Id of an incoming request */
        "x-request-id"?: parameters["x-request-id"];
        /** Customer's Integration Application Id */
        "x-originating-application"?: parameters["x-originating-application"];
        /** Mandatory parameter to identify the hotel code where the end user is logged in */
        "x-hotelid": parameters["x-hotelid"];
        /** Language code */
        "Accept-Language"?: parameters["Accept-Language"];
      };
    };
    responses: {
      /** Location of process status resource */
      202: unknown;
      400: responses["400"];
      401: responses["401"];
      403: responses["403"];
      404: responses["404"];
      405: responses["405"];
      406: responses["406"];
      413: responses["413"];
      414: responses["414"];
      415: responses["415"];
      500: responses["500"];
      502: responses["502"];
      503: responses["503"];
    };
  };
  /** This API returns inventory revenue&apos;s statistics for a hotel within dates given in the startRevenueInventoryStatisticsProcess API request. You can get the value of the summaryId from the Location header returned by the getRevenueInventoryStatisticsProcessStatus operation after the process is completed.<p><strong>OperationId:</strong>getRevenueInventoryStatistics</p> */
  getRevenueInventoryStatistics: {
    parameters: {
      path: {
        requestId: string;
        extSystemCode: string;
        hotelId: string;
      };
      header: {
        /** Bearer token that needs to be passed which is generated post user authentication */
        authorization: parameters["authKey"];
        /** Pass this header as true, if payload needs DVM */
        externalData?: parameters["externalData"];
        /** Client or Partner's Application Key */
        "x-app-key": parameters["x-app-key"];
        /** Request Id of an incoming request */
        "x-request-id"?: parameters["x-request-id"];
        /** Customer's Integration Application Id */
        "x-originating-application"?: parameters["x-originating-application"];
        /** Mandatory parameter to identify the hotel code where the end user is logged in */
        "x-hotelid": parameters["x-hotelid"];
        /** Language code */
        "Accept-Language"?: parameters["Accept-Language"];
      };
    };
    responses: {
      /** Response for fetched revenue inventory statistics. */
      200: {
        headers: {};
        schema: definitions["revenueInventoryStatisticsDetails"];
      };
      400: responses["400"];
      401: responses["401"];
      403: responses["403"];
      404: responses["404"];
      405: responses["405"];
      406: responses["406"];
      413: responses["413"];
      414: responses["414"];
      415: responses["415"];
      500: responses["500"];
      502: responses["502"];
      503: responses["503"];
    };
  };
  /** Use this API to check whether the process to collate inventory revenue statistics is complete. You can get value of summaryId from the Location header returned by the startRevenueInventoryStatisticsProcess operation.<p><strong>OperationId:</strong>getRevenueInventoryStatisticsProcessStatus</p> */
  getRevenueInventoryStatisticsProcessStatus: {
    parameters: {
      path: {
        requestId: string;
        extSystemCode: string;
        hotelId: string;
      };
      header: {
        /** Bearer token that needs to be passed which is generated post user authentication */
        authorization: parameters["authKey"];
        /** Pass this header as true, if payload needs DVM */
        externalData?: parameters["externalData"];
        /** Client or Partner's Application Key */
        "x-app-key": parameters["x-app-key"];
        /** Request Id of an incoming request */
        "x-request-id"?: parameters["x-request-id"];
        /** Customer's Integration Application Id */
        "x-originating-application"?: parameters["x-originating-application"];
        /** Mandatory parameter to identify the hotel code where the end user is logged in */
        "x-hotelid": parameters["x-hotelid"];
        /** Language code */
        "Accept-Language"?: parameters["Accept-Language"];
      };
    };
    responses: {
      /** Response for status of scheduled asynchronous process. */
      200: unknown;
      /** Response for status of scheduled asynchronous process. */
      201: unknown;
      400: responses["400"];
      401: responses["401"];
      403: responses["403"];
      404: responses["404"];
      405: responses["405"];
      406: responses["406"];
      413: responses["413"];
      414: responses["414"];
      415: responses["415"];
      500: responses["500"];
      502: responses["502"];
      503: responses["503"];
    };
  };
  /** Use this API to start the process to get a hotel's inventory statistics for a given date range. The maximum limit of the date range is 365 days with a single request, but the recommendation is to use a date range proportionate to the size of the hotel. Returns a header parameter Location that can be used in the getInventoryStatisticsProcessStatus operation.<p><strong>OperationId:</strong>startInventoryStatisticsProcess</p> */
  startInventoryStatisticsProcess: {
    parameters: {
      path: {
        hotelId: string;
        extSystemCode: string;
      };
      body: {
        /** Request object for fetching inventory statistics asynchronously. */
        inventoryCriteria: definitions["inventoryCriteriaType"];
      };
      header: {
        /** Bearer token that needs to be passed which is generated post user authentication */
        authorization: parameters["authKey"];
        /** Pass this header as true, if payload needs DVM */
        externalData?: parameters["externalData"];
        /** Client or Partner's Application Key */
        "x-app-key": parameters["x-app-key"];
        /** Request Id of an incoming request */
        "x-request-id"?: parameters["x-request-id"];
        /** Customer's Integration Application Id */
        "x-originating-application"?: parameters["x-originating-application"];
        /** Mandatory parameter to identify the hotel code where the end user is logged in */
        "x-hotelid": parameters["x-hotelid"];
        /** Language code */
        "Accept-Language"?: parameters["Accept-Language"];
      };
    };
    responses: {
      /** Location of process status resource */
      202: unknown;
    };
  };
  /** This API returns inventory statistics for a hotel by given dates in the startInventoryStatisticsProcess API request. You can get the value of the summaryId with the getInventoryStatisticsProcessStatus API response (under header location). <p><strong>OperationId:</strong>getInventoryStatisticsAsync</p> */
  getInventoryStatisticsAsync: {
    parameters: {
      path: {
        requestId: string;
        extSystemCode: string;
        hotelId: string;
      };
      header: {
        /** Bearer token that needs to be passed which is generated post user authentication */
        authorization: parameters["authKey"];
        /** Pass this header as true, if payload needs DVM */
        externalData?: parameters["externalData"];
        /** Client or Partner's Application Key */
        "x-app-key": parameters["x-app-key"];
        /** Request Id of an incoming request */
        "x-request-id"?: parameters["x-request-id"];
        /** Customer's Integration Application Id */
        "x-originating-application"?: parameters["x-originating-application"];
        /** Mandatory parameter to identify the hotel code where the end user is logged in */
        "x-hotelid": parameters["x-hotelid"];
        /** Language code */
        "Accept-Language"?: parameters["Accept-Language"];
      };
    };
    responses: {
      /** Response for fetched inventory statistics. */
      200: {
        headers: {};
        schema: definitions["inventoryStatisticsDetails"];
      };
    };
  };
  /** Use this API to check whether the statistics of the hotel's inventory statistics is ready yet. You can get value of summaryId with startInventoryStatisticsProcess API response (under header location). <p><strong>OperationId:</strong>getInventoryStatisticsProcessStatus</p> */
  getInventoryStatisticsProcessStatus: {
    parameters: {
      path: {
        requestId: string;
        extSystemCode: string;
        hotelId: string;
      };
      header: {
        /** Bearer token that needs to be passed which is generated post user authentication */
        authorization: parameters["authKey"];
        /** Pass this header as true, if payload needs DVM */
        externalData?: parameters["externalData"];
        /** Client or Partner's Application Key */
        "x-app-key": parameters["x-app-key"];
        /** Request Id of an incoming request */
        "x-request-id"?: parameters["x-request-id"];
        /** Customer's Integration Application Id */
        "x-originating-application"?: parameters["x-originating-application"];
        /** Mandatory parameter to identify the hotel code where the end user is logged in */
        "x-hotelid": parameters["x-hotelid"];
        /** Language code */
        "Accept-Language"?: parameters["Accept-Language"];
      };
    };
    responses: {
      /** Response for status of scheduled asynchronous process. */
      200: unknown;
      /** Response for status of scheduled asynchronous process. */
      201: unknown;
    };
  };
  /** You can use this API to create sell limits in OPERA by date. <p><strong>OperationId:</strong>postSellLimitsProcess</p> */
  postSellLimitsProcess: {
    parameters: {
      path: {
        hotelId: string;
        extSystemCode: string;
      };
      body: {
        /** Request for setting sell limits for house, room type, room class. */
        sellLimitsByDate: definitions["sellLimitsByDate"];
      };
      header: {
        /** Bearer token that needs to be passed which is generated post user authentication */
        authorization: parameters["authKey"];
        /** Pass this header as true, if payload needs DVM */
        externalData?: parameters["externalData"];
        /** Client or Partner's Application Key */
        "x-app-key": parameters["x-app-key"];
        /** Request Id of an incoming request */
        "x-request-id"?: parameters["x-request-id"];
        /** Customer's Integration Application Id */
        "x-originating-application"?: parameters["x-originating-application"];
        /** Mandatory parameter to identify the hotel code where the end user is logged in */
        "x-hotelid": parameters["x-hotelid"];
        /** Language code */
        "Accept-Language"?: parameters["Accept-Language"];
      };
    };
    responses: {
      /** Location of process status resource */
      202: unknown;
      400: responses["400"];
      401: responses["401"];
      403: responses["403"];
      404: responses["404"];
      405: responses["405"];
      406: responses["406"];
      413: responses["413"];
      414: responses["414"];
      415: responses["415"];
      500: responses["500"];
      502: responses["502"];
      503: responses["503"];
    };
  };
  /** This API returns the status log if any of sell limit data creation is failed. You can get the value of summaryId with the getSellLimitsProcessStatus API response (under header location). <p><strong>OperationId:</strong>getSellLimits</p> */
  getSellLimits: {
    parameters: {
      path: {
        requestId: string;
        hotelId: string;
        extSystemCode: string;
      };
      header: {
        /** Bearer token that needs to be passed which is generated post user authentication */
        authorization: parameters["authKey"];
        /** Pass this header as true, if payload needs DVM */
        externalData?: parameters["externalData"];
        /** Client or Partner's Application Key */
        "x-app-key": parameters["x-app-key"];
        /** Request Id of an incoming request */
        "x-request-id"?: parameters["x-request-id"];
        /** Customer's Integration Application Id */
        "x-originating-application"?: parameters["x-originating-application"];
        /** Mandatory parameter to identify the hotel code where the end user is logged in */
        "x-hotelid": parameters["x-hotelid"];
        /** Language code */
        "Accept-Language"?: parameters["Accept-Language"];
      };
    };
    responses: {
      /** This asynchronous callback base type is used as a base for an extension for Opera Web Services Callback Requests to provide uniform implementation. */
      200: {
        headers: {};
        schema: definitions["sellLimitByDateStatus"];
      };
      /** SetSellLimitByDate not found. */
      204: never;
      400: responses["400"];
      401: responses["401"];
      403: responses["403"];
      404: responses["404"];
      405: responses["405"];
      406: responses["406"];
      413: responses["413"];
      414: responses["414"];
      415: responses["415"];
      500: responses["500"];
      502: responses["502"];
      503: responses["503"];
    };
  };
  /** Use this API to check whether the sell limit data creation is completed yet. You can get the value of the summaryId with the postSellLimitsProcess API response (under header location). <p><strong>OperationId:</strong>getSellLimitsProcessStatus</p> */
  getSellLimitsProcessStatus: {
    parameters: {
      path: {
        requestId: string;
        extSystemCode: string;
        hotelId: string;
      };
      header: {
        /** Bearer token that needs to be passed which is generated post user authentication */
        authorization: parameters["authKey"];
        /** Pass this header as true, if payload needs DVM */
        externalData?: parameters["externalData"];
        /** Client or Partner's Application Key */
        "x-app-key": parameters["x-app-key"];
        /** Request Id of an incoming request */
        "x-request-id"?: parameters["x-request-id"];
        /** Customer's Integration Application Id */
        "x-originating-application"?: parameters["x-originating-application"];
        /** Mandatory parameter to identify the hotel code where the end user is logged in */
        "x-hotelid": parameters["x-hotelid"];
        /** Language code */
        "Accept-Language"?: parameters["Accept-Language"];
      };
    };
    responses: {
      /** Response for status of scheduled asynchronous process. */
      200: unknown;
      /** Response for status of scheduled asynchronous process. */
      201: unknown;
      400: responses["400"];
      401: responses["401"];
      403: responses["403"];
      404: responses["404"];
      405: responses["405"];
      406: responses["406"];
      413: responses["413"];
      414: responses["414"];
      415: responses["415"];
      500: responses["500"];
      502: responses["502"];
      503: responses["503"];
    };
  };
}

export interface external {}
