/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/customizedLetter/{letterId}": {
    /** Use this API to return a customized letter based on search criteria such as letterId, letterIdContext, letterIdtype. <p><strong>OperationId:</strong>getCustomizedLetter</p> */
    get: operations["getCustomizedLetter"];
  };
  "/emailFile/{emailId}": {
    /** Use this API to return email blob file stored in file storage schema based on the search criteria emailId. It's used in profiles to return email and open in an end user's mail client. <p><strong>OperationId:</strong>getEmailFile</p> */
    get: operations["getEmailFile"];
  };
  "/fileAttachments": {
    /** Use this API to return file attachments based on search criteria such as id, idContext, idType. <p><strong>OperationId:</strong>getFileAttachment</p> */
    get: operations["getFileAttachment"];
    /** Use this API to upload a file attachment. <p><strong>OperationId:</strong>uploadFileAttachment</p> */
    post: operations["uploadFileAttachment"];
  };
  "/folioReports/email": {
    /** Use this API to create an email folio report. <p><strong>OperationId:</strong>emailFolioReport</p> */
    post: operations["emailFolioReport"];
  };
  "/hotels/{hotelId}/reservations/{reservationId}/customizedLetter": {
    /** Use this API to update a customized letter for a reservation for a specific property based on the hotelId, reservationId, customizedLetter. <p><strong>OperationId:</strong>setCustomizedLetter</p> */
    put: operations["setCustomizedLetter"];
  };
  "/hotels/{hotelId}/reservations/{reservationId}/folioReports": {
    /** Use this API to return a folio report for a reservation for a specific property based on search criteria such as reservationId, hotelId, reservationIdContext, reservationIdType, folioWindowNo, billNumber, folioType, folioDate, referenceCurrency. <p><strong>OperationId:</strong>getFolioReport</p> */
    get: operations["getFolioReport"];
  };
  "/hotels/{hotelId}/reservations/{reservationId}/registrationCard": {
    /** Use this API to return a registration card for a reservation based on search criteria such as reservationId, hotelId, reservationIdContext, reservationIdType, regenerate, signedOnly, language, template.  <p><strong>OperationId:</strong>getRegistrationCard</p> */
    get: operations["getRegistrationCard"];
  };
  "/images": {
    /** Use this API to return an image based on search criteria such as linkId, linkIdContext, linkIdType, imageCode, imageParameterCode, imageParameterValue, languageCode, imageStyle, imageId, imageIdContext, imageIdType, base64.  <p><strong>OperationId:</strong>getImage</p> */
    get: operations["getImage"];
    /** You can use this API to upload an image for the suppored image code types <p><strong>OperationId:</strong>uploadImage</p> */
    post: operations["uploadImage"];
    /** Use this API to delete an image based on parameters such as imageCode, imageSet, imageId, imageIdContext, imageIdType. <p><strong>OperationId:</strong>removeImage</p> */
    delete: operations["removeImage"];
  };
}

export interface definitions {
  /** @description Response object for retrieving customized letter. */
  customizedLetter: {
    /** @description Customized letter in HTML or RTF format. */
    customizedLetterDetails?: definitions["customizedLetterType"];
    links?: definitions["links"];
    warnings?: definitions["warningsType"];
  };
  /** @description Details about customized letter. */
  customizedLetterType: {
    /** @description Hotel code that the customized letter belongs to. */
    hotelId?: string;
    /** @description Reservation ID that the customized letter belongs to. */
    reservationId?: definitions["uniqueID_Type"];
    /**
     * Format: byte
     * @description Customized letter in HTML or RTF format.
     */
    customizedLetter?: string;
    /** @description URL that identifies the location associated with the record identified by the UniqueID. */
    url?: string;
    /** @description A reference to the type of object defined by the UniqueID element. */
    type?: string;
    /** @description The identification of a record as it exists at a point in time. An instance is used in update messages where the sender must assure the server that the update sent refers to the most recent modification level of the object being updated. */
    instance?: string;
    /** @description Used to identify the source of the identifier (e.g., IATA, ABTA). */
    idContext?: string;
    /** @description A unique identifying value assigned by the creating system. The ID attribute may be used to reference a primary-key value within a database or in a particular implementation. */
    id?: string;
    /** @description Additional identifying value assigned by the creating system. */
    idExtension?: number;
  };
  /** @description An identifier used to uniquely reference an object in a system (e.g. an airline reservation reference, customer profile reference, booking confirmation number, or a reference to a previous availability quote). */
  uniqueID_Type: {
    /** @description A unique identifying value assigned by the creating system. The ID attribute may be used to reference a primary-key value within a database or in a particular implementation. */
    id?: string;
    /** @description A reference to the type of object defined by the UniqueID element. */
    type?: string;
  };
  links: definitions["instanceLink"][];
  /** @description Metadata describing link description objects that MAY appear in the JSON instance representation. */
  instanceLink: {
    /** @description URI [RFC3986] or URI Template [RFC6570]. If the value is set to URI Template, then the "templated" property must be set to true. */
    href?: string;
    /** @description Name of the link relation that, in addition to the type property, can be used to retrieve link details. For example, href or profile. */
    rel?: string;
    /**
     * @description Boolean flag that specifies that "href" property is a URI or URI Template. If the property is a URI template, set this value to true. By default, this value is false.
     * @default false
     */
    templated?: boolean;
    /**
     * @description HTTP method for requesting the target of the link.
     * @enum {string}
     */
    method?: "GET" | "POST" | "PUT" | "DELETE" | "PATCH" | "OPTIONS" | "HEAD";
    /** @description Link to the metadata of the resource, such as JSON-schema, that describes the resource expected when dereferencing the target resource.. */
    targetSchema?: string;
    /** @description The operationId of the path you can call to follow this link.  This allows you to look up not only the path and method, but the description of that path and any parameters you need to supply. */
    operationId?: string;
    /** @description Exact copy of the "summary" field on the linked operation. */
    title?: string;
  };
  /** @description Used in conjunction with the Success element to define a business error. */
  warningsType: definitions["warningType"][];
  /** @description Used when a message has been successfully processed to report any warnings or business errors that occurred. */
  warningType: {
    /** @description Property Value */
    value?: string;
    /** @description An abbreviated version of the error in textual format. */
    shortText?: string;
    /** @description If present, this refers to a table of coded values exchanged between applications to identify errors or warnings. */
    code?: string;
    /** @description If present, this URL refers to an online description of the error that occurred. */
    docURL?: string;
    /** @description If present, recommended values are those enumerated in the ErrorRS, (NotProcessed Incomplete Complete Unknown) however, the data type is designated as string data, recognizing that trading partners may identify additional status conditions not included in the enumeration. */
    status?: string;
    /** @description If present, this attribute may identify an unknown or misspelled tag that caused an error in processing. It is recommended that the Tag attribute use XPath notation to identify the location of a tag in the event that more than one tag of the same name is present in the document. Alternatively, the tag name alone can be used to identify missing data [Type=ReqFieldMissing]. */
    tag?: string;
    /** @description If present, this attribute allows for batch processing and the identification of the record that failed amongst a group of records. This value may contain a concatenation of a unique failed transaction ID with specific record(s) associated with that transaction. */
    recordId?: string;
    /** @description The Warning element MUST contain the Type attribute that uses a recommended set of values to indicate the warning type. The validating XSD can expect to accept values that it has NOT been explicitly coded for and process them by using Type ="Unknown". */
    type?: string;
    /** @description Language identification. */
    language?: string;
    /** @description Reference Place Holder used as an index for this warning. */
    rph?: string;
  };
  /**
   * Error Detail
   * @description Complex type that contains error details for a REST call.
   */
  exceptionDetailType: {
    /** @description Absolute URI [RFC3986] that identifies the problem type.  When dereferenced, it SHOULD provide a human-readable summary of the problem (for example, using HTML). */
    type: string;
    /** @description Short, human-readable summary of the problem.  The summary SHOULD NOT change for subsequent occurrences of the problem, except for purposes of localization. */
    title: string;
    /** @description HTTP status code for this occurrence of the problem, set by the origin server. */
    status?: number;
    /** @description Human-readable description specific to this occurrence of the problem. */
    detail?: string;
    /** @description Absolute URI that identifies the specific occurrence of the problem.  It may or may not provide additional information if dereferenced. */
    instance?: string;
    /** @description Application error code, which is different from HTTP error code. */
    "o:errorCode"?: string;
    /** @description Path to the problem at the resource or property level. */
    "o:errorPath"?: string;
    /** @description Details of the error message, consisting of a hierarchical tree structure. */
    "o:errorDetails"?: definitions["errorInstance"][];
    links?: definitions["links"];
  };
  /**
   * Error Instance Details
   * @description Complex type that contains error instance details for a REST call.
   */
  errorInstance: {
    /** @description Absolute URI [RFC3986] that identifies the problem type.  When dereferenced, it SHOULD provide a human-readable summary of the problem (for example, using HTML). */
    type: string;
    /** @description Short, human-readable summary of the problem.  The summary SHOULD NOT change for subsequent occurrences of the problem, except for purposes of localization. */
    title: string;
    /** @description HTTP status code for this occurrence of the problem, set by the origin server. */
    status?: number;
    /** @description Human-readable description specific to this occurrence of the problem. */
    detail?: string;
    /** @description Absolute URI that identifies the specific occurrence of the problem.  It may or may not provide additional information if dereferenced. */
    instance?: string;
    /** @description Application error code, which is different from HTTP error code. */
    "o:errorCode"?: string;
    /** @description Path to the problem at the resource or property level. */
    "o:errorPath"?: string;
  };
  /** @description Response object for Fetch Email Blob File Operation. */
  emailFile: {
    /** @description Email File Blob Details based on email Id Number */
    file?: definitions["emailFileType"];
    links?: definitions["links"];
    warnings?: definitions["warningsType"];
  };
  /** @description ID that uniquely defines an email object */
  emailFileType: {
    /** @description Unique ID that represents an email. */
    emailID?: definitions["uniqueID_Type"];
    /**
     * Format: byte
     * @description File attachment in base64 binary format
     */
    emailFile?: string;
    /** @description Name of the attachment */
    emailFileName?: string;
  };
  /** @description Response to fetch file attachment */
  file: {
    /** @description File Attachment details */
    fileDetails?: definitions["fileAttachmentType"];
    links?: definitions["links"];
    warnings?: definitions["warningsType"];
  };
  /** @description ID that uniquely determines file attachment */
  fileAttachmentType: {
    /** @description Unique ID that represents file attachment */
    attachmentId?: definitions["uniqueID_Type"];
    /**
     * Format: byte
     * @description File attachment in base64 binary format
     */
    fileAttachment?: string;
    /** @description Name of the attachment */
    fileName?: string;
  };
  /** @description Request to upload a file attachment. */
  fileToUpload: {
    /** @description Link Id of the attachment. */
    linkId?: definitions["stringLength200"];
    /** @description Link Type of the attachment. */
    linkType?: definitions["stringLength200"];
    /** @description Name of the attachment. */
    fileName?: definitions["stringLength1000"];
    /** @description Description of the attachment file. */
    description?: definitions["stringLength2000"];
    /** @description User (name) related to the attachment file. */
    userName?: definitions["stringLength200"];
    /** @description Resort related to the attachment file. */
    hotelId?: definitions["stringLength200"];
    /** @description Global Yes (Y) or No (N) flag related to the attachment file. */
    globalYN?: definitions["stringLength10"];
    /**
     * Format: byte
     * @description Attachment file in base64 binary format.
     */
    fileAttachment?: string;
    /** @description Overwrite Yes (Y) or No (N) flag related to the attachment file. */
    overwriteExistingFileYN?: definitions["stringLength10"];
    links?: definitions["links"];
    warnings?: definitions["warningsType"];
  };
  /** @description Used for Character Strings, length 0 to 200. */
  stringLength200: string;
  /** @description Used for Character Strings, length 0 to 1000. */
  stringLength1000: string;
  /** @description Used for Character Strings, length 0 to 2000. */
  stringLength2000: string;
  /** @description Used for Character Strings, length 0 to 10. */
  stringLength10: string;
  /** @description Response Body. */
  status: {
    warnings?: definitions["warningsType"];
    links?: definitions["links"];
  };
  /** @description Request to generate and email a folio report. */
  folioReportToEmail: {
    /** @description Identifies folio to be generated. */
    folioInfo?: definitions["folioReportCriteriaType"];
    /** @description List of email recipients for the report. */
    emailRecipients?: definitions["emailRecipientsType"];
    links?: definitions["links"];
    warnings?: definitions["warningsType"];
  };
  /** @description Criteria required to generate or retrieve a folio for a reservation. */
  folioReportCriteriaType: {
    /** @description Hotel code for the folio. */
    hotelId?: string;
    /** @description Reservation ID to generate a folio for. */
    reservationId?: definitions["uniqueID_Type"];
    /** @description Folio window number to generate (defaults to view 1). */
    folioWindowNo?: number;
    /** @description Optional bill number to generate. */
    billNumber?: number;
    /** @description Optional folio type. */
    folioType?: string;
    /**
     * Format: date
     * @description Optional folio generation date - defaults to hotel business date.
     */
    folioDate?: string;
    /** @description Folio currency code. */
    referenceCurrency?: string;
  };
  emailRecipientsType: definitions["emailRecipientType"][];
  emailRecipientType: {
    emailAddress?: string;
  };
  /** @description Response Body. */
  customizedLetterStatus: {
    links?: definitions["links"];
    warnings?: definitions["warningsType"];
  };
  /** @description Response object for folio report. */
  folioReport: {
    /** @description Folio report. */
    folio?: definitions["folioReportResultType"];
    links?: definitions["links"];
    warnings?: definitions["warningsType"];
  };
  /** @description Folio card details, including PDF report. */
  folioReportResultType: {
    /** @description Hotel code for the folio. */
    hotelId?: string;
    /** @description Reservation ID identifying the folio. */
    reservationId?: definitions["uniqueID_Type"];
    /**
     * Format: byte
     * @description Folio PDF report.
     */
    folio?: string;
  };
  /** @description Response object for registration card. */
  registrationCard: {
    /** @description Registration card PDF. */
    registrationCard?: definitions["registrationCardType"];
    links?: definitions["links"];
    warnings?: definitions["warningsType"];
  };
  /** @description Registration card details, including PDF report. */
  registrationCardType: {
    /** @description Hotel code for the registration card. */
    hotelId?: string;
    /** @description Reservation ID identifying the reservation for the registration card. */
    reservationId?: definitions["uniqueID_Type"];
    /**
     * Format: byte
     * @description Registration card PDF.
     */
    registrationCard?: string;
  };
  /** @description Request to upload an image. */
  imageToUpload: {
    /** @description Image upload details including image to upload. */
    images?: definitions["imageUploadInfoType"];
    links?: definitions["links"];
    warnings?: definitions["warningsType"];
  };
  /** @description List of Image details to upload including image to upload. */
  imageUploadInfoType: definitions["imageUploadType"][];
  /** @description Image upload details */
  imageUploadType: {
    /** @description Image code to upload */
    imageCode?: definitions["imageCodeType"];
    /** @description File extension of the Image, e.g. JPG, PNG, BMP, etc. */
    fileExtension?: string;
    /** @description Zero or more image parameters - code / value pairs which define the image path. These are dependent on the image code type. */
    imageParameters?: definitions["imageParametersType"];
    /** @description Language code for the image. */
    languageCode?: definitions["languageType"];
    /** @description Style of the image. */
    imageStyle?: definitions["imageStyleType"];
    /** @description Link ID to reference table. */
    linkId?: definitions["uniqueID_Type"];
    /** @description Description of the image. */
    description?: string;
    /**
     * Format: byte
     * @description Image file to upload.
     */
    image?: string;
    /** @description Image Id of the image to be replaced. */
    imageId?: definitions["uniqueID_Type"];
  };
  /** @enum {string} */
  imageCodeType:
    | "LogoChain"
    | "Logo"
    | "Profile"
    | "Nationality"
    | "User"
    | "ToolbarItemCode"
    | "Chain"
    | "MembershipType"
    | "MembershipLevel"
    | "Resort"
    | "RoomTypeChain"
    | "RoomType"
    | "RoomNumber"
    | "OooReasonChain"
    | "OooReason"
    | "RoomMaintChain"
    | "RoomMaintenance"
    | "RoomMaintIssue"
    | "FloorPlan"
    | "SiteLayout"
    | "Attraction"
    | "PropertyMap"
    | "InvItemChain"
    | "InvItem"
    | "PackageChain"
    | "Package"
    | "Pool"
    | "RoomConditionChain"
    | "RoomCondition"
    | "FunctionSpace"
    | "FunctionSetupStyle"
    | "TrackItTypeChain"
    | "TrackItType"
    | "Height"
    | "Width"
    | "RoomRepair"
    | "Article";
  /** @description Collection of image parameters code / value pairs. */
  imageParametersType: definitions["imageParameterType"][];
  /** @description Image parameter code/value pair */
  imageParameterType: {
    /** @description Image parameter code. */
    imageParameterCode?: definitions["imageCodeType"];
    /** @description Image parameter value. */
    imageParameterValue?: string;
  };
  languageType: string;
  /**
   * @description An enumeration of image styles.
   * @enum {string}
   */
  imageStyleType:
    | "Full"
    | "Thumbnail"
    | "Icon"
    | "Square"
    | "Banner"
    | "Button"
    | "Lowres"
    | "Highres";
  /** @description Response to fetch image(s) */
  image: {
    /** @description Collection of images */
    images?: definitions["imageResultsType"];
    links?: definitions["links"];
    warnings?: definitions["warningsType"];
  };
  /** @description Collection of image results. */
  imageResultsType: definitions["imageResultType"][];
  imageResultType: {
    /** @description Image set describing path of image. */
    imageSet?: string;
    /** @description Mime type of the Image. */
    mimeType?: string;
    /**
     * Format: byte
     * @description Image file to upload.
     */
    image?: string;
    /** @description ImageId file. */
    imageId?: definitions["uniqueID_Type"];
    /** @description LinkID of the file. */
    linkId?: definitions["uniqueID_Type"];
    /** @description Image link id file. */
    imageLinkId?: definitions["uniqueID_Type"];
    /** @description Base64Image image content of the file. */
    base64Image?: string;
  };
}

export interface parameters {
  /** @description Pass this header as true, if payload needs DVM */
  externalData: string;
  /** @description Bearer token that needs to be passed which is generated post user authentication */
  authKey: string;
  /** @description Client or Partner's Application Key */
  "x-app-key": string;
  /** @description Request Id of an incoming request */
  "x-request-id": string;
  /** @description Customer's Integration Application Id */
  "x-originating-application": string;
  /** @description Mandatory parameter to identify the hotel code where the end user is logged in */
  "x-hotelid": string;
  /** @description External system code. */
  "x-externalsystem": string;
  /** @description Language code */
  "Accept-Language": string;
  /** @description x-hubid is a logical grouping of multiple properties that allows api consumers to manage data from a group of properties. This x-hubid is a valid list of hub codes configured in OPERA to which the user has access. Rest APIs without hotelId in the operation path can support hub level integration using x-hubid */
  "x-hubid": string;
}

export interface responses {
  /** Bad Request */
  400: {
    schema: definitions["exceptionDetailType"];
  };
  /** Unauthorized */
  401: unknown;
  /** Forbidden */
  403: unknown;
  /** Resource not found */
  404: {
    schema: definitions["exceptionDetailType"];
  };
  /** Method not allowed */
  405: unknown;
  /** Not acceptable. */
  406: unknown;
  /** Request Entity Too Large */
  413: unknown;
  /** Request URI Too Large */
  414: unknown;
  /** Unsupported Media Type */
  415: unknown;
  /** System Error */
  500: {
    schema: definitions["exceptionDetailType"];
  };
  /** Bad Gateway */
  502: unknown;
  /** Service Unavailable */
  503: unknown;
}

export interface operations {
  /** Use this API to return a customized letter based on search criteria such as letterId, letterIdContext, letterIdtype. <p><strong>OperationId:</strong>getCustomizedLetter</p> */
  getCustomizedLetter: {
    parameters: {
      path: {
        letterId: string;
      };
      query: {
        /** Used to identify the source of the identifier (e.g., IATA, ABTA). */
        letterIdContext?: string;
        /** A reference to the type of object defined by the UniqueID element. */
        letterIdtype?: string;
      };
      header: {
        /** Bearer token that needs to be passed which is generated post user authentication */
        authorization: parameters["authKey"];
        /** Pass this header as true, if payload needs DVM */
        externalData?: parameters["externalData"];
        /** Client or Partner's Application Key */
        "x-app-key": parameters["x-app-key"];
        /** Request Id of an incoming request */
        "x-request-id"?: parameters["x-request-id"];
        /** Customer's Integration Application Id */
        "x-originating-application"?: parameters["x-originating-application"];
        /** Mandatory parameter to identify the hotel code where the end user is logged in */
        "x-hotelid": parameters["x-hotelid"];
        /** External system code. */
        "x-externalsystem"?: parameters["x-externalsystem"];
        /** Language code */
        "Accept-Language"?: parameters["Accept-Language"];
      };
    };
    responses: {
      /** Response object for retrieving customized letter. */
      200: {
        headers: {};
        schema: definitions["customizedLetter"];
      };
      /** CustomizedLetter not found. */
      204: never;
      400: responses["400"];
      401: responses["401"];
      403: responses["403"];
      404: responses["404"];
      405: responses["405"];
      406: responses["406"];
      413: responses["413"];
      414: responses["414"];
      415: responses["415"];
      500: responses["500"];
      502: responses["502"];
      503: responses["503"];
    };
  };
  /** Use this API to return email blob file stored in file storage schema based on the search criteria emailId. It's used in profiles to return email and open in an end user's mail client. <p><strong>OperationId:</strong>getEmailFile</p> */
  getEmailFile: {
    parameters: {
      path: {
        /** Unique OPERA Email ID which is used to find an Email BLOB File from OPERA. This ID is a primary identification of an email file in OPERA. */
        emailId: string;
      };
      header: {
        /** Bearer token that needs to be passed which is generated post user authentication */
        authorization: parameters["authKey"];
        /** Pass this header as true, if payload needs DVM */
        externalData?: parameters["externalData"];
        /** Client or Partner's Application Key */
        "x-app-key": parameters["x-app-key"];
        /** Request Id of an incoming request */
        "x-request-id"?: parameters["x-request-id"];
        /** Customer's Integration Application Id */
        "x-originating-application"?: parameters["x-originating-application"];
        /** Mandatory parameter to identify the hotel code where the end user is logged in */
        "x-hotelid": parameters["x-hotelid"];
        /** External system code. */
        "x-externalsystem"?: parameters["x-externalsystem"];
        /** Language code */
        "Accept-Language"?: parameters["Accept-Language"];
      };
    };
    responses: {
      /** Response to fetch an email file */
      200: {
        headers: {};
        schema: definitions["emailFile"];
      };
      /** EmailFile not found. */
      204: never;
      400: responses["400"];
      401: responses["401"];
      403: responses["403"];
      404: responses["404"];
      405: responses["405"];
      406: responses["406"];
      413: responses["413"];
      414: responses["414"];
      415: responses["415"];
      500: responses["500"];
      502: responses["502"];
      503: responses["503"];
    };
  };
  /** Use this API to return file attachments based on search criteria such as id, idContext, idType. <p><strong>OperationId:</strong>getFileAttachment</p> */
  getFileAttachment: {
    parameters: {
      query: {
        /** A unique identifying value assigned by the creating system. The ID attribute may be used to reference a primary-key value within a database or in a particular implementation. */
        id?: string;
        /** Used to identify the source of the identifier (e.g., IATA, ABTA). */
        idContext?: string;
        /** A reference to the type of object defined by the UniqueID element. */
        idType?: string;
      };
      header: {
        /** Bearer token that needs to be passed which is generated post user authentication */
        authorization: parameters["authKey"];
        /** Pass this header as true, if payload needs DVM */
        externalData?: parameters["externalData"];
        /** Client or Partner's Application Key */
        "x-app-key": parameters["x-app-key"];
        /** Request Id of an incoming request */
        "x-request-id"?: parameters["x-request-id"];
        /** Customer's Integration Application Id */
        "x-originating-application"?: parameters["x-originating-application"];
        /** Mandatory parameter to identify the hotel code where the end user is logged in */
        "x-hotelid": parameters["x-hotelid"];
        /** External system code. */
        "x-externalsystem"?: parameters["x-externalsystem"];
        /** Language code */
        "Accept-Language"?: parameters["Accept-Language"];
      };
    };
    responses: {
      /** Response to fetch file attachment */
      200: {
        headers: {};
        schema: definitions["file"];
      };
      /** FileAttachment not found. */
      204: never;
      400: responses["400"];
      401: responses["401"];
      403: responses["403"];
      404: responses["404"];
      405: responses["405"];
      406: responses["406"];
      413: responses["413"];
      414: responses["414"];
      415: responses["415"];
      500: responses["500"];
      502: responses["502"];
      503: responses["503"];
    };
  };
  /** Use this API to upload a file attachment. <p><strong>OperationId:</strong>uploadFileAttachment</p> */
  uploadFileAttachment: {
    parameters: {
      body: {
        /** Request to upload a file attachment. */
        fileToUpload: definitions["fileToUpload"];
      };
      header: {
        /** Bearer token that needs to be passed which is generated post user authentication */
        authorization: parameters["authKey"];
        /** Pass this header as true, if payload needs DVM */
        externalData?: parameters["externalData"];
        /** Client or Partner's Application Key */
        "x-app-key": parameters["x-app-key"];
        /** Request Id of an incoming request */
        "x-request-id"?: parameters["x-request-id"];
        /** Customer's Integration Application Id */
        "x-originating-application"?: parameters["x-originating-application"];
        /** Mandatory parameter to identify the hotel code where the end user is logged in */
        "x-hotelid": parameters["x-hotelid"];
        /** External system code. */
        "x-externalsystem"?: parameters["x-externalsystem"];
        /** Language code */
        "Accept-Language"?: parameters["Accept-Language"];
      };
    };
    responses: {
      /** HATEOAS links which help the consumer to navigate to resources */
      201: {
        headers: {};
        schema: definitions["status"];
      };
      400: responses["400"];
      401: responses["401"];
      403: responses["403"];
      404: responses["404"];
      405: responses["405"];
      406: responses["406"];
      413: responses["413"];
      414: responses["414"];
      415: responses["415"];
      500: responses["500"];
      502: responses["502"];
      503: responses["503"];
    };
  };
  /** Use this API to create an email folio report. <p><strong>OperationId:</strong>emailFolioReport</p> */
  emailFolioReport: {
    parameters: {
      body: {
        /** Request to generate and email a folio report. */
        folioReportToEmail: definitions["folioReportToEmail"];
      };
      header: {
        /** Bearer token that needs to be passed which is generated post user authentication */
        authorization: parameters["authKey"];
        /** Pass this header as true, if payload needs DVM */
        externalData?: parameters["externalData"];
        /** Client or Partner's Application Key */
        "x-app-key": parameters["x-app-key"];
        /** Request Id of an incoming request */
        "x-request-id"?: parameters["x-request-id"];
        /** Customer's Integration Application Id */
        "x-originating-application"?: parameters["x-originating-application"];
        /** Mandatory parameter to identify the hotel code where the end user is logged in */
        "x-hotelid": parameters["x-hotelid"];
        /** External system code. */
        "x-externalsystem"?: parameters["x-externalsystem"];
        /** Language code */
        "Accept-Language"?: parameters["Accept-Language"];
      };
    };
    responses: {
      /** HATEOAS links which help the consumer to navigate to resources */
      201: {
        headers: {};
        schema: definitions["status"];
      };
      400: responses["400"];
      401: responses["401"];
      403: responses["403"];
      404: responses["404"];
      405: responses["405"];
      406: responses["406"];
      413: responses["413"];
      414: responses["414"];
      415: responses["415"];
      500: responses["500"];
      502: responses["502"];
      503: responses["503"];
    };
  };
  /** Use this API to update a customized letter for a reservation for a specific property based on the hotelId, reservationId, customizedLetter. <p><strong>OperationId:</strong>setCustomizedLetter</p> */
  setCustomizedLetter: {
    parameters: {
      path: {
        reservationId: string;
        hotelId: string;
      };
      body: {
        /** Request to save customized letter. */
        customizedLetter: definitions["customizedLetter"];
      };
      header: {
        /** Bearer token that needs to be passed which is generated post user authentication */
        authorization: parameters["authKey"];
        /** Pass this header as true, if payload needs DVM */
        externalData?: parameters["externalData"];
        /** Client or Partner's Application Key */
        "x-app-key": parameters["x-app-key"];
        /** Request Id of an incoming request */
        "x-request-id"?: parameters["x-request-id"];
        /** Customer's Integration Application Id */
        "x-originating-application"?: parameters["x-originating-application"];
        /** Mandatory parameter to identify the hotel code where the end user is logged in */
        "x-hotelid": parameters["x-hotelid"];
        /** External system code. */
        "x-externalsystem"?: parameters["x-externalsystem"];
        /** Language code */
        "Accept-Language"?: parameters["Accept-Language"];
      };
    };
    responses: {
      /** Response Body. */
      200: {
        headers: {};
        schema: definitions["customizedLetterStatus"];
      };
      400: responses["400"];
      401: responses["401"];
      403: responses["403"];
      404: responses["404"];
      405: responses["405"];
      406: responses["406"];
      413: responses["413"];
      414: responses["414"];
      415: responses["415"];
      500: responses["500"];
      502: responses["502"];
      503: responses["503"];
    };
  };
  /** Use this API to return a folio report for a reservation for a specific property based on search criteria such as reservationId, hotelId, reservationIdContext, reservationIdType, folioWindowNo, billNumber, folioType, folioDate, referenceCurrency. <p><strong>OperationId:</strong>getFolioReport</p> */
  getFolioReport: {
    parameters: {
      path: {
        reservationId: string;
        hotelId: string;
      };
      query: {
        /** Used to identify the source of the identifier (e.g., IATA, ABTA). */
        reservationIdContext?: string;
        /** A reference to the type of object defined by the UniqueID element. */
        reservationIdType?: string;
        /** Folio window number to generate (defaults to view 1). */
        folioWindowNo?: number;
        /** Optional bill number to generate. */
        billNumber?: number;
        /** Optional folio type. */
        folioType?: string;
        /** Optional folio generation date - defaults to hotel business date. */
        folioDate?: string;
        /** Folio currency code. */
        referenceCurrency?: string;
      };
      header: {
        /** Bearer token that needs to be passed which is generated post user authentication */
        authorization: parameters["authKey"];
        /** Pass this header as true, if payload needs DVM */
        externalData?: parameters["externalData"];
        /** Client or Partner's Application Key */
        "x-app-key": parameters["x-app-key"];
        /** Request Id of an incoming request */
        "x-request-id"?: parameters["x-request-id"];
        /** Customer's Integration Application Id */
        "x-originating-application"?: parameters["x-originating-application"];
        /** Mandatory parameter to identify the hotel code where the end user is logged in */
        "x-hotelid": parameters["x-hotelid"];
        /** External system code. */
        "x-externalsystem"?: parameters["x-externalsystem"];
        /** Language code */
        "Accept-Language"?: parameters["Accept-Language"];
      };
    };
    responses: {
      /** Response object for folio report. */
      200: {
        headers: {};
        schema: definitions["folioReport"];
      };
      /** FolioReport not found. */
      204: never;
      400: responses["400"];
      401: responses["401"];
      403: responses["403"];
      404: responses["404"];
      405: responses["405"];
      406: responses["406"];
      413: responses["413"];
      414: responses["414"];
      415: responses["415"];
      500: responses["500"];
      502: responses["502"];
      503: responses["503"];
    };
  };
  /** Use this API to return a registration card for a reservation based on search criteria such as reservationId, hotelId, reservationIdContext, reservationIdType, regenerate, signedOnly, language, template.  <p><strong>OperationId:</strong>getRegistrationCard</p> */
  getRegistrationCard: {
    parameters: {
      path: {
        reservationId: string;
        hotelId: string;
      };
      query: {
        /** Used to identify the source of the identifier (e.g., IATA, ABTA). */
        reservationIdContext?: string;
        /** A reference to the type of object defined by the UniqueID element. */
        reservationIdType?: string;
        /** Flag indicating whether a new registration card should be generated even if a signed card already exists. */
        regenerate?: boolean;
        /** Flag indicating whether return only the signed registrationCard if present. */
        signedOnly?: boolean;
        /** Optional language code to use for registration card generation. Default guest language will be applied if not specified. */
        language?: string;
        /** Optional registration card template code to use for registration card generation. Default template will be applied if not specified. */
        template?: string;
      };
      header: {
        /** Bearer token that needs to be passed which is generated post user authentication */
        authorization: parameters["authKey"];
        /** Pass this header as true, if payload needs DVM */
        externalData?: parameters["externalData"];
        /** Client or Partner's Application Key */
        "x-app-key": parameters["x-app-key"];
        /** Request Id of an incoming request */
        "x-request-id"?: parameters["x-request-id"];
        /** Customer's Integration Application Id */
        "x-originating-application"?: parameters["x-originating-application"];
        /** Mandatory parameter to identify the hotel code where the end user is logged in */
        "x-hotelid": parameters["x-hotelid"];
        /** External system code. */
        "x-externalsystem"?: parameters["x-externalsystem"];
        /** Language code */
        "Accept-Language"?: parameters["Accept-Language"];
      };
    };
    responses: {
      /** Response object for registration card. */
      200: {
        headers: {};
        schema: definitions["registrationCard"];
      };
      /** RegistrationCard not found. */
      204: never;
      400: responses["400"];
      401: responses["401"];
      403: responses["403"];
      404: responses["404"];
      405: responses["405"];
      406: responses["406"];
      413: responses["413"];
      414: responses["414"];
      415: responses["415"];
      500: responses["500"];
      502: responses["502"];
      503: responses["503"];
    };
  };
  /** Use this API to return an image based on search criteria such as linkId, linkIdContext, linkIdType, imageCode, imageParameterCode, imageParameterValue, languageCode, imageStyle, imageId, imageIdContext, imageIdType, base64.  <p><strong>OperationId:</strong>getImage</p> */
  getImage: {
    parameters: {
      query: {
        /** A unique identifying value assigned by the creating system. The ID attribute may be used to reference a primary-key value within a database or in a particular implementation. */
        linkId?: string;
        /** Used to identify the source of the identifier (e.g., IATA, ABTA). */
        linkIdContext?: string;
        /** A reference to the type of object defined by the UniqueID element. */
        linkIdType?: string;
        /** An enumeration of image codes such as Logo, RoomType, InvItem */
        imageCode?:
          | "LogoChain"
          | "Logo"
          | "Profile"
          | "Nationality"
          | "User"
          | "ToolbarItemCode"
          | "Chain"
          | "MembershipType"
          | "MembershipLevel"
          | "Resort"
          | "RoomTypeChain"
          | "RoomType"
          | "RoomNumber"
          | "OooReasonChain"
          | "OooReason"
          | "RoomMaintChain"
          | "RoomMaintenance"
          | "RoomMaintIssue"
          | "FloorPlan"
          | "SiteLayout"
          | "Attraction"
          | "PropertyMap"
          | "InvItemChain"
          | "InvItem"
          | "PackageChain"
          | "Package"
          | "Pool"
          | "RoomConditionChain"
          | "RoomCondition"
          | "FunctionSpace"
          | "FunctionSetupStyle"
          | "TrackItTypeChain"
          | "TrackItType"
          | "Height"
          | "Width"
          | "RoomRepair"
          | "Article";
        /** An enumeration of image parameter codes such as Logo, RoomType, InvItem */
        imageParameterCode?: (
          | "LogoChain"
          | "Logo"
          | "Profile"
          | "Nationality"
          | "User"
          | "ToolbarItemCode"
          | "Chain"
          | "MembershipType"
          | "MembershipLevel"
          | "Resort"
          | "RoomTypeChain"
          | "RoomType"
          | "RoomNumber"
          | "OooReasonChain"
          | "OooReason"
          | "RoomMaintChain"
          | "RoomMaintenance"
          | "RoomMaintIssue"
          | "FloorPlan"
          | "SiteLayout"
          | "Attraction"
          | "PropertyMap"
          | "InvItemChain"
          | "InvItem"
          | "PackageChain"
          | "Package"
          | "Pool"
          | "RoomConditionChain"
          | "RoomCondition"
          | "FunctionSpace"
          | "FunctionSetupStyle"
          | "TrackItTypeChain"
          | "TrackItType"
          | "Height"
          | "Width"
        )[];
        /** Image parameter value. */
        imageParameterValue?: string[];
        /** Unique Code of language. */
        languageCode?: string;
        /** An enumeration of image styles. */
        imageStyle?:
          | "Full"
          | "Thumbnail"
          | "Icon"
          | "Square"
          | "Banner"
          | "Button"
          | "Lowres"
          | "Highres";
        /** A unique identifying value assigned by the creating system. The ID attribute may be used to reference a primary-key value within a database or in a particular implementation. */
        imageId?: string;
        /** Used to identify the source of the identifier (e.g., IATA, ABTA). */
        imageIdContext?: string;
        /** A reference to the type of object defined by the UniqueID element. */
        imageIdType?: string;
        /** True if the image to be returned as a base64String else if the image to be returned as the binary in MTOM attachment then false . */
        base64?: boolean;
      };
      header: {
        /** Bearer token that needs to be passed which is generated post user authentication */
        authorization: parameters["authKey"];
        /** Pass this header as true, if payload needs DVM */
        externalData?: parameters["externalData"];
        /** Client or Partner's Application Key */
        "x-app-key": parameters["x-app-key"];
        /** Request Id of an incoming request */
        "x-request-id"?: parameters["x-request-id"];
        /** Customer's Integration Application Id */
        "x-originating-application"?: parameters["x-originating-application"];
        /** Mandatory parameter to identify the hotel code where the end user is logged in */
        "x-hotelid": parameters["x-hotelid"];
        /** External system code. */
        "x-externalsystem"?: parameters["x-externalsystem"];
        /** Language code */
        "Accept-Language"?: parameters["Accept-Language"];
      };
    };
    responses: {
      /** Response to fetch image(s) */
      200: {
        headers: {};
        schema: definitions["image"];
      };
      /** Image not found. */
      204: never;
      400: responses["400"];
      401: responses["401"];
      403: responses["403"];
      404: responses["404"];
      405: responses["405"];
      406: responses["406"];
      413: responses["413"];
      414: responses["414"];
      415: responses["415"];
      500: responses["500"];
      502: responses["502"];
      503: responses["503"];
    };
  };
  /** You can use this API to upload an image for the suppored image code types <p><strong>OperationId:</strong>uploadImage</p> */
  uploadImage: {
    parameters: {
      body: {
        /** Request to upload an image. */
        imageToUpload: definitions["imageToUpload"];
      };
      header: {
        /** Bearer token that needs to be passed which is generated post user authentication */
        authorization: parameters["authKey"];
        /** Pass this header as true, if payload needs DVM */
        externalData?: parameters["externalData"];
        /** Client or Partner's Application Key */
        "x-app-key": parameters["x-app-key"];
        /** Request Id of an incoming request */
        "x-request-id"?: parameters["x-request-id"];
        /** Customer's Integration Application Id */
        "x-originating-application"?: parameters["x-originating-application"];
        /** Mandatory parameter to identify the hotel code where the end user is logged in */
        "x-hotelid": parameters["x-hotelid"];
        /** External system code. */
        "x-externalsystem"?: parameters["x-externalsystem"];
        /** Language code */
        "Accept-Language"?: parameters["Accept-Language"];
      };
    };
    responses: {
      /** HATEOAS links which help the consumer to navigate to resources */
      201: {
        headers: {};
        schema: definitions["status"];
      };
      400: responses["400"];
      401: responses["401"];
      403: responses["403"];
      404: responses["404"];
      405: responses["405"];
      406: responses["406"];
      413: responses["413"];
      414: responses["414"];
      415: responses["415"];
      500: responses["500"];
      502: responses["502"];
      503: responses["503"];
    };
  };
  /** Use this API to delete an image based on parameters such as imageCode, imageSet, imageId, imageIdContext, imageIdType. <p><strong>OperationId:</strong>removeImage</p> */
  removeImage: {
    parameters: {
      query: {
        /** An enumeration of image codes such as Logo, RoomType, InvItem */
        imageCode?:
          | "LogoChain"
          | "Logo"
          | "Profile"
          | "Nationality"
          | "User"
          | "ToolbarItemCode"
          | "Chain"
          | "MembershipType"
          | "MembershipLevel"
          | "Resort"
          | "RoomTypeChain"
          | "RoomType"
          | "RoomNumber"
          | "OooReasonChain"
          | "OooReason"
          | "RoomMaintChain"
          | "RoomMaintenance"
          | "RoomMaintIssue"
          | "FloorPlan"
          | "SiteLayout"
          | "Attraction"
          | "PropertyMap"
          | "InvItemChain"
          | "InvItem"
          | "PackageChain"
          | "Package"
          | "Pool"
          | "RoomConditionChain"
          | "RoomCondition"
          | "FunctionSpace"
          | "FunctionSetupStyle"
          | "TrackItTypeChain"
          | "TrackItType"
          | "Height"
          | "Width"
          | "RoomRepair"
          | "Article";
        /** Used for Character Strings, length 0 to 800. */
        imageSet?: string;
        /** A unique identifying value assigned by the creating system. The ID attribute may be used to reference a primary-key value within a database or in a particular implementation. */
        imageId?: string;
        /** Used to identify the source of the identifier (e.g., IATA, ABTA). */
        imageIdContext?: string;
        /** A reference to the type of object defined by the UniqueID element. */
        imageIdType?: string;
      };
      header: {
        /** Bearer token that needs to be passed which is generated post user authentication */
        authorization: parameters["authKey"];
        /** Pass this header as true, if payload needs DVM */
        externalData?: parameters["externalData"];
        /** Client or Partner's Application Key */
        "x-app-key": parameters["x-app-key"];
        /** Request Id of an incoming request */
        "x-request-id"?: parameters["x-request-id"];
        /** Customer's Integration Application Id */
        "x-originating-application"?: parameters["x-originating-application"];
        /** Mandatory parameter to identify the hotel code where the end user is logged in */
        "x-hotelid": parameters["x-hotelid"];
        /** External system code. */
        "x-externalsystem"?: parameters["x-externalsystem"];
        /** Language code */
        "Accept-Language"?: parameters["Accept-Language"];
      };
    };
    responses: {
      /** HATEOAS links which help the consumer to navigate to resources */
      200: {
        headers: {};
        schema: definitions["status"];
      };
      400: responses["400"];
      401: responses["401"];
      403: responses["403"];
      404: responses["404"];
      405: responses["405"];
      406: responses["406"];
      413: responses["413"];
      414: responses["414"];
      415: responses["415"];
      500: responses["500"];
      502: responses["502"];
      503: responses["503"];
    };
  };
}

export interface external {}
