/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/tokens": {
    /** <p>This is required to access Oracle Hospitality OPERA Cloud REST APIs.  </p><h3>Obtaining a token</h3><p>To obtain a token include the following headers:</p> <ul><li>A Basic authentication header using the base64 hash of your Client ID and Client Secret in the format <code>ClientID:ClientSecret</code> - base64 encoded to the Basic Access Authorization standard</li> <li>Your application key in the <code>x-app-key</code> header</li></ul> <p>And the following body parameters:</p> <h4>Body parameters for obtaining your initial access token</h4> <ul><li><strong>grant_type</strong>.  Required to be "password" or "client_credentials"</strong></li><li><strong>username</strong>.  If grant_type is password, set this to your OPERA Cloud integration username.</strong></li><li><strong>password</strong>.  If grant_type is password, set this to your OPERA Cloud integration user's password.</li> <li><strong>scope</strong>. If grant_type is client_credentials, set this to your assigned scope. </li> </strong></li></ul> <h3>JSON Web Token (JWT)</h3><p> An open standard (<a href="https://tools.ietf.org/html/rfc7519" title="Definition of RFC7519, the standard for JWT tokens">RFC 7519</a>) that defines a compact and self-contained way for securely transmitting information between parties as a JSON object. This information can be verified and trusted because it is digitally signed.</p><p><strong>OperationId:</strong>getToken</p> */
    post: operations["getToken"];
  };
}

export interface definitions {
  /** @description OAuth2 token object sent as a response to the token request */
  OAuth2TokenResponse: {
    /** @description The access token.  Include this in the header for every subsequent request. */
    access_token: string;
    /**
     * Format: int64
     * @description Time in seconds for the access token to expire (typically, 3600 i.e. 60 minutes)
     */
    expires_in?: number;
    /** @description The type of access token issued (Bearer). */
    token_type?: string;
    /** @description Always user_assertion. */
    oracle_tk_context?: string;
  };
}

export interface parameters {
  /** @description Client or Partner's Application Key */
  "x-app-key": string;
  /** @description Global unique ID of the Enterprise. Only while using Client Credentials workflow with OCIM environments, users should pass this header. */
  enterpriseId: string;
}

export interface operations {
  /** <p>This is required to access Oracle Hospitality OPERA Cloud REST APIs.  </p><h3>Obtaining a token</h3><p>To obtain a token include the following headers:</p> <ul><li>A Basic authentication header using the base64 hash of your Client ID and Client Secret in the format <code>ClientID:ClientSecret</code> - base64 encoded to the Basic Access Authorization standard</li> <li>Your application key in the <code>x-app-key</code> header</li></ul> <p>And the following body parameters:</p> <h4>Body parameters for obtaining your initial access token</h4> <ul><li><strong>grant_type</strong>.  Required to be "password" or "client_credentials"</strong></li><li><strong>username</strong>.  If grant_type is password, set this to your OPERA Cloud integration username.</strong></li><li><strong>password</strong>.  If grant_type is password, set this to your OPERA Cloud integration user's password.</li> <li><strong>scope</strong>. If grant_type is client_credentials, set this to your assigned scope. </li> </strong></li></ul> <h3>JSON Web Token (JWT)</h3><p> An open standard (<a href="https://tools.ietf.org/html/rfc7519" title="Definition of RFC7519, the standard for JWT tokens">RFC 7519</a>) that defines a compact and self-contained way for securely transmitting information between parties as a JSON object. This information can be verified and trusted because it is digitally signed.</p><p><strong>OperationId:</strong>getToken</p> */
  getToken: {
    parameters: {
      formData: {
        /** The grant type.  This value will depend on the API you are passing the OAuth token to. */
        grant_type: "password" | "client_credentials";
        /** Your OPERA Cloud integration user name. Required value when requesting a token using the password grant. */
        username?: string;
        /** Your OPERA Cloud integration user password. Required value when requesting a token using the password grant. */
        password?: string;
        /** Your assigned scope. Required value when requesting a token using the client_credentials grant. */
        scope?: string;
      };
      header: {
        /** Client or Partner's Application Key */
        "x-app-key": parameters["x-app-key"];
        /** Global unique ID of the Enterprise. Only while using Client Credentials workflow with OCIM environments, users should pass this header. */
        enterpriseId?: parameters["enterpriseId"];
      };
    };
    responses: {
      /** OK */
      200: {
        schema: definitions["OAuth2TokenResponse"];
      };
      /** Bad Request. This error is returned if the authentication information provided is not valid. */
      400: unknown;
      /** Unauthorized. Invalid client ID, client secret, username, and/or password, and/or scope. */
      401: unknown;
      /** Forbidden. This error is returned if the operation is not allowed for the request. */
      403: unknown;
    };
  };
}

export interface external {}
