/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/externalSystems/{extSystemCode}/hotels/{hotelId}/restrictions": {
    /** A user can send various restrictions to OPERA by specifying restriction details in the request. <p><strong>OperationId:</strong>postRestrictionsProcess</p> */
    post: operations["postRestrictionsProcess"];
  };
  "/externalSystems/{extSystemCode}/hotels/{hotelId}/restrictions/{requestId}": {
    /** Use this to check whether the restrictions sent have been processed. <p><strong>OperationId:</strong>getRestrictions</p> */
    get: operations["getRestrictions"];
    /** Use this to check whether the restrictions sent have been processed. <p><strong>OperationId:</strong>getRestrictionsProcessStatus</p> */
    head: operations["getRestrictionsProcessStatus"];
  };
}

export interface definitions {
  /**
   * Error Detail
   * @description Complex type that contains error details for a REST call.
   */
  exceptionDetailType: {
    /** @description Absolute URI [RFC3986] that identifies the problem type.  When dereferenced, it SHOULD provide a human-readable summary of the problem (for example, using HTML). */
    type?: string;
    /** @description Short, human-readable summary of the problem.  The summary SHOULD NOT change for subsequent occurrences of the problem, except for purposes of localization. */
    title?: string;
    /** @description HTTP status code for this occurrence of the problem, set by the origin server. */
    status?: number;
    /** @description Human-readable description specific to this occurrence of the problem. */
    detail?: string;
    /** @description Absolute URI that identifies the specific occurrence of the problem.  It may or may not provide additional information if dereferenced. */
    instance?: string;
    /** @description Application error code, which is different from HTTP error code. */
    "o:errorCode"?: string;
    /** @description Path to the problem at the resource or property level. */
    "o:errorPath"?: string;
    /** @description Details of the error message, consisting of a hierarchical tree structure. */
    "o:errorDetails"?: definitions["errorInstance"][];
    links?: definitions["links"];
  };
  /**
   * Error Instance Details
   * @description Complex type that contains error instance details for a REST call.
   */
  errorInstance: {
    /** @description Absolute URI [RFC3986] that identifies the problem type.  When dereferenced, it SHOULD provide a human-readable summary of the problem (for example, using HTML). */
    type?: string;
    /** @description Short, human-readable summary of the problem.  The summary SHOULD NOT change for subsequent occurrences of the problem, except for purposes of localization. */
    title?: string;
    /** @description HTTP status code for this occurrence of the problem, set by the origin server. */
    status?: number;
    /** @description Human-readable description specific to this occurrence of the problem. */
    detail?: string;
    /** @description Absolute URI that identifies the specific occurrence of the problem.  It may or may not provide additional information if dereferenced. */
    instance?: string;
    /** @description Application error code, which is different from HTTP error code. */
    "o:errorCode"?: string;
    /** @description Path to the problem at the resource or property level. */
    "o:errorPath"?: string;
  };
  /** @description Metadata describing link description objects that MAY appear in the JSON instance representation. */
  instanceLink: {
    /** @description URI [RFC3986] or URI Template [RFC6570]. If the value is set to URI Template, then the "templated" property must be set to true. */
    href?: string;
    /** @description Name of the link relation that, in addition to the type property, can be used to retrieve link details. For example, href or profile. */
    rel?: string;
    /**
     * @description Boolean flag that specifies that "href" property is a URI or URI Template. If the property is a URI template, set this value to true. By default, this value is false.
     * @default false
     */
    templated?: boolean;
    /**
     * @description HTTP method for requesting the target of the link.
     * @enum {string}
     */
    method?: "GET" | "POST" | "PUT" | "DELETE" | "PATCH" | "OPTIONS" | "HEAD";
    /** @description Link to the metadata of the resource, such as JSON-schema, that describes the resource expected when dereferencing the target resource.. */
    targetSchema?: string;
    /** @description The operationId of the path you can call to follow this link.  This allows you to look up not only the path and method, but the description of that path and any parameters you need to supply. */
    operationId?: string;
    /** @description Exact copy of the "summary" field on the linked operation. */
    title?: string;
  };
  links: definitions["instanceLink"][];
  /** @description Collection of restrictions to be configured. */
  restrictionsType: definitions["createRestrictionType"][];
  createRestrictionType: {
    /** @description Indicates the type of the restriction. */
    restrictionStatus?: definitions["restrictionStatusType"];
    /** @description The rate code for which the restriction will be applied. */
    ratePlanCodes?: string[];
    /** @description The rate class for which the restriction will be applied. */
    rateClasses?: string[];
    /** @description The room class for which the restriction will be applied. */
    roomClasses?: string[];
    /** @description Booking channel. */
    bookingChannels?: string[];
    /** @description The room type for which the restriction will be applied. */
    roomTypes?: string[];
    /** @description The rate category for which the restriction will be applied. */
    ratePlanCategories?: string[];
    /** @description The season code during which the restrictions are valid. */
    seasonCode?: string;
    /** @description Unique block identifier of the block for which restriction will be applied. */
    blockId?: definitions["blockId"];
    /** @description Booking channel on request. */
    bookingChannelOnRequest?: string;
    /**
     * Format: date
     * @description The starting value of the date range.
     */
    dateRangeStart?: string;
    /**
     * Format: date
     * @description The ending value of the date range.
     */
    dateRangeEnd?: string;
    sunday?: boolean;
    monday?: boolean;
    tuesday?: boolean;
    wednesday?: boolean;
    thursday?: boolean;
    friday?: boolean;
    saturday?: boolean;
    /** @description Yield status condition. */
    yieldStatus?: definitions["roomTypeYieldableType"];
  };
  /**
   * @description Simple type for Yieldable or Non Yieldable
   * @enum {string}
   */
  roomTypeYieldableType: "Yieldable" | "NonYieldable";
  /** @description An identifier used to uniquely reference an object in a system (e.g. an airline reservation reference, customer profile reference, booking confirmation number, or a reference to a previous availability quote). */
  blockId: {
    /** @description A unique identifying value assigned by the creating system. The ID attribute may be used to reference a primary-key value within a database or in a particular implementation. */
    id?: string;
  };
  /** @description The RestrictionStatusType is used to indicate the type of restriction applied. An enumerated restriction type is defined in the attribute group. */
  restrictionStatusType: {
    /** @description Identifies the type of restriction. I.E. Closed, ClosedForArrival, etc. */
    code?: definitions["restrictionStatusesType"];
    /** @description Defines restriction in conjunction with Restriction Code. Value must be specified for Restriction Codes MinimumStayThrough, MaximumStayThrough, MinimumLengthOfStay, MaximumLengthOfStay, MinimumAdvanceBooking, MaximumAdvanceBooking. */
    unit?: number;
    /** @description Indicates Length of Stay 1 is not available. Defines restriction in conjunction with Restriction Code LengthOfStayNotAvailable. */
    lengthOfStay1?: boolean;
    /** @description Indicates Length of Stay 2 is not available. Defines restriction in conjunction with Restriction Code LengthOfStayNotAvailable. */
    lengthOfStay2?: boolean;
    /** @description Indicates Length of Stay 3 is not available. Defines restriction in conjunction with Restriction Code LengthOfStayNotAvailable. */
    lengthOfStay3?: boolean;
    /** @description Indicates Length of Stay 4 is not available. Defines restriction in conjunction with Restriction Code LengthOfStayNotAvailable. */
    lengthOfStay4?: boolean;
    /** @description Indicates Length of Stay 5 is not available. Defines restriction in conjunction with Restriction Code LengthOfStayNotAvailable. */
    lengthOfStay5?: boolean;
    /** @description Indicates Length of Stay 6 is not available. Defines restriction in conjunction with Restriction Code LengthOfStayNotAvailable. */
    lengthOfStay6?: boolean;
    /** @description Indicates Length of Stay 7 or more is not available. Defines restriction in conjunction with Restriction Code LengthOfStayNotAvailable. */
    lengthOfStay7?: boolean;
  };
  /** @enum {string} */
  restrictionStatusesType:
    | "Closed"
    | "ClosedForArrival"
    | "ClosedForDeparture"
    | "MinimumStayThrough"
    | "MaximumStayThrough"
    | "MinimumLengthOfStay"
    | "MaximumLengthOfStay"
    | "LengthOfStayNotAvailable"
    | "MinimumAdvanceBooking"
    | "MaximumAdvanceBooking"
    | "Open"
    | "OpenForArrival"
    | "OpenForDeparture";
  /** @description Used in conjunction with the Success element to define a business error. */
  warningsType: definitions["warningType"][];
  /** @description Used when a message has been successfully processed to report any warnings or business errors that occurred. */
  warningType: {
    /** @description Property Value */
    value?: string;
    /** @description An abbreviated version of the error in textual format. */
    shortText?: string;
    /** @description If present, this refers to a table of coded values exchanged between applications to identify errors or warnings. */
    code?: string;
    /** @description If present, this URL refers to an online description of the error that occurred. */
    docURL?: string;
    /** @description If present, recommended values are those enumerated in the ErrorRS, (NotProcessed Incomplete Complete Unknown) however, the data type is designated as string data, recognizing that trading partners may identify additional status conditions not included in the enumeration. */
    status?: string;
    /** @description If present, this attribute may identify an unknown or misspelled tag that caused an error in processing. It is recommended that the Tag attribute use XPath notation to identify the location of a tag in the event that more than one tag of the same name is present in the document. Alternatively, the tag name alone can be used to identify missing data [Type=ReqFieldMissing]. */
    tag?: string;
    /** @description If present, this attribute allows for batch processing and the identification of the record that failed amongst a group of records. This value may contain a concatenation of a unique failed transaction ID with specific record(s) associated with that transaction. */
    recordId?: string;
    /** @description The Warning element MUST contain the Type attribute that uses a recommended set of values to indicate the warning type. The validating XSD can expect to accept values that it has NOT been explicitly coded for and process them by using Type ="Unknown". */
    type?: string;
    /** @description Language identification. */
    language?: string;
    /** @description Reference Place Holder used as an index for this warning. */
    rph?: string;
  };
  /** @description Request for configuring restrictions. */
  restrictions: {
    /** @description Restrictions to be configured. */
    restrictions?: definitions["restrictionsType"];
    links?: definitions["links"];
  };
  /** @description Response for created restrictions status. */
  restrictionsStatus: {
    /** @description List of warnings that occurred. */
    warnings?: definitions["warningsType"];
    links?: definitions["links"];
  };
}

export interface parameters {
  /** @description Pass this header as true, if payload needs DVM */
  externalData: string;
  /** @description Bearer token that needs to be passed which is generated post user authentication */
  authKey: string;
  /** @description Client or Partner's Application Key */
  "x-app-key": string;
  /** @description Request Id of an incoming request */
  "x-request-id": string;
  /** @description Customer's Integration Application Id */
  "x-originating-application": string;
  /** @description Mandatory parameter to identify the hotel code where the end user is logged in */
  "x-hotelid": string;
  /** @description Language code */
  "Accept-Language": string;
}

export interface responses {
  /** Bad Request */
  400: {
    schema: definitions["exceptionDetailType"];
  };
  /** Unauthorized */
  401: unknown;
  /** Forbidden */
  403: unknown;
  /** Resource not found */
  404: {
    schema: definitions["exceptionDetailType"];
  };
  /** Method not allowed */
  405: unknown;
  /** Not acceptable. */
  406: unknown;
  /** Request Entity Too Large */
  413: unknown;
  /** Request URI Too Large */
  414: unknown;
  /** Unsupported Media Type */
  415: unknown;
  /** System Error */
  500: {
    schema: definitions["exceptionDetailType"];
  };
  /** Bad Gateway */
  502: unknown;
  /** Service Unavailable */
  503: unknown;
}

export interface operations {
  /** A user can send various restrictions to OPERA by specifying restriction details in the request. <p><strong>OperationId:</strong>postRestrictionsProcess</p> */
  postRestrictionsProcess: {
    parameters: {
      path: {
        /** Unique ID of the hotel in OPERA */
        hotelId: string;
        /** Unique code of the external system */
        extSystemCode: string;
      };
      body: {
        /** Request for configuring restrictions. */
        restrictions: definitions["restrictions"];
      };
      header: {
        /** Bearer token that needs to be passed which is generated post user authentication */
        authorization: parameters["authKey"];
        /** Pass this header as true, if payload needs DVM */
        externalData?: parameters["externalData"];
        /** Client or Partner's Application Key */
        "x-app-key": parameters["x-app-key"];
        /** Request Id of an incoming request */
        "x-request-id"?: parameters["x-request-id"];
        /** Customer's Integration Application Id */
        "x-originating-application"?: parameters["x-originating-application"];
        /** Mandatory parameter to identify the hotel code where the end user is logged in */
        "x-hotelid": parameters["x-hotelid"];
        /** Language code */
        "Accept-Language"?: parameters["Accept-Language"];
      };
    };
    responses: {
      /** HATEOAS links which help the consumer to navigate to resources */
      202: {
        headers: {};
        schema: definitions["links"];
      };
      400: responses["400"];
      401: responses["401"];
      403: responses["403"];
      404: responses["404"];
      405: responses["405"];
      406: responses["406"];
      413: responses["413"];
      414: responses["414"];
      415: responses["415"];
      500: responses["500"];
      502: responses["502"];
      503: responses["503"];
    };
  };
  /** Use this to check whether the restrictions sent have been processed. <p><strong>OperationId:</strong>getRestrictions</p> */
  getRestrictions: {
    parameters: {
      path: {
        /** Unique ID of Hotel in OPERA. */
        hotelId: string;
        /** Unique code of the external system. */
        extSystemCode: string;
        /** Unique ID to fetch status of created restrictions. */
        requestId: string;
      };
      header: {
        /** Bearer token that needs to be passed which is generated post user authentication */
        authorization: parameters["authKey"];
        /** Pass this header as true, if payload needs DVM */
        externalData?: parameters["externalData"];
        /** Client or Partner's Application Key */
        "x-app-key": parameters["x-app-key"];
        /** Request Id of an incoming request */
        "x-request-id"?: parameters["x-request-id"];
        /** Customer's Integration Application Id */
        "x-originating-application"?: parameters["x-originating-application"];
        /** Mandatory parameter to identify the hotel code where the end user is logged in */
        "x-hotelid": parameters["x-hotelid"];
        /** Language code */
        "Accept-Language"?: parameters["Accept-Language"];
      };
    };
    responses: {
      /** HATEOAS links which help the consumer to navigate to resources */
      200: {
        headers: {};
        schema: definitions["restrictionsStatus"];
      };
      400: responses["400"];
      401: responses["401"];
      403: responses["403"];
      404: responses["404"];
      405: responses["405"];
      406: responses["406"];
      413: responses["413"];
      414: responses["414"];
      415: responses["415"];
      500: responses["500"];
      502: responses["502"];
      503: responses["503"];
    };
  };
  /** Use this to check whether the restrictions sent have been processed. <p><strong>OperationId:</strong>getRestrictionsProcessStatus</p> */
  getRestrictionsProcessStatus: {
    parameters: {
      path: {
        /** Unique ID to fetch status of created restrictions. */
        requestId: string;
        /** Unique code of the external system. */
        extSystemCode: string;
        /** Unique ID of Hotel in OPERA. */
        hotelId: string;
      };
      header: {
        /** Bearer token that needs to be passed which is generated post user authentication */
        authorization: parameters["authKey"];
        /** Pass this header as true, if payload needs DVM */
        externalData?: parameters["externalData"];
        /** Client or Partner's Application Key */
        "x-app-key": parameters["x-app-key"];
        /** Request Id of an incoming request */
        "x-request-id"?: parameters["x-request-id"];
        /** Customer's Integration Application Id */
        "x-originating-application"?: parameters["x-originating-application"];
        /** Mandatory parameter to identify the hotel code where the end user is logged in */
        "x-hotelid": parameters["x-hotelid"];
        /** Language code */
        "Accept-Language"?: parameters["Accept-Language"];
      };
    };
    responses: {
      /** Response for status of scheduled asynchronous process. */
      200: unknown;
      /** Response for status of scheduled asynchronous process. */
      201: unknown;
      400: responses["400"];
      401: responses["401"];
      403: responses["403"];
      404: responses["404"];
      405: responses["405"];
      406: responses["406"];
      413: responses["413"];
      414: responses["414"];
      415: responses["415"];
      500: responses["500"];
      502: responses["502"];
      503: responses["503"];
    };
  };
}

export interface external {}
