/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/hotels/{hotelId}/departureStartDate/{departureStartDate}/departureEndDate/{departureEndDate}/reservationRotationPoints": {
    /** This API will allow a user to retrieve list of reservations and the number of rotation points associated with a given reservation for requested hotel, departure start date, departure end date, and room numbers. <p><strong>OperationId:</strong>getReservationRotationPoints</p> <p>This API allows a time span of <strong>30</strong> days.</p> */
    get: operations["getReservationRotationPoints"];
  };
  "/hotels/{hotelId}/reservations/{reservationId}/rooms/{roomId}/reservationRotationPointsDetails": {
    /** This API will allow a user to retrieve list of rotation points details along with adjustment log for requested hotel, reservation Id and room number. <p><strong>OperationId:</strong>getReservationRotationPointsDetails</p> */
    get: operations["getReservationRotationPointsDetails"];
    /** This API will allow a user to modify rotation points for the requested hotel, reservation Id and room number. <p><strong>OperationId:</strong>putReservationRotationPointsDetails</p> */
    put: operations["putReservationRotationPointsDetails"];
  };
  "/hotels/{hotelId}/roomRotationPoints": {
    /** Use this API to fetch the individual units' rotation points.<p><strong>OperationId:</strong>getRoomRotationPoints</p> <p>The maximum allowable limit for this API is <strong>100</strong>.</p> */
    get: operations["getRoomRotationPoints"];
    /** Use this operation to update balance forward and adjusted points of individual rooms. <p><strong>OperationId:</strong>putRoomRotationPoints</p> */
    put: operations["putRoomRotationPoints"];
  };
  "/profiles/{profileId}/roomOwnerships": {
    /** Use this API to fetch profile Rooms with Room Ownership or Owner Referral records associated. <p><strong>OperationId:</strong>getRoomOwnerships</p> */
    get: operations["getRoomOwnerships"];
  };
  "/roomOwners": {
    /** Get Room Ownership details for specific room(s) or owners. Hotel Id(s) and at least one other search criteria is required. <p><strong>OperationId:</strong>getRoomOwners</p> */
    get: operations["getRoomOwners"];
  };
  "/services/roomrotation/status": {
    /** This API facilitates status check of room rotation service <p><strong>OperationId:</strong>pingRoomRotationService</p> */
    get: operations["pingRoomRotationService"];
  };
}

export interface definitions {
  /** @description Response Body. */
  status: {
    warnings?: definitions["warningsType"];
    links?: definitions["links"];
  };
  /** @description Used in conjunction with the Success element to define a business error. */
  warningsType: definitions["warningType"][];
  /** @description Used when a message has been successfully processed to report any warnings or business errors that occurred. */
  warningType: {
    /** @description Property Value */
    value?: string;
    /** @description An abbreviated version of the error in textual format. */
    shortText?: string;
    /** @description If present, this refers to a table of coded values exchanged between applications to identify errors or warnings. */
    code?: string;
    /** @description If present, this URL refers to an online description of the error that occurred. */
    docURL?: string;
    /** @description If present, recommended values are those enumerated in the ErrorRS, (NotProcessed Incomplete Complete Unknown) however, the data type is designated as string data, recognizing that trading partners may identify additional status conditions not included in the enumeration. */
    status?: string;
    /** @description If present, this attribute may identify an unknown or misspelled tag that caused an error in processing. It is recommended that the Tag attribute use XPath notation to identify the location of a tag in the event that more than one tag of the same name is present in the document. Alternatively, the tag name alone can be used to identify missing data [Type=ReqFieldMissing]. */
    tag?: string;
    /** @description If present, this attribute allows for batch processing and the identification of the record that failed amongst a group of records. This value may contain a concatenation of a unique failed transaction ID with specific record(s) associated with that transaction. */
    recordId?: string;
    /** @description The Warning element MUST contain the Type attribute that uses a recommended set of values to indicate the warning type. The validating XSD can expect to accept values that it has NOT been explicitly coded for and process them by using Type ="Unknown". */
    type?: string;
    /** @description Language identification. */
    language?: string;
    /** @description Reference Place Holder used as an index for this warning. */
    rph?: string;
  };
  links: definitions["instanceLink"][];
  /** @description Metadata describing link description objects that MAY appear in the JSON instance representation. */
  instanceLink: {
    /** @description URI [RFC3986] or URI Template [RFC6570]. If the value is set to URI Template, then the "templated" property must be set to true. */
    href?: string;
    /** @description Name of the link relation that, in addition to the type property, can be used to retrieve link details. For example, href or profile. */
    rel?: string;
    /**
     * @description Boolean flag that specifies that "href" property is a URI or URI Template. If the property is a URI template, set this value to true. By default, this value is false.
     * @default false
     */
    templated?: boolean;
    /**
     * @description HTTP method for requesting the target of the link.
     * @enum {string}
     */
    method?: "GET" | "POST" | "PUT" | "DELETE" | "PATCH" | "OPTIONS" | "HEAD";
    /** @description Link to the metadata of the resource, such as JSON-schema, that describes the resource expected when dereferencing the target resource.. */
    targetSchema?: string;
    /** @description The operationId of the path you can call to follow this link.  This allows you to look up not only the path and method, but the description of that path and any parameters you need to supply. */
    operationId?: string;
    /** @description Exact copy of the "summary" field on the linked operation. */
    title?: string;
  };
  /**
   * Error Detail
   * @description Complex type that contains error details for a REST call.
   */
  exceptionDetailType: {
    /** @description Absolute URI [RFC3986] that identifies the problem type.  When dereferenced, it SHOULD provide a human-readable summary of the problem (for example, using HTML). */
    type: string;
    /** @description Short, human-readable summary of the problem.  The summary SHOULD NOT change for subsequent occurrences of the problem, except for purposes of localization. */
    title: string;
    /** @description HTTP status code for this occurrence of the problem, set by the origin server. */
    status?: number;
    /** @description Human-readable description specific to this occurrence of the problem. */
    detail?: string;
    /** @description Absolute URI that identifies the specific occurrence of the problem.  It may or may not provide additional information if dereferenced. */
    instance?: string;
    /** @description Application error code, which is different from HTTP error code. */
    "o:errorCode"?: string;
    /** @description Path to the problem at the resource or property level. */
    "o:errorPath"?: string;
    /** @description Details of the error message, consisting of a hierarchical tree structure. */
    "o:errorDetails"?: definitions["errorInstance"][];
    links?: definitions["links"];
  };
  /**
   * Error Instance Details
   * @description Complex type that contains error instance details for a REST call.
   */
  errorInstance: {
    /** @description Absolute URI [RFC3986] that identifies the problem type.  When dereferenced, it SHOULD provide a human-readable summary of the problem (for example, using HTML). */
    type: string;
    /** @description Short, human-readable summary of the problem.  The summary SHOULD NOT change for subsequent occurrences of the problem, except for purposes of localization. */
    title: string;
    /** @description HTTP status code for this occurrence of the problem, set by the origin server. */
    status?: number;
    /** @description Human-readable description specific to this occurrence of the problem. */
    detail?: string;
    /** @description Absolute URI that identifies the specific occurrence of the problem.  It may or may not provide additional information if dereferenced. */
    instance?: string;
    /** @description Application error code, which is different from HTTP error code. */
    "o:errorCode"?: string;
    /** @description Path to the problem at the resource or property level. */
    "o:errorPath"?: string;
  };
  getRoomRotationPoints: {
    /** @description List of Room Rotation Points Information. */
    roomRotationPointsInfoList?: definitions["roomRotationPointsInfoType"][];
    /** @description Indicates whether Out of Order/ Out of Service Room Rotation Points is active */
    outOfOrderServiceActive?: boolean;
    /**
     * Format: date
     * @description Start date of the Room Rotation Period
     */
    startRoomRotationPeriodDate?: string;
    /**
     * Format: date
     * @description End date of the Room Rotation Period
     */
    endRoomRotationPeriodDate?: string;
    /** @description Indicates whether the balance forward is active */
    balanceForwardActive?: boolean;
    /** @description Indicates whether the user is allowed to edit balance forward points */
    balanceForwardEditable?: boolean;
    /** @description Indicates the index of the next applicable set(page). */
    offset?: number;
    /** @description Indicates number of records the API can return as per the API request limit sent. */
    limit?: number;
    /** @description Indicates number of records the API has returned actually as per the API request criteria. */
    count?: number;
    /** @description Indicates whether there are more records available to be returned as per the API request criteria or not. */
    hasMore?: boolean;
    /** @description Indicates total number of records available that can be returned as per the API request criteria. */
    totalResults?: number;
    links?: definitions["links"];
    warnings?: definitions["warningsType"];
  };
  /** @description Room Rotation Points Information */
  roomRotationPointsInfoType: {
    /** @description Room Number */
    roomId?: string;
    /** @description Out of Order / Out of Service points */
    outOfOrderServicePoints?: number;
    /** @description Balance forward points */
    balanceForwardPoints?: number;
    /** @description Room adjusted points */
    roomAdjustedPoints?: number;
    /** @description Reservation adjusted points */
    reservationAdjustedPoints?: number;
    /** @description Random points */
    randomPoints?: number;
    /** @description Calculated points */
    calculatedPoints?: number;
    /** @description Prorated average points */
    proratedAveragePoints?: number;
    /** @description Forecasted points */
    forecastedPoints?: number;
  };
  roomRotationPointsAdjustment: {
    /** @description List of Room Rotation Points Information to update */
    roomRotationPointsAdjustmentInfoTypeList?: definitions["roomRotationPointsAdjustmentInfoType"][];
    links?: definitions["links"];
    warnings?: definitions["warningsType"];
  };
  /** @description Room Rotation Points Update Information */
  roomRotationPointsAdjustmentInfoType: {
    /** @description Room Number */
    roomId?: string;
    /** @description Balance forward points to update */
    balanceForwardPoints?: number;
    /** @description Room adjusted points to update */
    roomAdjustedPoints?: number;
  };
  /** @description Provides Pagination Information for the REST API. */
  getReservationRotationPoints: definitions["rESTPaginationGroup"] & {
    /** @description Collection of reservation and associated rotation points details. */
    reservationRotationPoints?: definitions["reservationRotationPointsType"][];
  };
  /** @description Provides Pagination Information for the REST API. */
  rESTPaginationGroup: {
    /** @description Indicates the index of the next applicable set(page). */
    offset?: number;
    /** @description Indicates number of records the API can return as per the API request limit sent. A maximum of 200 records can be only returned at a time. */
    limit?: number;
    /** @description Indicates number of records the API has returned actually as per the API request criteria. */
    count?: number;
    /** @description Indicates whether there are more records available to be returned as per the API request criteria or not. */
    hasMore?: boolean;
    /** @description Indicates total number of records available that can be returned as per the API request criteria. */
    totalResults?: number;
  };
  /** @description Individual reservation and associated rotation points information */
  reservationRotationPointsType: {
    /** @description Room Number */
    roomId?: string;
    /**
     * Format: date
     * @description Reservation arrival date
     */
    arrivalDate?: string;
    /**
     * Format: date
     * @description Reservation departure date
     */
    departureDate?: string;
    /** @description The number of nights of the reservation. */
    nights?: number;
    /** @description Unique identifier of the reservation like Reservation Name Id, Confirmation Number. */
    reservationIdList?: definitions["uniqueID_Type"][];
    /** @description Unique identifier of the guest. */
    profileId?: definitions["profileId"];
    /** @description The guest name on the reservation. */
    guestName?: string;
    /** @description Total rotation points for the room. */
    totalPoints?: number;
    /** @description Whether rotation points for the room have been adjusted. */
    pointsAdjusted?: boolean;
  };
  /** @description An identifier used to uniquely reference an object in a system (e.g. an airline reservation reference, customer profile reference, booking confirmation number, or a reference to a previous availability quote). */
  profileId: {
    /** @description A reference to the type of object defined by the UniqueID element. */
    type?: string;
    /** @description A unique identifying value assigned by the creating system. The ID attribute may be used to reference a primary-key value within a database or in a particular implementation. */
    id?: string;
    /** @description Additional identifying value assigned by the creating system. */
    idExtension?: number;
  };
  /** @description An identifier used to uniquely reference an object in a system (e.g. an airline reservation reference, customer profile reference, booking confirmation number, or a reference to a previous availability quote). */
  uniqueID_Type: {
    /** @description A unique identifying value assigned by the creating system. The ID attribute may be used to reference a primary-key value within a database or in a particular implementation. */
    id?: string;
    /** @description A reference to the type of object defined by the UniqueID element. */
    type?: string;
  };
  /** @description Associated Room Ownerships List */
  associatedRoomOwnershipListDetails: {
    /** @description List of Associated Room Ownerships */
    associatedRoomOwnershipInfoTypeList?: definitions["associatedRoomOwnershipInfoType"][];
    links?: definitions["links"];
    warnings?: definitions["warningsType"];
  };
  /** @description Associated Room Ownership Information */
  associatedRoomOwnershipInfoType: {
    /** @description Unique Id for Room Owner record. */
    roomOwnershipId?: number;
    /** @description Hotel Id */
    hotelId?: string;
    /** @description Room Number */
    roomId?: string;
    /** @description Room Type */
    roomType?: string;
    /**
     * Format: date
     * @description Start date of Room Ownership contract
     */
    startDate?: string;
    /**
     * Format: date
     * @description End date of Room Ownership contract
     */
    endDate?: string;
    /** @description Whether Room is available for the exclusive use of its designated owner and owner referrals, or if it is available in general availability */
    ownerExclusive?: boolean;
    /** @description Whether the associated room is an Owner or Referral. */
    associatedRoomOwnershipType?: definitions["associatedRoomOwnershipType"];
  };
  /**
   * @description Indicates if the associated room is an Owner or Referral room.
   * @enum {string}
   */
  associatedRoomOwnershipType: "Owner" | "Referral";
  /** @description Reservation Details */
  reservationDetailsType: {
    /** @description Hotel Id */
    hotelId?: string;
    /** @description Unique identifier of the reservation like Reservation Name Id, Confirmation Number. */
    reservationIdList?: definitions["uniqueID_Type"][];
    /**
     * Format: date
     * @description Reservation arrival date
     */
    arrival?: string;
    /**
     * Format: date
     * @description Reservation departure date
     */
    departure?: string;
    /** @description The number of nights of the reservation. */
    nights?: number;
    /** @description Room Number */
    roomId?: string;
    /** @description Unique identifier of the guest. */
    profileId?: definitions["profileId"];
    /** @description Family name, last name. */
    surname?: string;
    /** @description Given name, first name or names */
    givenName?: string;
  };
  /** @description Rotation Points Details of a reservation */
  reservationRotationPointsDetailsType: {
    /**
     * Format: date
     * @description Start date of reservation
     */
    startDate?: string;
    /**
     * Format: date
     * @description End date of reservation
     */
    endDate?: string;
    /** @description Represents calculation type for rotation point rule. */
    type?: definitions["rotationRuleCalculationRuleType"];
    /** @description Current applicable points for the shown calculation rule for the reservation. */
    currentPoints?: number;
    /** @description Override the current points and enter a new value for the respective calculation rule up to 5 decimal places. */
    adjustPointsTo?: number;
    /** @description Reason for the adjustment to the rotation points. */
    adjustmentReason?: definitions["reservationRotationPointsAdjustmentReasonType"];
  };
  /**
   * @description Simple type for Rotation Rule Calculation Rule.
   * @enum {string}
   */
  rotationRuleCalculationRuleType:
    | "PerRevenue"
    | "PerNight"
    | "PerStay"
    | "AvgRateAmount";
  /** @description Contains adjustment reason code and description. */
  reservationRotationPointsAdjustmentReasonType: {
    /** @description Code. */
    code?: string;
    /** @description Description of the code. */
    description?: string;
  };
  /** @description Reservation Rotation points details with total points. */
  reservationRotationPointsDetailsListType: {
    /** @description Collection of reservation rotation points details. */
    reservationRotationPointsDetails?: definitions["reservationRotationPointsDetailsType"][];
    /** @description Total points including any applied adjustments. */
    totalReservationPoints?: number;
  };
  /** @description Reservation rotation points adjustment log. */
  reservationRotationPointsAdjustmentLogType: {
    /**
     * Format: date-time
     * @description The date and time that the adjustment was made to the rotation points for the room.
     */
    logDate?: string;
    /** @description The type of the calculation rule that was overridden with a new point value. */
    type?: definitions["rotationRuleCalculationRuleType"];
    /** @description Unique application user ID. */
    userId?: definitions["uniqueID_Type"];
    /** @description Unique application login of the user who made the adjustment. */
    userName?: string;
    /** @description The points that were applicable for the specific calculation rule before the change of points. */
    originalPoints?: number;
    /** @description The number of points for the specific calculation rule after the change of points. */
    adjustedPointsTo?: number;
    /** @description The code and description associated with the reason the adjustment was made. */
    adjustmentReason?: definitions["reservationRotationPointsAdjustmentReasonType"];
  };
  /** @description Reservation rotation points adjustment log. */
  reservationRotationPointsAdjustmentLogListType: {
    /** @description Collection of reservation rotation points adjustment log. */
    adjustmentLog?: definitions["reservationRotationPointsAdjustmentLogType"][];
  };
  /** @description Response object for Reservation Rotation Points Details. */
  getReservationRotationPointsDetails: {
    reservationDetails?: definitions["reservationDetailsType"];
    reservationRotationPointsDetailsList?: definitions["reservationRotationPointsDetailsListType"];
    adjustmentLogList?: definitions["reservationRotationPointsAdjustmentLogListType"];
    links?: definitions["links"];
    warnings?: definitions["warningsType"];
  };
  /** @description Collection of Reservation Rotation Points Details. */
  putReservationRotationPointsDetails: {
    reservationRotationPointsDetailsList?: definitions["reservationRotationPointsDetailsListType"];
    links?: definitions["links"];
    warnings?: definitions["warningsType"];
  };
  /** @description Provides Pagination Information for the REST API. */
  roomOwnersListDetails: definitions["rESTPaginationGroup"] & {
    /** @description Collection of Room Owners with Room Ownership details. */
    roomOwnerInfoTypeList?: definitions["roomOwnerInfoType"][];
    links?: definitions["links"];
    warnings?: definitions["warningsType"];
  };
  /** @description Room Owners with Room Ownership details. */
  roomOwnerInfoType: {
    /** @description Hotel Code of Room Ownership record. */
    hotelId?: string;
    /** @description Unique Id for Room Ownership record. */
    roomOwnershipId?: number;
    /** @description Contract number for Room Ownership record. */
    contractNumber?: string;
    /**
     * Format: date
     * @description Start Date of the Room Ownership record.
     */
    startDate?: string;
    /**
     * Format: date
     * @description End Date of the Room Ownership record.
     */
    endDate?: string;
    /** @description Room Id of Room Ownership record. */
    roomId?: string;
    /** @description Room Type of the Room Ownership record. */
    roomType?: string;
    /** @description Unique identifier of the Room Owner. */
    profileId?: definitions["uniqueID_Type"];
    /** @description Display Name for the Room Owner. */
    ownerDisplayName?: string;
    /** @description Indicates whether Room is available for the exclusive use of its designated owner and owner referrals, or if it is available in general availability. */
    ownerExclusive?: boolean;
    /** @description Indicates if the Room Owner is inactive. */
    inactive?: boolean;
  };
  /** @description Current Opera Version Number */
  operaVersionNumberType: string;
  /** @description Response for Ping operation. */
  pingDetail: {
    /** @description Opera version number. */
    operaVersion?: definitions["operaVersionNumberType"];
    links?: definitions["links"];
    warnings?: definitions["warningsType"];
  };
}

export interface parameters {
  /** @description Pass this header as true, if payload needs DVM */
  externalData: string;
  /** @description Bearer token that needs to be passed which is generated post user authentication */
  authKey: string;
  /** @description Client or Partner's Application Key */
  "x-app-key": string;
  /** @description Request Id of an incoming request */
  "x-request-id": string;
  /** @description Customer's Integration Application Id */
  "x-originating-application": string;
  /** @description Mandatory parameter to identify the hotel code where the end user is logged in */
  "x-hotelid": string;
  /** @description External system code. */
  "x-externalsystem": string;
  /** @description Language code */
  "Accept-Language": string;
}

export interface responses {
  /** Bad Request */
  400: {
    schema: definitions["exceptionDetailType"];
  };
  /** Unauthorized */
  401: unknown;
  /** Forbidden */
  403: unknown;
  /** Resource not found */
  404: {
    schema: definitions["exceptionDetailType"];
  };
  /** Method not allowed */
  405: unknown;
  /** Not acceptable. */
  406: unknown;
  /** Request Entity Too Large */
  413: unknown;
  /** Request URI Too Large */
  414: unknown;
  /** Unsupported Media Type */
  415: unknown;
  /** System Error */
  500: {
    schema: definitions["exceptionDetailType"];
  };
  /** Bad Gateway */
  502: unknown;
  /** Service Unavailable */
  503: unknown;
}

export interface operations {
  /** This API will allow a user to retrieve list of reservations and the number of rotation points associated with a given reservation for requested hotel, departure start date, departure end date, and room numbers. <p><strong>OperationId:</strong>getReservationRotationPoints</p> <p>This API allows a time span of <strong>30</strong> days.</p> */
  getReservationRotationPoints: {
    parameters: {
      path: {
        /** Unique Id for the Hotel */
        hotelId: string;
        /** Departure Start Date of the reservation to be searched. */
        departureStartDate: string;
        /** Departure End Date of the reservation to be searched. */
        departureEndDate: string;
      };
      query: {
        /** List of Room Ids for which to return Reservation Rotation Points. */
        roomIds: string[];
        /** A unique identifying value assigned by the creating system. The ID attribute may be used to reference a primary-key value within a database or in a particular implementation. */
        confirmationNumber?: string;
        /** Family name, last name. */
        surname?: string;
        /** Given name, first name or names */
        givenName?: string;
        /** Indicates maximum number of records a Web Service should return. */
        limit?: number;
        /** Index or initial index of the set(page) being requested. If the index goes out of the bounds of the total set count then no data will be returned. */
        offset?: number;
      };
      header: {
        /** Bearer token that needs to be passed which is generated post user authentication */
        authorization: parameters["authKey"];
        /** Pass this header as true, if payload needs DVM */
        externalData?: parameters["externalData"];
        /** Client or Partner's Application Key */
        "x-app-key": parameters["x-app-key"];
        /** Request Id of an incoming request */
        "x-request-id"?: parameters["x-request-id"];
        /** Customer's Integration Application Id */
        "x-originating-application"?: parameters["x-originating-application"];
        /** Mandatory parameter to identify the hotel code where the end user is logged in */
        "x-hotelid": parameters["x-hotelid"];
        /** External system code. */
        "x-externalsystem"?: parameters["x-externalsystem"];
        /** Language code */
        "Accept-Language"?: parameters["Accept-Language"];
      };
    };
    responses: {
      /** Response object for fetching Reservation Rotation Points. Based on the criteria, reservations and associated rotation points are returned. */
      200: {
        headers: {};
        schema: definitions["getReservationRotationPoints"];
      };
      /** Reservation Rotation Points not found. */
      204: never;
      400: responses["400"];
      401: responses["401"];
      403: responses["403"];
      404: responses["404"];
      405: responses["405"];
      406: responses["406"];
      413: responses["413"];
      414: responses["414"];
      415: responses["415"];
      500: responses["500"];
      502: responses["502"];
      503: responses["503"];
    };
  };
  /** This API will allow a user to retrieve list of rotation points details along with adjustment log for requested hotel, reservation Id and room number. <p><strong>OperationId:</strong>getReservationRotationPointsDetails</p> */
  getReservationRotationPointsDetails: {
    parameters: {
      path: {
        /** Unique Id of the Hotel for the reservation. */
        hotelId: string;
        /** Unique OPERA reservation ID which is used to find reservation from OPERA. This ID is a primary identification of a reservation in OPERA. */
        reservationId: string;
        /** Room number of the reservation. */
        roomId: string;
      };
      query: {
        /** Include adjustment log details in the response. */
        includeAdjustmentLog?: boolean;
      };
      header: {
        /** Bearer token that needs to be passed which is generated post user authentication */
        authorization: parameters["authKey"];
        /** Pass this header as true, if payload needs DVM */
        externalData?: parameters["externalData"];
        /** Client or Partner's Application Key */
        "x-app-key": parameters["x-app-key"];
        /** Request Id of an incoming request */
        "x-request-id"?: parameters["x-request-id"];
        /** Customer's Integration Application Id */
        "x-originating-application"?: parameters["x-originating-application"];
        /** Mandatory parameter to identify the hotel code where the end user is logged in */
        "x-hotelid": parameters["x-hotelid"];
        /** External system code. */
        "x-externalsystem"?: parameters["x-externalsystem"];
        /** Language code */
        "Accept-Language"?: parameters["Accept-Language"];
      };
    };
    responses: {
      /** Response object for fetching Reservation Rotation Points Details. Rotation points details with adjustment log are returned for the requested hotel, reservation Id and room number. */
      200: {
        headers: {};
        schema: definitions["getReservationRotationPointsDetails"];
      };
      /** Reservation Rotation Points Details not found. */
      204: never;
      400: responses["400"];
      401: responses["401"];
      403: responses["403"];
      404: responses["404"];
      405: responses["405"];
      406: responses["406"];
      413: responses["413"];
      414: responses["414"];
      415: responses["415"];
      500: responses["500"];
      502: responses["502"];
      503: responses["503"];
    };
  };
  /** This API will allow a user to modify rotation points for the requested hotel, reservation Id and room number. <p><strong>OperationId:</strong>putReservationRotationPointsDetails</p> */
  putReservationRotationPointsDetails: {
    parameters: {
      path: {
        /** Unique Id of the Hotel for the reservation. */
        hotelId: string;
        /** Unique OPERA reservation ID which is used to find reservation from OPERA. This ID is a primary identification of a reservation in OPERA. */
        reservationId: string;
        /** Room number of the reservation. */
        roomId: string;
      };
      body: {
        /** Collection of Reservation Rotation Points Details */
        reservationRotationPoints: definitions["putReservationRotationPointsDetails"];
      };
      header: {
        /** Bearer token that needs to be passed which is generated post user authentication */
        authorization: parameters["authKey"];
        /** Pass this header as true, if payload needs DVM */
        externalData?: parameters["externalData"];
        /** Client or Partner's Application Key */
        "x-app-key": parameters["x-app-key"];
        /** Request Id of an incoming request */
        "x-request-id"?: parameters["x-request-id"];
        /** Customer's Integration Application Id */
        "x-originating-application"?: parameters["x-originating-application"];
        /** Mandatory parameter to identify the hotel code where the end user is logged in */
        "x-hotelid": parameters["x-hotelid"];
        /** External system code. */
        "x-externalsystem"?: parameters["x-externalsystem"];
        /** Language code */
        "Accept-Language"?: parameters["Accept-Language"];
      };
    };
    responses: {
      /** Response Body. */
      200: {
        headers: {};
        schema: definitions["status"];
      };
      400: responses["400"];
      401: responses["401"];
      403: responses["403"];
      404: responses["404"];
      405: responses["405"];
      406: responses["406"];
      413: responses["413"];
      414: responses["414"];
      415: responses["415"];
      500: responses["500"];
      502: responses["502"];
      503: responses["503"];
    };
  };
  /** Use this API to fetch the individual units' rotation points.<p><strong>OperationId:</strong>getRoomRotationPoints</p> <p>The maximum allowable limit for this API is <strong>100</strong>.</p> */
  getRoomRotationPoints: {
    parameters: {
      path: {
        /** Unique Id for the Hotel */
        hotelId: string;
      };
      query: {
        /** The date for which the Room Rotation Points are being requested */
        roomRotationPointsDate: string;
        /** Indicates maximum number of records the API should return. */
        limit?: number;
        /** Index or initial index of the set(page) being requested. If the index goes out of the bounds of the total set count then no data will be returned. */
        offset?: number;
        /** List of Room Classes for which to return Room Rotation Points. Multiple values can be entered by adding multiple query parameters. */
        roomClasses?: string[];
        /** List of Room Types for which to return Room Rotation Points. Multiple values can be entered by adding multiple query parameters. */
        roomTypes?: string[];
        /** List of Room Ids for which to return Room Rotation Points. Multiple values can be entered by adding multiple query parameters. */
        roomIds?: string[];
      };
      header: {
        /** Bearer token that needs to be passed which is generated post user authentication */
        authorization: parameters["authKey"];
        /** Pass this header as true, if payload needs DVM */
        externalData?: parameters["externalData"];
        /** Client or Partner's Application Key */
        "x-app-key": parameters["x-app-key"];
        /** Request Id of an incoming request */
        "x-request-id"?: parameters["x-request-id"];
        /** Customer's Integration Application Id */
        "x-originating-application"?: parameters["x-originating-application"];
        /** Mandatory parameter to identify the hotel code where the end user is logged in */
        "x-hotelid": parameters["x-hotelid"];
        /** External system code. */
        "x-externalsystem"?: parameters["x-externalsystem"];
        /** Language code */
        "Accept-Language"?: parameters["Accept-Language"];
      };
    };
    responses: {
      /** Response object for fetching Room Rotation Points. Based on the criteria, Room Rotation Points information is returned */
      200: {
        headers: {};
        schema: definitions["getRoomRotationPoints"];
      };
      /** Room Rotation Points not found. */
      204: never;
      400: responses["400"];
      401: responses["401"];
      403: responses["403"];
      404: responses["404"];
      405: responses["405"];
      406: responses["406"];
      413: responses["413"];
      414: responses["414"];
      415: responses["415"];
      500: responses["500"];
      502: responses["502"];
      503: responses["503"];
    };
  };
  /** Use this operation to update balance forward and adjusted points of individual rooms. <p><strong>OperationId:</strong>putRoomRotationPoints</p> */
  putRoomRotationPoints: {
    parameters: {
      path: {
        /** Unique Id for the Hotel */
        hotelId: string;
      };
      body: {
        /** Request details containing room, balance forward and adjusted points to update. */
        roomRotationPointsAdjustment: definitions["roomRotationPointsAdjustment"];
      };
      header: {
        /** Bearer token that needs to be passed which is generated post user authentication */
        authorization: parameters["authKey"];
        /** Pass this header as true, if payload needs DVM */
        externalData?: parameters["externalData"];
        /** Client or Partner's Application Key */
        "x-app-key": parameters["x-app-key"];
        /** Request Id of an incoming request */
        "x-request-id"?: parameters["x-request-id"];
        /** Customer's Integration Application Id */
        "x-originating-application"?: parameters["x-originating-application"];
        /** Mandatory parameter to identify the hotel code where the end user is logged in */
        "x-hotelid": parameters["x-hotelid"];
        /** External system code. */
        "x-externalsystem"?: parameters["x-externalsystem"];
        /** Language code */
        "Accept-Language"?: parameters["Accept-Language"];
      };
    };
    responses: {
      /** Response Body. */
      200: {
        headers: {};
        schema: definitions["status"];
      };
      400: responses["400"];
      401: responses["401"];
      403: responses["403"];
      404: responses["404"];
      405: responses["405"];
      406: responses["406"];
      413: responses["413"];
      414: responses["414"];
      415: responses["415"];
      500: responses["500"];
      502: responses["502"];
      503: responses["503"];
    };
  };
  /** Use this API to fetch profile Rooms with Room Ownership or Owner Referral records associated. <p><strong>OperationId:</strong>getRoomOwnerships</p> */
  getRoomOwnerships: {
    parameters: {
      path: {
        /** Unique ID of profile. */
        profileId: string;
      };
      query: {
        /** Unique Id(s) for the Hotel(s). Multiple Hotels can be entered by adding multiple query parameters. */
        hotelIds?: string[];
        /** The starting value of the date range. */
        startDate?: string;
        /** The ending value of the date range. */
        endDate?: string;
        /** Include Owner Referral in response flag. */
        includeReferral?: boolean;
        /** Flag indicating if only rooms available for booking during the date range specified should be included in response. */
        includeAvailableRoomsOnly?: boolean;
      };
      header: {
        /** Bearer token that needs to be passed which is generated post user authentication */
        authorization: parameters["authKey"];
        /** Pass this header as true, if payload needs DVM */
        externalData?: parameters["externalData"];
        /** Client or Partner's Application Key */
        "x-app-key": parameters["x-app-key"];
        /** Request Id of an incoming request */
        "x-request-id"?: parameters["x-request-id"];
        /** Customer's Integration Application Id */
        "x-originating-application"?: parameters["x-originating-application"];
        /** Mandatory parameter to identify the hotel code where the end user is logged in */
        "x-hotelid": parameters["x-hotelid"];
        /** External system code. */
        "x-externalsystem"?: parameters["x-externalsystem"];
        /** Language code */
        "Accept-Language"?: parameters["Accept-Language"];
      };
    };
    responses: {
      /** Response object for Rooms with Room Ownership or Owner Referral records. Based on the criteria, associated Owner Rooms are returned. */
      200: {
        headers: {};
        schema: definitions["associatedRoomOwnershipListDetails"];
      };
      /** Associated Room Ownership not found. */
      204: never;
      400: responses["400"];
      401: responses["401"];
      403: responses["403"];
      404: responses["404"];
      405: responses["405"];
      406: responses["406"];
      413: responses["413"];
      414: responses["414"];
      415: responses["415"];
      500: responses["500"];
      502: responses["502"];
      503: responses["503"];
    };
  };
  /** Get Room Ownership details for specific room(s) or owners. Hotel Id(s) and at least one other search criteria is required. <p><strong>OperationId:</strong>getRoomOwners</p> */
  getRoomOwners: {
    parameters: {
      query: {
        /** Unique Id(s) for the Hotel(s) queried. */
        hotelIds: string[];
        /** Family name, last name. */
        surname?: string;
        /** Given name, first name or names */
        givenName?: string;
        /** The starting value of the start date range. */
        startDateFrom?: string;
        /** The ending value of the start date range. */
        startDateTo?: string;
        /** The starting value of the end date range. */
        endDateFrom?: string;
        /** The ending value of the end date range. */
        endDateTo?: string;
        /** List of Room Classes for which to return Room Owners. Multiple values can be entered by adding multiple query parameters. */
        roomClasses?: string[];
        /** List of Room Types for which to return Room Owners. Multiple values can be entered by adding multiple query parameters. */
        roomTypes?: string[];
        /** List of Room Ids for which to return Room Owners. Multiple values can be entered by adding multiple query parameters. */
        roomIds?: string[];
        /** Contract Number of the Ownership Record. */
        contractNumber?: string;
        /** Indicates whether to return inactive records. Records are considered inactive when the end date of the ownership record is prior to the current property business date. */
        includeInactive?: boolean;
        /** Indicates maximum number of records the API should return. */
        limit?: number;
        /** Index or initial index of the set(page) being requested. If the index goes out of the bounds of the total set count then no data will be returned. */
        offset?: number;
      };
      header: {
        /** Bearer token that needs to be passed which is generated post user authentication */
        authorization: parameters["authKey"];
        /** Pass this header as true, if payload needs DVM */
        externalData?: parameters["externalData"];
        /** Client or Partner's Application Key */
        "x-app-key": parameters["x-app-key"];
        /** Request Id of an incoming request */
        "x-request-id"?: parameters["x-request-id"];
        /** Customer's Integration Application Id */
        "x-originating-application"?: parameters["x-originating-application"];
        /** Mandatory parameter to identify the hotel code where the end user is logged in */
        "x-hotelid": parameters["x-hotelid"];
        /** External system code. */
        "x-externalsystem"?: parameters["x-externalsystem"];
        /** Language code */
        "Accept-Language"?: parameters["Accept-Language"];
      };
    };
    responses: {
      /** Response object for List of Room Owners. Based on the criteria, associated List of Room Owners are returned. */
      200: {
        headers: {};
        schema: definitions["roomOwnersListDetails"];
      };
      /** Room Owners not found. */
      204: never;
      400: responses["400"];
      401: responses["401"];
      403: responses["403"];
      404: responses["404"];
      405: responses["405"];
      406: responses["406"];
      413: responses["413"];
      414: responses["414"];
      415: responses["415"];
      500: responses["500"];
      502: responses["502"];
      503: responses["503"];
    };
  };
  /** This API facilitates status check of room rotation service <p><strong>OperationId:</strong>pingRoomRotationService</p> */
  pingRoomRotationService: {
    parameters: {
      query: {
        /** Opera Ping request input type */
        operaPingInput?: string;
      };
      header: {
        /** Bearer token that needs to be passed which is generated post user authentication */
        authorization: parameters["authKey"];
        /** Pass this header as true, if payload needs DVM */
        externalData?: parameters["externalData"];
        /** Client or Partner's Application Key */
        "x-app-key": parameters["x-app-key"];
        /** Request Id of an incoming request */
        "x-request-id"?: parameters["x-request-id"];
        /** Customer's Integration Application Id */
        "x-originating-application"?: parameters["x-originating-application"];
        /** Mandatory parameter to identify the hotel code where the end user is logged in */
        "x-hotelid": parameters["x-hotelid"];
        /** External system code. */
        "x-externalsystem"?: parameters["x-externalsystem"];
        /** Language code */
        "Accept-Language"?: parameters["Accept-Language"];
      };
    };
    responses: {
      /** Response for Ping operation. */
      200: {
        headers: {};
        schema: definitions["pingDetail"];
      };
      /** pingRoomRotationService not found. */
      204: never;
      400: responses["400"];
      401: responses["401"];
      403: responses["403"];
      404: responses["404"];
      405: responses["405"];
      406: responses["406"];
      413: responses["413"];
      414: responses["414"];
      415: responses["415"];
      500: responses["500"];
      502: responses["502"];
      503: responses["503"];
    };
  };
}

export interface external {}
