/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/hotels/{hotelId}/reservations/{reservationId}/arrivalDate/{arrivalDate}/upsellOffers": {
    /** This API will allow a user to retrieve a retrieve a list of available upsell offers based on the search criteria specified in the request body, inventory availability and current reservation details. <p><strong>OperationId:</strong> getUpsellOffers</p> */
    get: operations["getUpsellOffers"];
    /** This API will allow a user to update a reservation with an offer selected from the list of available upsell offers based on the unique offer id specified in the request body. <p><strong>OperationId:</strong> postUpsellOffers</p> */
    post: operations["postUpsellOffers"];
  };
}

export interface definitions {
  /** @description Success and Failure Summary Data */
  UpsellOffers: {
    Items?: definitions["Items"][];
    /** @example 1 */
    totalResults?: number;
    /** @example 0 */
    offset?: number;
    /** @example 1 */
    count?: number;
    /** @example false */
    hasMore?: boolean;
    /** @example 0 */
    limit?: number;
  };
  /** @description Success and Failure Summary Data */
  Items: {
    upsellOffers?: definitions["UpsellOffer"][];
  };
  UpsellOffer: {
    /**
     * @description describes type of an offer
     * @example room_upgrade
     */
    offerType?: string;
    /**
     * @example zero_to_one
     * @enum {string}
     */
    selectionType?: "zeroToOne" | "zeroToMany";
    offers?: definitions["Offers"][];
  };
  Offers: {
    /**
     * Format: uuid
     * @description A unique upsell ID per upsell offer
     */
    offerId?: string;
    /**
     * @description offer name
     * @example Deluxe King Suite
     */
    name?: string;
    /** @example Rest easy in the 600-square-foot suite with sitting area and cityscape views. Enjoy pillow top mattress, pull out sofa bed, premium mini bar, 24 hour room service, and a large marble bathroom. */
    description?: string;
    images?: definitions["Image"];
    price?: {
      /** @example 33.94 */
      amount?: number;
      /**
       * @description This is an ISO 4217(https://en.wikipedia.org/wiki/ISO_4217) currency code.
       * @example USD
       */
      currency?: string;
    };
    /** @example 16.06 */
    savings?: string;
    /** @example per_unit_per_night */
    chargeFrequency?: string;
    /** @example 33.94 */
    fixedCharge?: number;
    roomTypeCode?: string[];
  };
  Image: {
    /** @example https://example.com/img_url1.jpg */
    big?: string;
    /** @example https://example.com/img_url2.jpg */
    small?: string;
  };
  Item: {
    /** Format: uuid */
    offerId?: string;
  };
  /** @description Complex type that contains error detail */
  errorDetail: {
    /** @description Holds error details in short */
    title?: string;
    /** @description Holds error details */
    detail?: string;
    /** @description Holds specific error code */
    errorCode?: string;
  };
  /** @description Complex type that contains internal server error instance details for a REST call */
  errorInstanceISE: {
    /**
     * @description Holds error type
     * @example http://www.example.org/protocols/..
     */
    type?: string;
    /**
     * @description Holds error details in short
     * @example Internal Server Error
     */
    title?: string;
    /** @example 500 */
    status?: number;
    /**
     * @description Holds error details
     * @example Internal Server Error
     */
    detail?: string;
    /** @description Holds specific error code */
    errorCode?: string;
    /** @description Holds List of errors */
    errorDetails?: definitions["errorDetail"][];
  };
  /** @description Complex type that contains not found error instance details for a REST call */
  errorInstanceNF: {
    /**
     * @description Holds error type
     * @example http://www.example.org/protocols/..
     */
    type?: string;
    /**
     * @description Holds error details in short
     * @example Not Found
     */
    title?: string;
    /** @example 404 */
    status?: number;
    /**
     * @description Holds error details
     * @example Unable to find HotelId or ReservationId
     */
    detail?: string;
    /** @description Holds specific error code */
    errorCode?: string;
    /** @description Holds List of errors */
    errorDetails?: definitions["errorDetail"][];
  };
  /** @description Complex type that contains refuse request error instance details for a REST call */
  errorInstanceUMT: {
    /**
     * @description Holds error type
     * @example http://www.example.org/protocols/..
     */
    type?: string;
    /**
     * @description Holds error details in short
     * @example Unsupported Media Type
     */
    title?: string;
    /** @example 415 */
    status?: number;
    /**
     * @description Holds error details
     * @example Unsupported Media Type
     */
    detail?: string;
    /** @description Holds specific error code */
    errorCode?: string;
  };
}

export interface parameters {
  /** @enum {string} */
  accept: "application/json; charset=UTF-8" | "application/json";
  /** @enum {string} */
  acceptForPost: "application/json; charset=UTF-8" | "application/json";
  authorization: string;
  "x-app-key": string;
  /** @description Partner's Unique Nor1 Provider ID */
  providerId: string;
  /** @description Language code */
  "Accept-Language": string;
}

export interface operations {
  /** This API will allow a user to retrieve a retrieve a list of available upsell offers based on the search criteria specified in the request body, inventory availability and current reservation details. <p><strong>OperationId:</strong> getUpsellOffers</p> */
  getUpsellOffers: {
    parameters: {
      header: {
        Accept: parameters["accept"];
        Authorization?: parameters["authorization"];
        "x-app-key"?: parameters["x-app-key"];
        /** Partner's Unique Nor1 Provider ID */
        providerId?: parameters["providerId"];
        /** Language code */
        "Accept-Language"?: parameters["Accept-Language"];
      };
      path: {
        /** Unique ID of the hotel where reservation is searched based on reservation Id. */
        hotelId: string;
        /** A unique identifying value for reservation assigned by the creating system. */
        reservationId: string;
        /** Arrival Date of the reservation. */
        arrivalDate: string;
      };
    };
    responses: {
      /** Successful Response */
      200: {
        headers: {};
        schema: definitions["UpsellOffers"];
      };
      /** No Offers Found */
      204: never;
      /** Unable to find HotelId or ReservationId */
      404: {
        schema: definitions["errorInstanceNF"];
      };
      /** System Error */
      500: {
        schema: definitions["errorInstanceISE"];
      };
      /** Bad Gateway */
      502: unknown;
      /** Service Unavailable */
      503: unknown;
    };
  };
  /** This API will allow a user to update a reservation with an offer selected from the list of available upsell offers based on the unique offer id specified in the request body. <p><strong>OperationId:</strong> postUpsellOffers</p> */
  postUpsellOffers: {
    parameters: {
      header: {
        consumes?: parameters["acceptForPost"];
        Authorization?: parameters["authorization"];
        "x-app-key"?: parameters["x-app-key"];
        /** Partner's Unique Nor1 Provider ID */
        providerId?: parameters["providerId"];
        /** Language code */
        "Accept-Language"?: parameters["Accept-Language"];
      };
      path: {
        /** Unique ID of the hotel where reservation is searched based on reservation Id. */
        hotelId: string;
        /** A unique identifying value for reservation assigned by the creating system. */
        reservationId: string;
        /** Arrival Date of the reservation. */
        arrivalDate: string;
      };
      body: {
        body: definitions["Item"];
      };
    };
    responses: {
      /** Successful Response */
      200: {
        schema: definitions["UpsellOffers"];
      };
      /** Unable to find HotelId or ReservationId */
      404: {
        schema: definitions["errorInstanceNF"];
      };
      /** Unsupported Media Type */
      415: {
        schema: definitions["errorInstanceUMT"];
      };
      /** System Error */
      500: {
        schema: definitions["errorInstanceISE"];
      };
      /** Bad Gateway */
      502: unknown;
      /** Service Unavailable */
      503: unknown;
    };
  };
}

export interface external {}
